### ISSUE TITLE
Add method to add and remove values in a multi choice

### ISSUE THREAD

**Issue by vertex-npratt** [select2/select2#1181]
Current functionality only provides for setting and retrieving the entire selection.  It would be a useful addition if there was an addVal and removeVal() method that add and remove selections to the multi choice programatically

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.

**Comment by StanAccy** [comment]
Do you want me to bump every ticket I enter in future? :-)

**Comment by kevin-brown** [comment]
@StanAccy If you find a ticket that you really need fixed and hasn't seen much attention for a while, definitely bump it. It tends to [work](https://github.com/select2/select2/issues/279) [really](https://github.com/select2/select2/issues/781) [well](https://github.com/select2/select2/issues/1345) for popular issues

For something like this, you can now just set the `required` property on the `<option>` (create it if necessary), and trigger the `change` event. Select2 will be able to detect the change, and it won't require keeping track of _all of the other options_ which are selected.

**Comment by arborrow** [comment]
I'm trying to figure out the status of having a way to select or unselect all of the options with a keyboard shortcut. There seems to be some scripts that I was not able to immediately get working. I realize this functionality has been much talked about in https://github.com/select2/select2/issues/195 and https://github.com/select2/select2/issues/279#issuecomment-32131960 although I am not sure where things currently stand. Is there a version of select2 that implements this or are folks still adding their own custom code? Is there a current issue I am not seeing I should be aware of that I can bump or +1? I did implement closeOnSelect: false but it seems to return to the top of the list on enter rather than the next unselected item so it ends up not being that quick. My apologies if I am missing something obvious.
