### ISSUE TITLE
results dropdown does not scroll to selected item

### ISSUE THREAD

**Issue by andrewalcantara** [select2/select2#1408]
to reproduce:
1. open dropdown
2. scroll dropdown several lines down (ensure it is at least one full height off the dropdown) and then select an item
3. now click to open dropdown again, the dropdown is scroll all the way at top instead of where the scroll position of the selected item

I did some troubleshooting and I understand that when opening the method ensureHighlightVisible (line 1251) did its job to position the scroll correctly, however it gets reset to scroll top of 0 when postRender() is called on line 1587.

Thanks.

**Comment by DanielConant** [comment]
I just downloaded 4.0.2. This problem is still there. I did notice if I click the down arrow again the list will scroll to the selected item. It is the initial opening where the selected item is not at the top of the list. If you scroll down to the selected item it is highlighted. Is there something I can do to correct this?

**Comment by SamuelJohnsonMedia** [comment]
This is still an issue with 4.0.13; why was it closed?
