### ISSUE TITLE
Placeholder not showing

### ISSUE THREAD

**Issue by OliverRC** [select2/select2#155]
As the title says, I have added Select 2 to my ASP MVC3 Project but the placeholder is not showing. I have tried adding it through the data attribute and through javascript.

 $("#release-select").select2({
        placeholder: "Select a release..."
      });

**Comment by brandonhall** [comment]
We have a Backbone app which inits select2 before they are visible on the page. As a result, the `select2-search__field` width is always `0px` because that's the `innerWidth` when it's initialized. This caused placeholders to be hidden.

Here's the relevant block of code in `select2`...

```
          if (this.$search.attr('placeholder') !== '') {
            width = this.$selection.find('.select2-selection__rendered').innerWidth();
          } else {
            var minimumWidth = this.$search.val().length + 1;
            width = (minimumWidth * 0.75) + 'em';
          }
```

As a result, the solution was to use setTimeout as mentioned above but that causes all sorts of bouncing around on the page as the elements are initialized.

I added an OR condition to use 100% if innerWidth is 0 to prevent this. Like so: `width = this.$selection.find('.select2-selection__rendered').innerWidth() || '100%'`

I'm not sure it's the most elegant solution but it does the job and fixes the issue.

**Comment by kevin-brown** [comment]
@brandonhall Can you create a new ticket for this with 4.0.0? Thanks.

**Comment by technofreaky** [comment]
+1.

i am also unable to show placeholder after selecte2 init.
instead of showing the placeholder. it automatically selects the first selection option where it dose not have attribute **selected**

**Comment by mkoch42** [comment]
Has this been addressed?  When a select2 is ajaxed into a hidden div and then the div is shown, the placeholder is not visible. If you select an option and then remove it, the placeholder becomes visible.  I confirmed this is the case in both 4.0.1 and 4.0.2   

Thanks
Matt

**Comment by nasospsa** [comment]
Great fix @brandonhall I might be making a pull request with your solution so we can all get it sooner.

Also another fix I have found regarding this issue (im having the exact same problem, backbone app etc.):

`$elementWithSelect2.find('.select2-search__field.').css({width: ''});`

It removes the css width property so the placeholder is visible 😉

**Comment by LoganGS** [comment]
In my case, no placeholder text was showing because I had updated the **templateSelection** property to return a property value that existed in my results loaded via AJAX, but did not exist on the placeholder object.

So, I just reverted my templateSelection to return the **text** property of the object:
```
templateSelection: function (option) {
    return option.text
}
```

All is well, there is peace on Earth once again.

**Comment by sdeering** [comment]
I did this and it worked.

```
<select class="select2-suburb select2 form-control" name="suburb">
     <option value="">Select a suburb</option>
 </select>
```

```
processResults: function(results) {
     return results ? results : '';
}
```

**Comment by mgarcia96** [comment]
Hard option:

`$(".select2-selection__placeholder").text('Search documents')`

**Comment by RodolfoE** [comment]
I found the answer!
just did this:
 $('#id')
    .select2({
      data: prod,
      placeholder: 'Place holder'',
      width: '100%'
    })
    .val('null')
    .change();

**Comment by vds-wgit** [comment]
If someone still faces this issue in the multi select just use this in your CSS file.  Works for me
` .select2-search__field{
    width: 100% !important;
  }`

**Comment by FatemeMahdavi-developer** [comment]
add data-placeholder attribute  on select tag and empty first option tag
