### ISSUE TITLE
width: resolve needs a bit more width to account for the arrow down icon

### ISSUE THREAD

**Issue by wijnand1** [select2/select2#1556]
![image](https://f.cloud.github.com/assets/3251351/834597/35cea9f6-f2c5-11e2-837f-b5433f11bdbc.png)
![image](https://f.cloud.github.com/assets/3251351/834603/50d84fa4-f2c5-11e2-996e-e693ff720079.png)

Adding a bit more space in line 1721 fixes this

 // finally, fallback on the calculated width of the element
return this.opts.element.outerWidth(false) === 0 ? 'auto' : (this.opts.element.outerWidth(false) + 15) + 'px'

**Comment by andreyvolokitin** [comment]
I am not quite sure how it doesn't make sense. This is a classic problem and I agree that it can be quite hard to solve or unsolvable. The width of original select is always big enough to accommodate its widest option, but not much bigger. The width of select2 container should differ from that due to paddings, width of result text string, arrow width, etc. The final goal should be to make select2 container wide enough to accommodate the widest option (just like original select logic). And that could be a big problem because we first need to know the proper width of result text string and other values like horizontal paddings, widest text string within result field, arrow width and so on. Looks like it requires at least prerendering of the select2 to know this values, and god knows what else. But IMO the issue is important and at least deserves attention
