### ISSUE TITLE
Message "No results" doesn't appears when createSearchChoice function provided

### ISSUE THREAD

**Issue by alsma** [select2/select2#1585]
Hello!
Check this fiddle: http://jsfiddle.net/nDAAU/2/
Steps to reproduce:
- type "test" and see result
- type "test" again
### Extual:

Empty results block appears
### Expected:

self.opts.formatNoMatches message should appears
### Results of investigation:

The issue in following condition on line 2960 in postprocessResults function,
no matches will not appeared never because createSearchChoice function provided even if result of this function will undefined or null or just filtered as .select2-selected

//If all results are chosen render formatNoMAtches
(!this.opts.createSearchChoice && !choices.filter('.select2-result:not(.select2-selected)').length > 0) 

Thanks a lot in advance,  hope issue will be fixed!
Kind regards!

**Comment by WARrior-Alex** [comment]
This bug is still unresolved!
Let me explain. You have select2 with createSearchChoice function, wich should add value only in certain cases, ex. only if valid email was entered. In all other cases this function returns undefined. User entered some not email text, which has filtered only one item from values list. User selected this item and entered the same text. The query function (no matter if user defined or default) filters again to the single item, but internal logic removes this item as it was already selected. So user gets empty list, but without "not found" message, because logic pointed above checks if createSearchChoice function is defined and expects this function **always** returns some value.
