### ISSUE TITLE
Case insensitive on tags

### ISSUE THREAD

**Issue by soullivaneuh** [select2/select2#1704]
Here is a way to check tags unity with case insensitive ?

**Comment by mattbrictson** [comment]
The `matcher` is not relevant here. The issue is that select2 uses `indexOf` (not `matcher`) to decide whether to insert a new choice or reuse an existing one. Since indexOf is case-sensitive, you don't get the desired behavior.

I solved it by passing in a custom `createSearchChoice` callback in the select2 options. It reuses the existing tag value if there is a case-insensitive match, instead of creating a new choice.

Assuming `tags` holds an array of strings that are the allowed tag values, then (CoffeeScript):

```coffeescript
createSearchChoice: (term)->
  choice =
    id: $.trim(term)
    text: $.trim(term)
  for each in tags
    if each.toUpperCase() == $.trim(term).toUpperCase()
      choice.id = each
      choice.text = each
      break
  choice
```
