### ISSUE TITLE
selectOnBlur function does not validate against duplicate choices when creating UI elements

### ISSUE THREAD

**Issue by Corrosive** [select2/select2#1739]
When selectOnBlur is enabled, the user is able to add multiple of the same choice to the UI of <select multiple> and <input type="hidden"> inputs.

To replicate, simply type a tag, add it, type it again, and have the element lose focus.  A duplicate choice should pop up.  When accessing $('...').val() however, it would appear that the internal value IS validated, because it only contains one instance of the token's text.

This wouldn't really be a big deal, except that when you remove any of the duplicated tokens, the choice UI element and value are removed, but the additional duplicate choice UI elements remain, which could cause a number of problems, or at least some very confused users.

My apologies if I'm jumbling up terminology here-- apart from context, it's not particularly intuitive which entities are supposed to be referred to as 'choices' vs 'tokens' or 'tags' ;)

**Comment by kevin-brown** [comment]
This should be fixed in 4.0, as the `selectOnClose` (renamed option) now actually triggers the same process a normal user would when selecting the choice.

If it is not fixed, please add a :+1: to the ticket to bring it to our attention. Please also include an example that we can test to verify that it is not actually working.
