### ISSUE TITLE
Able to set the list to a disabled value but not then read its value back

### ISSUE THREAD

**Issue by aquavark** [select2/select2#1740]
In a select, values can be set to disabled, and will display in the list but with a grey background and cannot be user selected (as expected).

However, calling $("#list").select2("val",value) will set this item to be the visible one on the list.

When you then attempt to get the value back (using $('#list').val()) you get "null" returned, and not the value that is being displayed on the select2.

This has shown up as I am actually after a method to be able to set disabled items as the selected one programmatically, but not to let the user actually choose them (so they have to be in the list to do this, but set to disabled from the user perspective). In this use case I am limiting background colours for user selected, but selecting from another list can choose background colours that are not available to the user.

**Comment by kevin-brown** [comment]
This should be fixed in 4.0, `.select2("val")` is mapped to `.val()` so things behave in similar ways to a regular `<select>`.

If it is not fixed, please add a :+1: to the ticket to bring it to our attention. Please also include an example that we can test to verify that it is not actually working.
