### ISSUE TITLE
Ajax with infinite scroll - pagination problem

### ISSUE THREAD

**Issue by mattihelminen** [select2/select2#1833]
Infinite scroll works well with data that you only select once or you don't need to change. Problem is when you scroll down dropdown and select an option from second "page", close select2 and then open it again. Position is reset to page one and value you choose is not selected. Is there any workaround for this issue? It would be nice if select2 remembered on what page your option was when using infinite scroll.

**Comment by kevin-brown** [comment]
You should be able to avoid this now by setting `selectOnClose` to `false`, which correctly works for AJAX data.

**Comment by maxgalbu** [comment]
@kevin-brown the issue is not when the user doesn't select something (and you force the selection with selectOnClose), it's when select2 doesn't restore the page where the selection was (with infinite scroll).

Example 1: I open the select2 and select the second option. If I reopen the select2, the second option will be selected to show what was selected.

Example 2: I open the select2 and scroll enough to trigger the infinite scroll and get to the 10th page, then select an option from that page. When i reopen the select2 it will start again from the 1st page and I need to scroll again to the 10th page.

**Comment by maxgalbu** [comment]
[This pull request](https://github.com/select2/select2/pull/2063) could help but it's still not user friendly not to restore the page where the record was, in my opinion
