### ISSUE TITLE
Select2 val does not always reflected order of selected items

### ISSUE THREAD

**Issue by pimlottc** [select2/select2#1861]
If you have a sortable multiple selection select2 input, the result of select2("val") does not change when you re-arrange the order.  For example, if you select "a", "b" and "c", then drag-and-drop so the selection appears as "c" "a" "b", $("#letters").select2("val") will still return ["a", "b", "c"].  However, $("#letters").select2("data") returns the items in the correct modified order.

Likewise, $("letters").val() will show the original order as well; which means the default form serialization will not accurately express the order of selection.

IMHO, the element value should always be consistent with the visual selection.

**Comment by TwentyOneSolutions** [comment]
> The solution is to not use a <select> with <option>s, but an <input type="hidden"> ...
And what is the solution for select2 v4?

**Comment by kevin-brown** [comment]
> And what is the solution for select2 v4?

Select2 v4 actually fixes this issue.

**Comment by TwentyOneSolutions** [comment]
@kevin-brown - I'm not sure what you mean.  I'm using v4 and when I use a select2 list with `multiple` the order of insertion is not maintained.

For example, if I have in the list the options: "a", "b", "c", "d", "e", and I select the options in the order: "b", "a", "d", then each time I select an item it is "inserted" in the order of the option appearance, and not in the order of "selection", and therefore `val()` returns `["a", "b", "d"]` instead of the desired result `["b", "a", "d"]`.

**Comment by kevin-brown** [comment]
@TwentyOneSolutions This ticket appears to have been about the `select2('data')` and `select2('val')` methods being out of sync with what was being displayed to the user. This is a bug we fixed in version 4, now all methods return the order which matches the `.val()` method.

The problem you are seeing, where the order of selections is not being reflected in `.val()`, is being tracked in https://github.com/select2/select2/issues/3106.

**Comment by TwentyOneSolutions** [comment]
I see.  Thank you for clarifying.

**Comment by sonianand11** [comment]
For those who are looking for solution to preserve the order when item is selected, here is long thread
https://github.com/select2/select2/issues/3106 and a workaround https://github.com/select2/select2/issues/3106#issuecomment-333341636, https://github.com/select2/select2/issues/3106#issuecomment-539469984
