### ISSUE TITLE
Cant loose focus when select-input has placeholder. [IE11]

### ISSUE THREAD

**Issue by vic** [select2/select2#2084]
Hey!

One of our clients just came along a bug using Internet Explorer 11. 

Thing is, after initing a select2 field, we set a placeholder on the generated input element (the one having the .select2-input class). We made so to have the select2 input always present a placeholder even when the user has already selected some options.

I've created a minimal [JSFiddle][1] reproducing the bug. I confirmed this bug is present in at least IE > 8, everything is fine in chrome/firefox.

Dunno why setting a placeholder attribute would impact on select2 functionality.

In the mean time we removed the placeholder from the .select2-input and just use the placeholder option for select2.

[1]: http://jsfiddle.net/4USXu/

**Comment by pavellishin** [comment]
I don't believe this issue is fixed, but I can't recreate the damned thing in a fiddle.

In our app (password protected, can't link) adding the `placeholder` option to the select2 init will cause IE11 (on Windows 7; haven't tested other combinations yet) to maintain focus on the created input. Removing that option causes the problem to stop.

I don't know why I cannot reproduce this in a fiddle.

**Comment by kevin-brown** [comment]
@pavellishin This ticket is for an older version of Select2.

The Select2 4.0.0 ticket is available at https://github.com/select2/select2/issues/3300.

**Comment by sirNemanjapro** [comment]
Issue still present.

**Comment by jayprakash-manjhi** [comment]
Hi Everyone,

We are facing the similar issue on IE11, when we open Select2 Dropdown and then click on Input Field (type text field with placeholder) so its allowing to edit placeholder text.

**Root cause on IE11:** Select2 inline search always get focused even after close the dropdown.

**Workaround:** Forcefully trigger focus on currently clicked input box, which remove the focus event from the Select2 inline search.

> **Below is the workaround code that is worked for us.**

```
$(document).on("click","input[type='text']", function(e){   
	e.preventDefault();  
	var self = e.currentTarget;
	$('.select2-search__field').trigger('blur'); //remove focus from select inline search field.
        $(self).trigger('focus'); // set focus on currently clicked input field.
});

```
