### ISSUE TITLE
infinite scrolling on selected tags

### ISSUE THREAD

**Issue by igler** [select2/select2#2221]
I'd like to use infinite scrolling on selected tags. The scenario is, that there are a lot of selectable items in a multiple slelect2 (around 650 items). The user can put all of them into the <code>ng-model</code> variable by clicking a button. The problem is that after doing so rendering all the tags takes around half a minute. So I wonder if it is possible to use infinite scrolling on the shown tags as it can be used on selections?

**Comment by kevin-brown** [comment]
Unfortunately this is not a feature request which we will be investigating further, due to the technical complexity and lack of support. This is theoretically possible in the new version of Select2 (4.0.0) by using a custom selection adapter, allowing you to customize how the selection is rendered so it can be done in a way that is more efficient. It is not something which we are planning to bring into the core of Select2.
