### ISSUE TITLE
Open menu closes sometimes directly after opening

### ISSUE THREAD

**Issue by smgadaleta** [select2/select2#2300]
Sometimes, when clicking into the menu, the drop down opens briefly but then closes again automatically without moving mouse out of the menu or clicking away.

Tracing through the code, I found that commenting out the line 2212 in select2.js in the function initSelection (comment out the self.close() there) fixes the issue.

I am using select2 from within AngularJS

**Comment by tobias47n9e** [comment]
I believe that this sometimes happens when the overlay opens above the click area that opens the overlay. Try holding down your mouse, move the cursor outside of the overlay an then release the button. If the overlay stays open, then you are mixing the behaviours of opening the overlay, with the ability to select items by releasing the mouse button. For debugging just give this `div` a value that moves it far away from the click area:

```
.select2-dropdown--below {
    top: 100px
}
```
