### ISSUE TITLE
select2-search-choice-focus event please

### ISSUE THREAD

**Issue by kosir** [select2/select2#2322]
Hello,
is it possible to add event for "select2-search-choice-focus". I need to get element text for selected items, when they are highlighted. I only succeed to get it with doubleclick event, but I would like to get it when I use keyboard left/right key. So it would be perfect, if event would be fired, when one of selected items (or tags) is highlighted. I would also like to programatically fire this event - "highligth" or change selection on these items from code. If this is not understandable, I attached image, what I mean... Thanks in advance for any help! Best regards, Milan
![select2](https://cloud.githubusercontent.com/assets/5576404/2809938/0040e282-cd8e-11e3-9140-a09241aaa5a7.png)

**Comment by kevin-brown** [comment]
As [mentioned in the 4.0 release notes](https://github.com/select2/select2/releases/tag/4.0.0-beta.1), there [is no way to make a `<select>` read-only](http://stackoverflow.com/q/368813/359284) and because [4.0 supports the `<select>` as the primary data source](https://select2.github.io/announcements-4.0.html#hidden-input), I'm going to close this ticket off.

**Comment by kevin-brown** [comment]
With the large restructuring of Select2 that happened during 4.0, I no longer have plans for implementing this event. You can do it through the use of a decorator on the selection adapters if you are interested in implementing this yourself.
