### ISSUE TITLE
Load data on demand

### ISSUE THREAD

**Issue by baurez** [select2/select2#236]
A little request,

we could load data via JSON or AJAX. that's ok !
we could load only a part of result via JSON or AJAX like a paging system... so we could load only 10 elements even if there are 1000 results...

could we make the same thing without AJAX request but via a select and is data ?

if yes... what is the option ?

if no... :(

:) Thank you

**Comment by derntl** [comment]
I know this was closed a long time ago, but since I needed to solve this for my app, there is a simple way to dynamically load data from a local JSON source based on a query term, if you do not want to fetch data remotely via AJAX. I needed this because I have tens of thousands of items for the select box stored in a local JSON variable. So the select2 initialization took several seconds each time, and AJAX was not an option.

The solution is to make select2 believe the data is being fetched via AJAX, but instead populate the resuls array from a local data source:

```
yourDropdown.select2({
	minimumInputLength: 3, // or whatever you prefer
	ajax: {
		url: 'someFakeAjaxScript.php', // this is any server side script that exists and returns an empty array 
		data: (params) => {
			// here we need to store the user's query term
			select.data('queryTerm', params.term);
			return {};
		},
		processResults: () => {
			let options = [];
			let queryTerm = select.data('queryTerm');
			yourHugeLocalDataArray.forEach(data => {
				if(data.text.includes(queryTerm)) // or some other check depending on your data
					options.push({id: data.id, text: data.text});
			});
			return {
				results: options
			};
		}
	}
});
```
