### ISSUE TITLE
select2 plugin and reisizing issue when placeholder is present

### ISSUE THREAD

**Issue by umbreak** [select2/select2#2485]
I just wrote it in [stackoverflow](http://stackoverflow.com/q/24362780/359284) but I think is a bug.

The select area is not re-sized (in some cases) when the placeholder attribute is present. When the attribute is not present, everything works as expected. Note also that when the select with placeholder is selected, the element is then re-sized correctly.
Better [an example](http://jsbin.com/nokuhe/1) to explain the wrong behavior.

**Comment by dickieirwin** [comment]
+1

**Comment by iam4x** [comment]
Same issue without the `placeholder`

**Comment by mikeUtah** [comment]
Experiencing this issue, also seeing it on your examples page: https://select2.github.io/examples.html
go down to "place holders", begin re sizing your browser window, it will start to happen with just that example

**Comment by enumag** [comment]
This bug is present in v4.0 as well.

**Comment by pedrofurtado** [comment]
This kind of bug is much related with the others CSS libraries of application and the structure of HTML where select2 lives. It's hard to make a "global" solution, because it depends a lot of variables (html structuring, which plugins was loaded and what order, css classes, other JS libraries that manipulate DOM). A example of variety of possible solutions is https://github.com/t0m/select2-bootstrap-css/issues/42
