### ISSUE TITLE
<option value="? undefined:undefined ?"></option> when using with ng-model

### ISSUE THREAD

**Issue by burakkilic** [select2/select2#2634]
Hi;

My select element is:

```
<select id="select2_country" class="form-control select2" ng-model="defaultLanguage">
                                    <option value="gb">English</option>
                                    <option value="tr">Türkçe</option>
                                    <option value="se">Svenska</option>
                                </select>
```

And the script is:

```
    <script type="text/javascript">
function format(state) {
    if (!state.id) return state.text; // optgroup
    return "<img class='flag' src='/themes/metronic/assets/global/img/flags/" + state.id.toLowerCase() + ".png'/>&nbsp;&nbsp;" + state.text;
}
$("#select2_country").select2({
    allowClear: true,
    formatResult: format,
    formatSelection: format,
    escapeMarkup: function(m) {
        return m;
    }
});
```

It adds
    <option value="? undefined:undefined ?"></option> 

as a first option in the select element. When I remove ng-model="defaultLanguage", it is ok.

Where is the problem.

**Comment by pathurs** [comment]
For anyone arriving to this issue, the problem is with Angular, ng-model, and <select> tags.

When ng-model does not equal to the value of any <option> tags in the <select>, Angular will add:

`<option value="? type:value ?"></option>`

Where type is the variable's type, and value is the variable's value.

To fix this, I had to add 

`selectCtrl.renderUnknownOption = angular.noop;`

to my select2 directive.
