### ISSUE TITLE
Closing dropdown with ESC key propagates and for example closes a Bootstrap Modal

### ISSUE THREAD

**Issue by cervengoc** [select2/select2#2731]
Here is a fiddle to reproduce the issue with the latest code:
http://jsfiddle.net/9p9fsmfr/1/

When I open the dropdown, and then press ESC key, the dropdown closes, and so does the modal. I think the ESC key should be caught and prevented when the dropdown is open.

**Comment by HRMsimon** [comment]
We've run into a similar problem with our custom modal implementation. You need to close the modal only if:
* The key's an escape key, and
* The event's default has not been prevented

The event is only having its default prevented but propagation isn't being stopped.

**Comment by kevin-brown** [comment]
The ticket where we are tracking this issue for 4.0 is at https://github.com/select2/select2/issues/4218.

**Comment by greendimka** [comment]
How come this issue is closed while it still exists??
#4218 is related to totally different situation.

**Comment by greendimka** [comment]
Probably the problem is here:
https://github.com/twbs/bootstrap/blob/v4-dev/js/src/modal.js, line 298

Instead of
`if (event.which === ESCAPE_KEYCODE)`

use
`if (event.which === ESCAPE_KEYCODE && !event.defaultPrevented)`

**Comment by alexweissman** [comment]
@greendimka if you believe that this is still an issue, please create a working example that demonstrates the problem _in the latest version_ (4.0.6-rc.1).  See our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

This issue is from 2014, so @cervengoc's example is likely highly outdated.  I certainly can't seem to reproduce it in my code at all.

**Comment by G-tlg0226** [comment]
232323232323
