### ISSUE TITLE
Add class select2-container-readonly

### ISSUE THREAD

**Issue by econic** [select2/select2#2745]
When making a select2 readonly, it receives the class `select2-container-disabled`.
Instead, it should get `select2-container-readonly`, since
* it is not disabled
* you should be able to style readonly inputs differently from disabled inputs

The styles should be a combination of normal an disabled, indicating that the input is indeed used, but not editable.

**Comment by kevin-brown** [comment]
As [mentioned in the 4.0 release notes](https://github.com/select2/select2/releases/tag/4.0.0-beta.1), there [is no way to make a `<select>` read-only](http://stackoverflow.com/q/368813/359284) and because [4.0 supports the `<select>` as the primary data source](https://select2.github.io/announcements-4.0.html#hidden-input), I'm going to close this ticket off.
