### ISSUE TITLE
Initialize select2 in readonly state

### ISSUE THREAD

**Issue by econic** [select2/select2#2746]
Currently you have to mark an input as readonly after you initialized it.

``$('#foobar').select2().select2("readonly", true);``

Additionally, you should be able to pass the readonly state as configuration, like so

``$('#foobar').select2({readonly: true});``

**Comment by kevin-brown** [comment]
As [mentioned in the 4.0 release notes](https://github.com/select2/select2/releases/tag/4.0.0-beta.1), there [is no way to make a `<select>` read-only](http://stackoverflow.com/q/368813/359284) and because [4.0 supports the `<select>` as the primary data source](https://select2.github.io/announcements-4.0.html#hidden-input), I'm going to close this ticket off.

**Comment by bomanti** [comment]
When disabled, can't send selected value in form?

**Comment by JackZeled0n** [comment]
Hi, I currently use angular 5 and for making disable I just use

`<ng-select id="someid"  placeholder="Select Something"  [(ngModel)]="somemodel" class="disabled"> 
</ng-select>"`
