### ISSUE TITLE
Decrease specificity of Select2's CSS

### ISSUE THREAD

**Issue by adamjohnson** [select2/select2#2826]
CSS best practices tell us to strive to reduce CSS specificity ([here](http://cssguidelin.es/#specificity), [here](https://github.com/necolas/idiomatic-css/blob/master/README.md#preprocessors-additional-format-considerations), and [here](http://csswizardry.com/2014/07/hacks-for-dealing-with-specificity/)). I absolutely love me some Select2 and use it in several projects; however, I repeatedly find myself fighting with Select2's CSS. Things like:

``` css
.select2-container-multi .select2-choices .select2-search-choice .select2-search-choice-close:hover {}
```

...make things tricky. A better selector would be:

``` css
.select2-search-choice-close:hover {}
```

or

``` css
.select2-search-choice-close--multi:hover {}
```

Would you consider decreasing the specificity of your selectors in an upcoming version? The [BEM naming convention](http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/) might help.

**Comment by banesto** [comment]
That use of BEM is quite a misfire if you ask me. There should be no nesting (with few possible exceptions). Right now it makes a headache to override styling. If I want to just override say 
```
.select2-selection--multiple
```

I absolutely must include *both* parents in selector to make it work for focused container:
```
.select2-container--default.select2-container--focus .select2-selection--multiple
```

which is wrong - it should be only ```select2-container--focus```

**Comment by kevin-brown** [comment]
I'm actually going to re-milestone this to see if there is any place we can improve this.

Well, we all know there is _always room for improvement_, the question is whether or not it is worth it.

It's useful to note that while BEM advises against nesting, they also aim for self-contained blocks. Unfortunately Select2 has to break this with how themes work, because we aren't going to carry theme identifiers around everywhere. Our _base theme_ though shouldn't have too many issues with this, as it can freely operate without theme identifiers.

**Comment by adamjohnson** [comment]
Kevin gets a gold :star2: for being an awesome maintainer and open minded. Great looking out boss. :ok_hand:

**Comment by banesto** [comment]
Yes, making it truly BEM requires a lot of work.. As for theme support, it could be this one exception for nesting.

**Comment by benflodge** [comment]
I have to agree it would be great to to see the specificity of select2 CSS selectors limited to a single level, the use of BEM selector naming should make it easier to remove any high selector specificity. 

Im working on a few long running projects that use select2, and altho select2 is a great plugin we find ourselves fighting with the CSS selectors. 

As a team we found the itcss http://www.creativebloq.com/web-design/manage-large-css-projects-itcss-101517528 methodology helpful in managing our specificity.

**Comment by wroughtec** [comment]
What would be really nice if the class names where configurable ie choose the name of the classes in the when you load similar with what is possible with selectize.js. This would allow the developer to allow the naming conventions too match their own project or use select2 default if needs be.

**Comment by kevin-brown** [comment]
We're planning on reorganizing the CSS in 4.1.0, so this ticket will likely be closed around that time.

We have plans to decrease the specificity for the really obvious cases (I think we have a N=7 case somewhere) but I think the best we will be able to do is N=3 for most cases.

**Comment by comerc** [comment]
Do you know? [Material Design Lite](https://getmdl.io/) support BEM too! It seems that Select2 is best choice with [Flat Design theme](https://github.com/select2/select2/issues/3957). :)

**Comment by lougreenwood** [comment]
Bumping this as I'm now also hitting many issues styling select2 (4.0.3) where the specificity is far too high.

It seems that now you've adopted BEM in 4.x, you should be able to remove most nested selectors, e.g: `.select2-container--default .select2-selection--single`.

I'm currently contemplating scrapping all of select2's css and rolling all of my own custom because of how cumbersome it is to customise with the default CSS.

I highly recommend Harry Roberts' writing at https://csswizardry.com/archive/, here are 2 great articles on specificity:

- https://csswizardry.com/2014/10/the-specificity-graph/
- https://csswizardry.com/2014/07/hacks-for-dealing-with-specificity/
