### ISSUE TITLE
select2 slow load when using class selector

### ISSUE THREAD

**Issue by kicks66** [select2/select2#2904]
I am using select2 for a table that has around 1000 rows in it. Each one of these rows contains the same set of options in a dropdown. The values of each select2 element are set by PHP when the page loads, however I am finding when I apply the select2 function to these elements I get a very long load and slow responsiveness.

    $.getJSON('xxxx', function (datacat) {
        var cattags = [];
        $.each(datacat, function (ind, val) {
            cattags.push(val);
        });
        $('.catv1').select2({
            tags: cattags,
            minimumInputLength: 2
        })
    });

This loads the categories, then applies select2 to the 1000 rows in the table. Is there a better method of doing this, or some way to prevent the slowdown when applied?

**Comment by kevin-brown** [comment]
There isn't an easy way to fix this for 3.5.x because of how tags work, but I'm assuming you are using 4.0 because there was a critical change that happened.

In 4.0, the `tags` option (when data is passed in) works like the `data` option. This will create individual `<option>` elements automatically for the data that is passed in, which means you are creating the same set of options each time, for each Select2 instance. You can skip the pain and create these once, cloning them to the other `<select>` elements, and speed up the process.

```js
$.getJSON('...', function (data) {
  var cattags = [];
  $.each(data, function (ind, val) {
    cattags.push(val);
  });
  
  var $_options = $.map(cattags, function (tag) {
    var $option = $('<option></option>');
    
    $option.val(tag.id);
    $option.text(tag.text);
    
    return $option;
  });
  
  $('.catv1').append($_options);
  
  $('.catv1').select2({
    tags: true,
    minimumInputLength: 2
  })
});
```

You may need to alter this code if you have nested options, or if you have additional data on the tag that needs to be stored.
