### ISSUE TITLE
Select2 v4.0 is not responsive-friendly

### ISSUE THREAD

**Issue by choxnox** [select2/select2#2911]
Current version has a problem because it translates percentage-based width into pixel-based. Basically, if I set the width of the original `select` element to 60% (`style="width: 60%"`), Select2 container will have the width set to 60px (`style="width: 60px"`).

I've just checked the source code for v3.5.2 and it has more advanced width detection than the one found in v4.0.

**Comment by choxnox** [comment]
This fix doesn't work when original `select` element has a class which sets width in percentages. For example, if the `select` element has a class `width-60`, and this class is defined as:
```
.width-60 {
    width: 60%;
}
```

then Select2 element will have the width which again equals to `60px`. I believe `width` option should have it's original `copy` value back because it used to also calculate the width using the `$.css()` function hence fixing this new issue.

**Comment by kevin-brown** [comment]
> I believe width option should have it's original copy value back because it used to also calculate the width using the $.css() function hence fixing this new issue.

The [old `copy` option](https://github.com/select2/select2/blob/da4789c61bdb743905bd71698c9d03a8f901f517/select2.js#L1948-L1957) for the width is the [new `style` option](https://github.com/select2/select2/blob/766d9f05e004863d16ed7b1960fc6d9f8a40c642/src/js/select2/core.js#L137-L153).

> This fix doesn't work when original select element has a class which sets width in percentages

This is most likely because Select2 no longer copies classes to the dropdown and container. At some point I'll make a compatibility module that handles the CSS classes, I'd expect it for either RC1 or Beta 3 (depending on which one happens).

**Comment by akgarg007** [comment]
/* Select2 adds class .select2. You can override what script does using css. Here I'm set select2 to have 100% width, using !important. If I would not do that select2 would have 24px width.

You can further customize other classes that select2 generates using some principle.

 */

.select2 {
    width:100%!important;
}

**Comment by techbisu** [comment]
select2 dropdown list width larger than container issues 

solution -
open select2.js 

search ` t.addClass("select2-container--open"),` this line
add `t.addClass("select2Css"),` after  ` t.addClass("select2-container--open"),`

and add css class in your css file 

```
.select2Css{
         width: fit-content !important;
         }
```


I hope now working fine.
