### ISSUE TITLE
Programmatic init is not resolving widths correctly?

### ISSUE THREAD

**Issue by scoot1585** [select2/select2#2935]
I was having problems in my app with this and thought it was me, but when I went to your example page it was doing the same exact thing.

- go to https://select2.github.io/examples.html#programmatic (i was on chrome 29, didnt test other browsers)
- click the init button 
- the width of the select box and the dropdown is way too small

I was using 4.0.0-beta2 for my project

**Comment by kevin-brown** [comment]
Just bisected this to https://github.com/select2/select2/commit/af1f35176b0000acf26a411a7b360c63631cd377 (which was painful because https://github.com/select2/select2/commit/86b4a5d8e20cf666d7de523df77f1977ba1dad9c [broken] was the middle commit) and I'm in the process of finding out what the major change was that broke it.

**Comment by scoot1585** [comment]
thanks for fixing this so quickly, works great now.
