### ISSUE TITLE
Virtual keyboard, dropdown to top and other issues

### ISSUE THREAD

**Issue by anilastrio** [select2/select2#2936]
Firstly, awesome plugin.

Issues: v4. Branch: select2-ng
1.  Tried using my iphone on your example page but the virtual keyboard opens and closes immediately, which makes it unable to type. This also happens when, onclick on the single select input box.
2. iphone again: Dropdown on the first select on your example page is showing to the top, making the dropdown hidden under the top menu.
3. minimumResultsForSearch is set to "-1" but searchbox still appears.
4. closeOnSelect doesnt seem to work.

Thank you for sharing this plugin with all of us!

**Comment by craigmdennis** [comment]
Also noticing this issue. Doesn't happen the initial appearance is a text field.

**Comment by Inggo-inHomePortal** [comment]
Hi. We are experiencing issue #1 on iOS devices for both Chrome and Safari.

**Comment by adussel** [comment]
We have the same problem ! It would be great to solve it !

**Comment by alexweissman** [comment]
This issue is not useful because it covers too many different problems.  Furthermore, I believe most of these are already covered by other open issues or have already been resolved:

1. #3493
2. This may be something that can be solved with `dropdownParent`
3. `minimumResultsForSearch` should be set to `Infinity`, not `-1`.  See #3055
4. It appears that `closeOnSelect` was dropped in early beta versions of v4, but was reintroduced in https://github.com/select2/select2/commit/c9a8508a39a1ec8b398b988add5f17f2391ff6f2.
