### ISSUE TITLE
4.0.0-beta.2 breaking another jQuery plugin

### ISSUE THREAD

**Issue by flip111** [select2/select2#2939]
```html
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
    <script src="//cdn.jsdelivr.net/jquery.ui.timepicker.addon/1.4.3/jquery-ui-sliderAccess.js"></script>
    <script src="//cdn.jsdelivr.net/jquery.ui.timepicker.addon/1.4.3/jquery-ui-timepicker-addon.min.js"></script>
    <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.0.min.js"><\/script>')</script>
    <script src="{{ app.request_context.baseUrl }}/js/vendor/bootstrap.min.js"></script>
    <script src="{{ app.request_context.baseUrl }}/js/select2.full.min.js"></script>
    <script src="{{ app.request_context.baseUrl }}/js/_form.js"></script>
```

`_form.js`:
```js
$('#form_start').datetimepicker({
  timeFormat: 'HH:mm'
  ,dateFormat: 'dd-mm-yy'
  ,seperator: ' '
});
```

error:
```
_form.js:1 Uncaught TypeError: undefined is not a function
```

Removing `<script src="{{ app.request_context.baseUrl }}/js/select2.full.min.js"></script>` "fixes" the problem.

Also tested with non-minimized version.

Demo
Works: http://jsfiddle.net/dfhfdmof/
Does not work: http://jsfiddle.net/dfhfdmof/1/

**Comment by kevin-brown** [comment]
`select2.full.js` and `select2.full.min.js` include a copy of jQuery. Right now you appear to be loading **three** copies of jQuery, which is never a good thing.

I would recommend using `select2.min.js` unless you have a need for the compatibility modules and extras. If you do, then I would recommend loading Select2 at the top of the page, as a replacement for your existing jQuery files.

**Comment by flip111** [comment]
Ok thanks for support, i couldn't find the difference between full and regular version

**Comment by kevin-brown** [comment]
I'm planning on adding an explanation of the different versions to the main page of the docs before the next release. It basically boils down to:

- Use `select2.amd.js` if you are using an external AMD loader in a browser context
- Use `select2.amd.full.js` if you also need all of the compatibility modules
- Use `select2.js` if you need to use Select2 without any of the fancy add-ons (`select2.min.js` in production)
- Use `select2.full.js` if you need the extra add-ons and the recommended version of jQuery

Part of the issue is that we aren't currently isolating jQuery in the full version, so it's overwriting existing copies and causing conflicts. I do plan on fixing this by not loading it if an existing version exists.
