### ISSUE TITLE
Using select2.amd.js causes "Uncaught Error..."

### ISSUE THREAD

**Issue by mateuszf** [select2/select2#2946]
ver. select2-4.0.0-beta.2

I'm trying to use select2 with requirejs.
I figured out that if I want to use pre-built version I need to use "select2.amd.js". It defines "jquery.select2" module so I changed name of the file to match name of the module and included it in my sources.

It loads, but I'm getting:
Uncaught Error: Module name "jquery.select2" has not been loaded yet for context: _. Use require([])

Version from the "src" subdirectory loads without problems.

**Comment by CTAPbIuMABP** [comment]
+1

**Comment by yanickrochon** [comment]
So... what's the solution for this, as I get this error, too! What the hell is `jQuery.select2`??

I see it is defined a few lines above it is required, but I still get the error. This is using RequireJS@2.1.15.

**Comment by yanickrochon** [comment]
Nevermind, this is RequireJS just being silly and I had a wrong rule in my `require.config`.

**Comment by tagkiller** [comment]
@yanickrochon could you please share your require configuration, as I'm facing the same problem with select2.amd and require.js ?

**Comment by yanickrochon** [comment]
@tagkiller I reverted back to 3.5 for the time being, as there is too much backward issues that I don't have time to resolve at the moment with how our app is wired, etc. If I remember correctly, I was not making `jquery` a dependency and jQuery are not loaded before Select2 in some other module.

**Comment by tagkiller** [comment]
Thanks for the reply, unfortunately I just did the same and reverted back to 3.5.2 as the 4.0.0-beta3 isn't working correctly with requirejs.

**Comment by kevin-brown** [comment]
After thinking about this, I'm considering dropping the AMD build, always including the Almond.js loader, and switching the wrapper to be AMD compatible.

I'll still need to do more testing, and it may end up blocking full AMD support with 4.0.0 until a (near) future release.

**Comment by yanickrochon** [comment]
@kevin-brown isn't RequireJS the most widely used loader out there? Why having two builds only : A RequireJS compatible (`select2.js` with no loader, using `define` and `require` directly) and the Almond.js one (`select2.full.js`providing the minified loader) ? RequireJS minified is 15.3k and suitable for most projects, even mobiles nowadays.

This might not be the right thread for this, but I thought to comment here as it is relevant to the conversation and feel it's not necessary to make a big deal about it... yet :)

**Comment by CTAPbIuMABP** [comment]
require config

```
require.config({
	"shim": {
		"select2": {
			deps: ["jquery"],
			exports: "$.fn.select2"
		}
	},

	"paths": {
		"jquery": "/vendors/jquery/dist/jquery.min",
		"select2": "/vendors/select2/src/js"
	}
});
```

code

```
$.fn.select2.defaults.set("amdLanguageBase", "select2/select2/i18n/");
```

but why should i think about where lang files are?

there is a very simple way to do this in a good way
look at jquery ui. they are wrapping each individual file with 

```
(function( factory ) {
	if ( typeof define === "function" && define.amd ) {

		// AMD. Register as an anonymous module.
		define([
			// dependencies
		], factory );
	} else {

		// Browser globals
		factory( jQuery );
	}
}(function( $ ) { 
// code
});
```

to work from source folder

and wrapping concatenated code with the same wrapper 

so you will end up with two amd versions: requirejs and almond
how ever i still dont understand why do you need modules in concatenated file, because you are loading them all at once

**Comment by yanickrochon** [comment]
:+1:

**Comment by kevin-brown** [comment]
> how ever i still dont understand why do you need modules in concatenated file, because you are loading them all at once

This is what r.js gives us once it builds all of the required modules. If there is a way to somehow avoid all of the `define` calls in the same file, that'd be awesome to know.

Side note: I know jQuery gets around this issue by basically only using r.js for determining dependencies, and otherwise attaches modules to the global scope using the `jQuery` object. I'd personally rather avoid this, as it requires Select2 to be used on a global scope even though it's designed such that `select2/core` can be used without the global scope.

**Comment by CTAPbIuMABP** [comment]
```
If there is a way to somehow avoid all of the define calls in the same file, that'd be awesome to know.
```
actually jquery doesn't remove modules from combined version but if you really want you can use
[onBuildRead](https://github.com/jrburke/r.js/blob/master/build/example.build.js#L544) 

```
// Gruntfile.js
var deps = {
moduleName: "deps"
}
...
onBuildRead: function (moduleName, path, contents) {
        return '(function( factory ) {
    if ( typeof define === "function" && define.amd ) {

        // AMD. Register as an anonymous module.
        define([
            '+deps[moduleName]+'
        ], factory );
    } else {

        // Browser globals
        factory( jQuery );
    }
}(function( $ ) { 
'+contents+'
});';
    },
```

this way you can actually wrap modules for any amd lib

**Comment by glenpike** [comment]
@CTAPbIuMABP, I tried your require config example, but I still get errors about module errors - for "...compat..." has not been loaded yet for context: _. Use require([])

I'm only defining "select2/jquery.select2" as a dependency and not doing the defaults part for this, is that correct?

**Comment by CTAPbIuMABP** [comment]
i guess no, if you have an error)

**Comment by glenpike** [comment]
Okay, thanks, I'll come back to this later.

**Comment by CTAPbIuMABP** [comment]
please tag a new release

**Comment by yanickrochon** [comment]
Just tried to install `4.0.0` again, and I can't figure out how to use this with RequireJS. I see code thrown about this, but nothing seems "official" or documented.

How to load the locale files *after* Select2 with RequireJS?

**Comment by glenpike** [comment]
@yanickrochon with 4.0.0:

This example assumes you want to use the unminified, "simple" Select2 file without the add-ons, if you want a different one, look in the dist folder.

In your require-js config:

```
require.config({
   paths: {
        jquery: 'vendor/jquery/dist/jquery',
        select2: 'vendor/select2/dist/js/select2'
    },
    shim: {
        select2: {
            deps: ['jquery'],
            exports: 'select2'
        }
    }
});
```

Then in an AMD module, import select2 (you'll need jQuery too to initialise / select elements, etc.

```
define([
    'jquery',
    'select2'
], function ($, select2*/) {

    function initSelect2() {
        $('#my-select2').select2();
    }

    $(document).ready(initSelect2);
});

```

**Comment by glenpike** [comment]
@yanickrochon #2899 ?
One way is to make sure your require config points to 'path-to-libs/select2/dist/js' as the path alias for the select2 files rather than the actual JS.  You then need to load the plugin as select2/select2 with define / require.
It looks like the plugin is looking for select2/i18n/[lang].js - 
https://select2.github.io/options.html#amd
The other way would be to set the amdLanguageBase option to your path if you don't use the above.
(You will still have to find a way to define the shim config for select2 - it might be select2/select2 there too, not sure).

**Comment by wmlgl** [comment]
I using r.js to merge my code then I get a bug.

Version: 
Select2 4.0.6-rc.1

File:
i18n/zh-CN.js

Code:
e.define("select2/i18n/zh-CN",[]

Error: 
Uncaught TypeError: Cannot read property 'define' of undefined
