### ISSUE TITLE
Select2 4.0.0 documentation CDN link

### ISSUE THREAD

**Issue by and7ey** [select2/select2#2955]
The doc (https://select2.github.io/) refers to the following CDN releases - 

    <link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/select2.min.css" />
    <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/select2.min.js"></script>

But since there is no 4.0.0 release yet, the links are invalid. The valid links are `.../4.0.0-beta2/...`.
Btw, is it safe to use them? Will not they be deleted once 4.0.0 is released?

**Comment by kevin-brown** [comment]
I didn't realize that cdnjs was hosting the beta files, which is why the links were never updated. I've updated them locally, and during the 4.0.0-beta.3 release the docs should be updated to reflect the correct locations.

> Btw, is it safe to use them? Will not they be deleted once 4.0.0 is released?

More than likely they will not be deleted once 4.0.0 is released. I would make sure to upgrade your versions when it is released though, as you shouldn't be used the beta versions in production.

**Comment by asksnbb** [comment]
find -> [select2 cdn](https://bbbootstrap.com/snippets/select2-option-cdn-31353331) with example
