### ISSUE TITLE
Reposition of popup doesn't work correct (widget remembers last position)

### ISSUE THREAD

**Issue by ova2** [select2/select2#2961]
Steps to reproduce the bug:

1) Go to the https://select2.github.io/examples.html
2) Scroll down, so that any select2 is close to the window bottom.
3) Open select2.
4) Select2 shows the popup with items above because there is no enough place below. This is ok.
5) Close popup.
6) Scroll up now, so that there is enough place for popup.
7) Open select2.
8) Select2 still shows the popup with items above although there is enough place below. This is not ok.

Did you understand what I mean?

**Comment by kevin-brown** [comment]
Select2 will determine the direction to open based on the available space in both directions.

**On the first opening**
The available space above and below the Select2 container is calculated. If there is enough space below the container, the dropdown will be displayed below the container. If there is not enough space below the container, but there is enough space above it, the dropdown will be displayed above the container.

**On each subsequent opening**
If the dropdown is displayed below the container, Select2 will check to ensure that there is still space below the container for the dropdown. If the dropdown is displayed above the container, Select2 will check to ensure that there is still space to display it.

If there is suddenly not enough space to display the dropdown, it will check for available space in the opposite direction. If there is space in the opposite direction, it will reposition itself on the other side, otherwise it will just stay where it is with the limited space.

---

- If we always preferred below the container whenever there was enough room, the dropdown would constantly swap its position when searching. We experimented with it but found it to be too confusion/jarring.
- There does appear to be a jumping bug if the browser resizes or scrolls when calculating the next position that causes the dropdown to immediately close after opening.

**Comment by ova2** [comment]
Ok, you clarified this. Thanks. But anyway, it was not intuitive for me because I think other selects behaves different. But yes, I see the problem when searching - as you said "If we always preferred below the container whenever there was enough room, the dropdown would constantly swap its position when searching."

**Comment by poushy** [comment]
It would be great to make the drop-down/up fixed as an option we should be able to pass

**Comment by brunoDegaspare** [comment]
@poushy I completely agree! I've been trying to implement this on my own for one long week as select2.js has no option to set a fixed dropdown/up. That is a shame as the plugin is excellent.
