### ISSUE TITLE
Combine multiple selections into a single summary (e.g., "3 items selected")

### ISSUE THREAD

**Issue by piernik** [select2/select2#2965]
Is it possible in select2 4.0 that  multiple select will be displayed only in one line (now with too many selected options field has two line - is higher).
Something like in bootstrap select (http://silviomoreto.github.io/bootstrap-select/ example with `<select class="selectpicker" multiple data-selected-text-format="count">`).
Ex if selected 3 option text will be displayed like `2 options selected` instead of showing them.

**Comment by piernik** [comment]
Can anyone give me an anwser pealse?

**Comment by kevin-brown** [comment]
Yes, it is possible. No, it is not possible by default.

You need a custom [`selectionAdapter`](https://select2.github.io/options.html#selectionAdapter) that extends from [`MultipleSelection`](https://github.com/select2/select2/blob/4c563a3d068d66a30bb949fe4abd71f7402dc53e/src/js/select2/selection/multiple.js#L79-L93). You need to override the `update` method to render it the way you are looking for, instead of rendering the individual options.

**Comment by piernik** [comment]
ok - thanks

**Comment by ova2** [comment]
I like how the multiple items can be chosen by bootstrap-select (http://silviomoreto.github.io/bootstrap-select/) Unlike Select2 they can be chosen at once. Select2 close the dropdown after each selection and you have to open it again to select second, third, etc. items. Do you plan to add this behavior to Select2?

**Comment by chaimann** [comment]
@ova2 
you can pass an option `closeOnSelect: false` when initializing select2:

    $('.select').select2({
        ...,
        closeOnSelect: false,
        ...
    });

**Comment by thejahweh** [comment]
Do I see it right that this has no priority and everybody who wants to select more than 5 options has to use another library?

I have some cases with more than 100 selectable options and have to say that this looks amazingly ugly.

**Comment by kevin-brown** [comment]
> Do I see it right that this has no priority

Yes. Like most enhancements that aren't thinly veiled bugs, this ticket does not have any milestone currently attached to it.

> everybody who wants to select more than 5 options has to use another library

Not necessarily. Select2 doesn't prevent anyone from making this work, we just don't have any quick and simple recommendations for adjusting the CSS to make this work. If you have any CSS snippets that make this work (I have a feeling it's going to involve `overflow: auto` and preventing text wrapping), that would definitely help everyone who is looking to do this.

There _are_ cases where all options that are selected must be visible at all times, and it's considerably easier to hide the extra rows than it is to make them appear when they aren't supposed to.

**Comment by fagnercarvalho** [comment]
Hello @kevin-brown,


I'm trying to do what you recommended in [your first comment](https://github.com/select2/select2/issues/2965#issuecomment-72053727) but I failed.

Here is my code so far:


```
$.fn.select2.amd.define('select2/selection/customerMultipleSelection', [
		"select2/selection/multiple",
		'select2/utils'
],
	function (MultipleSelection, Utils) {

		function CustomMultipleSelection($element, options) {
			CustomMultipleSelection.__super__.constructor.call(this, $element, options);
		}

		Utils.Extend(CustomMultipleSelection, MultipleSelection);

		CustomMultipleSelection.prototype.update = function (data) {
			this.clear();

			if (data.length === 0) {
				return;
			}

			var $selections = [];

			for (var d = 0; d < data.length; d++) {
				var selection = data[d];

				var formatted = this.display(selection);
				var $selection = this.selectionContainer();

				$selection.append(formatted);
				$selection.data('data', selection);

				$selections.push($selection);
			}

			this.$selection.find('.select2-selection__rendered').append($selections);
		};

		$('#Selector').select2({
			ajax: {
                                // omitted for brevity
			},
			escapeMarkup: function (markup) { return markup; }, // let our custom formatter work
			minimumInputLength: 1,
			selectionAdapter: CustomMultipleSelection
		});
	}
);
```

The method update was overridden but I'm using the same behavior from MultipleSelection.

I'm using select2 version 4.0.3.

Can you help me?

**Comment by caiolima86** [comment]
Hello guys,

My solution to this problem was:

$('#id').change(function(){
    var total = 0;
    $('#id').next('.select2').find('.select2-selection__choice').not('.etc').each(function(){
        total++;
        if(total > 2){
            $('#id').next('.select2').find('.etc').remove();
            $(this).before('<li class="select2-selection__choice etc" title="...mais '+(total-2)+'">...mais '+(total-2)+'</li>');
            $(this).remove();
        }
    });
});

**Comment by alexweissman** [comment]
@WillemOpperman has this example that seems to work nicely: https://jsfiddle.net/Lkkm2L48/7/

**Comment by Folrond** [comment]
I feel like this really should have an official built in solution for three reasons.

First of all because this feature is requested a lot. I searched stackoverflow and github and found a lot of threads but not a decent solution. The solution linked here https://jsfiddle.net/Lkkm2L48/7/ is not good enough. Unfortunately the dropdown scrollbar jumps back up from the bottom. If you select something top then scroll down and select something bottom the scrollbar jumps back up. 
( Not to mention that i have not found any solutions to this when the data source is ajax. This could be my fault tho.) 

Secondly I feel like this is a major flaw of this plugin.
This is a really great plugin it can handle pretty much every use case, except handling a lot of selections in a nice way a feature that a lot of basic select plugins can do. A lot of ppl work hard on implementing a nice UI design but it all goes to trash when you select 5 things and your ui looks like this:
https://goo.gl/RfJXfp
Another point is that you guys have mentioned before that one of select2's main use case is handling large remote repositories which is all good and until you need to select 10 companies from a 100 an your UI goes crazy (see pic above).

The third point is maybe the most important ok we have some not so good solutions but do we want to implement and maintain these? 
No
1, No because the main point of these plugins are that they are working out of the box, they are well documented, well tested and you can find lots of support articles. Just some things that a custom solution will not have.
2, No because all of the half decent solutions out there requires solid understanding of how this plugin actually works. Which you might have but if the person who implemented this custom solution leaves or his solution fades you have a piece of iffy code which leads back to point 1.
3, No because there is no guarantee that a custom solution will keep working after new versions drop.

I really hope you will add this feature some day. I understand that this task may not be that simple but I really think it would worth the time to have an official solution and make this plugin go from really great to production ready

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused to fix some major UI bugs (that are majority of issues and PR's). But if you open a PR with unit tests, I will be glad to review and approve if everything is ok :+1:

**Comment by devarif** [comment]
This is my solution

```
$('.select2').on('select2:close', function (e) {
    e.preventDefault();
    var total = 0;
    $('.select2').nextAll('.select2:first').find('.select2-selection__choice').not('.etc').each(function(){
        total++;
        $('.select2-selection__rendered').html('<li class="select2-selection__choice etc" title="'+(total)+' Selected">'+(total)+' Selected</li>');
    });
});
```

**Comment by kmafutah** [comment]
> Hello guys,
> 
> My solution to this problem was:
> 
> ```
> $('#id').change(function(){
>     var total = 0;
>     $('#id').nextAll('.select2:first').find('.select2-selection__choice').not('.etc').each(function(){
>         total++;
>         if(total > 2){
>             $('#id').nextAll('.select2:first').find('.etc').remove();
>             $(this).before('<li class="select2-selection__choice etc" title="...mais '+(total-2)+'">...mais '+(total-2)+'</li>');
>             $(this).remove();
>         }
>     });
> });
> ```

this work fine with now i get 

> Unhandled exception at line 2, column 61543 in http://localhost:60669/Assets/lib/select2/js/select2.full.min.js
> 0x800a138f - JavaScript runtime error: Unable to get property 'current' of undefined or null reference
> 
any pointer with help coz the only option left is to swtich and replace hundred lines of js

**Comment by kmafutah** [comment]
> > Hello guys,
> > My solution to this problem was:
> > ```
> > $('#id').change(function(){
> >     var total = 0;
> >     $('#id').nextAll('.select2:first').find('.select2-selection__choice').not('.etc').each(function(){
> >         total++;
> >         if(total > 2){
> >             $('#id').nextAll('.select2:first').find('.etc').remove();
> >             $(this).before('<li class="select2-selection__choice etc" title="...mais '+(total-2)+'">...mais '+(total-2)+'</li>');
> >             $(this).remove();
> >         }
> >     });
> > });
> > ```
> 
> this worked at some point now i get
> 
> > Unhandled exception at line 2, column 61543 in http://localhost:60669/Assets/lib/select2/js/select2.full.min.js
> > 0x800a138f - JavaScript runtime error: Unable to get property 'current' of undefined or null reference
> 
> any pointer with help coz the only option left is to swtich and replace hundred lines of js

https://jsfiddle.net/Lkkm2L48/7/ this works and also changing the from <html class="no-js" lang="en"> to <html class="no-js">

**Comment by TheWitness** [comment]
Opened select2/select2#6462 implementing this as first-class `dropdownSearch` / `selectionSearch` options (adapter composition, no new adapter classes), with tests and docs. Linking here since this issue was part of the history that shaped the design.

**Comment by TheWitness** [comment]
Opened select2/select2#6462 implementing this as first-class `dropdownSearch` / `selectionSearch` options (adapter composition, no new adapter classes), with tests and docs. Linking here since this issue was part of the history that shaped the design.
