### ISSUE TITLE
Tags options not behaving like example

### ISSUE THREAD

**Issue by BenRacicot** [select2/select2#2986]
Hello, I have instantiated the CDN deps, CSS and JS however my code on a very simple select tag is not behaving like the example: 

```js
$("#sub-tags").select2({
	tags: true
});
```

I get a select type drop down with a text area within it. But not tag-like functionality. What am I missing?

**Comment by kevin-brown** [comment]
`tags` allows you to dynamically create new options that can be selected.

http://jsfiddle.net/b60umsgq/

I can't say much for the problem you are running into without a jsbin that reproduces the issue.

**Comment by BenRacicot** [comment]
Hey @kevin-brown thanks for replying. I'm after what's on the example page for tags, like that new-school comma separate stuff:

![image](https://cloud.githubusercontent.com/assets/1815385/5951280/134d1d76-a733-11e4-83ff-6c3be9535716.png)

**Comment by kevin-brown** [comment]
You need to set the `multiple="multiple` in order to allow multiple values to be selected.

https://select2.github.io/examples.html#multiple

I've updated your jsfiddle with the change.

http://jsfiddle.net/f7wLs1hL/4/

Keep in mind that you can always look at the source code of [the examples page](https://select2.github.io/examples.html), which is included in the repository under the `docs` directory. [Here's the tokenizer example source.](https://github.com/select2/select2/blob/36cfc26cc1886b5cbbd13e5a95adba19e36c19d8/docs/examples.html#L588-L592)

**Comment by BenRacicot** [comment]
Excellent answer! thank you very much for your time on this one. Works as I'd hoped.
