### ISSUE TITLE
Input not focused after selecting a tag

### ISSUE THREAD

**Issue by Soullivaneuh** [select2/select2#2995]
When you select a tag proposition with a click or enter, the input is not focused anymore.

The user have to select again the input to continue the tagging. Not really optimized.

Tell me if you need more details.

Thanks.

**Comment by JasperTey** [comment]
This is something I've noticed as well. I thought it was something on my end, but the examples page also has this behaviour. Looks like a bug?

**Comment by kevin-brown** [comment]
Seems to be a bug for all multiple-select inputs with search boxes.

**Comment by ova2** [comment]
Yes, this is always true for multiple selects. The input field is not focused after item's selection.

**Comment by Soullivaneuh** [comment]
Hi @kevin-brown, thanks for the fix, is it on a new beta version? Which one please?

Thanks.

**Comment by ova2** [comment]
Saidly, but the fix is only working when choosing not yet selected items. When you select already selected items (by arrow up / down keys), they will be removed from the input. This is ok. But the focus is also lost. Even worst: navigation in the dropdown by arrow up / down keys leads to the window scrolling.

Please reopen this issue.

**Comment by ova2** [comment]
Another bug (new bug?): If you press the enter key (focus on the input field), the dropdown is shown. This is ok. But the last selected item gets removed from the input field!

**Comment by kevin-brown** [comment]
Reopening this while I wait to do some more keyboard testing.

**Comment by JasperTey** [comment]
Tabbing to the select2 field doesn't trigger focus (visually, anyway). As @ova2 mentions above, if I tab to the select2 field and hit the Enter key, the dropdown is shown. Otherwise, it doesn't visually look like the field is in focus.

In version 3.5.*, tabbing to the select2 field triggered the blinking cursor and allowed typing, or use of the arrow keys. That worked quite well.
