### ISSUE TITLE
Is there a fullscreen option for the "dropdown" popup?

### ISSUE THREAD

**Issue by trusktr** [select2/select2#3015]
This would be good for mobile, so that the dropdown goes to the full screen of the page, with optional padding around the edges so you can see the underlying content (e.g. 20px around the screen edges).

**Comment by trusktr** [comment]
I just tested in the inspector, and basically I can add `position: fixed; top:0px; left:0px; width:100%; height:100%` to the popup, and it'll be full screen. Pascing around the edges could easily be added. If you could make this an option, that'd be great.

**Comment by kevin-brown** [comment]
This is something that we talked about doing for 4.0 for mobile devices specifically, but we ran into design and time problems that prevented it from being done.

I would like to alter the design for mobile devices though to improve touch region and make it easier to use.

**Comment by sahanDissanayake** [comment]
:+1:  would be awesome to have this enhancement

**Comment by cervengoc** [comment]
I use 3.x version. This is something I needed too. I had troubles with the fixed positioning of the dropdown because the UI is quite different for single and multi select boxes, and because mobile browsers have so much issues in general, especially with fixed positioning.

I finally tweaked select2 quite much, and reached that instead of dropping down on mobile, it puts the dropdown and related controls (searchbox, etc.) in a Bootstrap Modal. It looks very good and is really usable on mobile phones too. 

Sorry but currently I don't have the time to post any code about this solution, I just wanted to share one possible solution.

**Comment by cervengoc** [comment]
Just for a quick reference, I list a few things I've done related to the latter post. These steps were required (at least for me) to implement the "modal mode" of select2.

- added an option to allow disabling closing on escape
- added an option to allow disabling of using the mask
- added an option to allow disabling making use of jquery.mousewheel
- added an option to allow disabling the complete dropdown positioning and sizing logic
- added an option to allow disabling auto-focusing of the search input after selecting an item when in multiple mode (because in the modal mode the selected items and search input is at the top of the modal so it was always bringing the user to the top)
- tweaked the behaviour to update results after removing an item while the dropdown is open (so that the removed item "goes back" to the selectables list

- when opening select2, I open a bs modal and append the dropdown to it in single selection mode, and the whole container in multi selection mode (in the latter case I add a "dummy" input to the original place of the container which is removed when modal is closed).
- when select2 is closing, I close the modal too
- when modal is closing I close select2 too

These are just the most important ideas, not complete list or guide. Everybody should take it only as kind of a "for your interest" stuff.

**Comment by JacobEvelyn** [comment]
It would probably have to be modified to work well for mobile, but I just wrote a plugin ([maximize-select2-height](https://github.com/panorama-ed/maximize-select2-height)) that at least expands the height of the dropdown to be larger when there's room for it, so I'm including a link here in case any of that code is useful for this.

**Comment by georgeemr** [comment]
Still no solution to this? I would like this to be mobile friendly.

**Comment by karolisgit** [comment]
Can't believe there is no full screen overlay module added yet for mobiles. It's 2018 already. 🥇 👍

**Comment by cdcharlebois** [comment]
we have been working to implement this also, with the following CSS:
```css
select2-dropdown{
   height: 100vh !important;
   width: 100vw !important;
   position:fixed;
   top:0;
   left:0
}
.select2-results__options {
   max-height: none !important;
}
```
But our selection pop-up is being closed immediately after it's opened. It's like the touchevent that opens the pop-up is simultaneously triggering a select event at the same X/Y coordinate on the screen
🤔

**Comment by JacobEvelyn** [comment]
@cdcharlebois have you tried the [maximize-select2-height](https://github.com/panorama-ed/maximize-select2-height) plugin?

**Comment by cdcharlebois** [comment]
I just tried the plugin and it doesn't seem to give me any more functionality than adding my CSS (above) did. In fact, the CSS makes it look more like a mobile typeahead

**Comment by timavaza** [comment]
I agree, we really need a full-screen-on-mobile feature in Select2.. 
(see the UI in whatsapp when you click the newchat icon, and up pops a full-screen searchable select for the person you want to message)
There's almost no feature that would help the UI more for our product than this enhancement to select2.

**Comment by ekremsen** [comment]
I solved it this way,
**CSS**
`@media only screen and (max-width: 600px) {
	.select2-container--open .select2-dropdown--below{
		position: fixed !important;
		top: 71px !important;
		width: 100% !important;
		height: calc(100vh - 71px) !important;
	}
	.select2-results{
		visibility:hidden;
	}
}`
**JS**
`$(".select2").on('select2:opening',function(){
		setTimeout(function(){
			$(".select2-results").css("visibility","visible");
		}, 100);
	});`
because the object was opened and selected immediately. I slowed down a bit ... :)
