### ISSUE TITLE
Is tagging via <input> elements no longer supported?

### ISSUE THREAD

**Issue by philipwalton** [select2/select2#3022]
Here's an example of this not working. It used to work in 3.5.2:
http://jsbin.com/yonavaqiva/2/edit?html,output

Is this no longer supported or is this just something that needs to be worked out prior to the 4.0.0 release? FWIW, my use-case actually requires a comma-separated input rather than a multiselect.

**Comment by kevin-brown** [comment]
Select2 4.0 does not support hidden input tags anymore, as we have decided to use the native `<select>` inputs for all options.

https://select2.github.io/announcements-4.0.html#hidden-input

You _can_ add support back in through the use of a [custom data adapter](https://select2.github.io/options.html#dataAdapter), I would recommend looking at the standard [one for `<select>` tags](https://github.com/select2/select2/blob/a08179f481b4fd693849d9ebebe449fe0d9578b3/src/js/select2/data/select.js) as a base to work from. If you are able to get it working, either as a decorator or new adapter, we are interested in incorporating it into the core through a pull request.

**Comment by philipwalton** [comment]
I wasn't asking about a hidden input tag, I was asking about regular input tag.

Select2 is supposed to be progressive enhancement, right? So if for whatever reason select2 fails to load, the "regular" form controls are supposed to just work fine.

In my case, I actually *do* want a regular `<input>` field. I *don't* want a `<select multiple>` field. The reason is the value of the input is actually [supposed to be a comma-separated string](https://developers.google.com/analytics/devguides/reporting/core/v3/reference#metrics) and not an array (which is what you get with `<select multiple>`).

Are you saying select2 no longer supports `<input>` fields at all? If so I think that's a shame as this is a common use-case. It'd be a pain to require two separate plugins (with varying UIs) for very similar tasks.

**Comment by kevin-brown** [comment]
> I wasn't asking about a hidden input tag, I was asking about regular input tag.

They're the same thing to Select2 (that is, not an `<select>`). Select2 previously worked on a text box because both `input[type=text]` and `input[type=hidden]` both have the same properties.

> Are you saying select2 no longer supports <input> fields at all?

Not by default. This required extensive branching in the code to support both previously. Just to reinforce what I said previously

> You _can_ add support back in through the use of a [custom data adapter](https://select2.github.io/options.html#dataAdapter), I would recommend looking at the standard [one for `<select>` tags](https://github.com/select2/select2/blob/a08179f481b4fd693849d9ebebe449fe0d9578b3/src/js/select2/data/select.js) as a base to work from. If you are able to get it working, either as a decorator or new adapter, we are interested in incorporating it into the core through a pull request.

If you extended directly from the base `<select>` adapter, you would specifically need to override...

- `current` - used like `initSelection` to convert the `value` to a set of data objects
- `select`- called when a result is selected, you just need to append the `id` to the `value` attribute of the input
- `unselect` - called when a result is unselected, you need to remove the `id` from the `value` attribute
- `query` - similar to the old `query` method, used to get the results list

**Comment by kevin-brown** [comment]
I'm actually going to tentatively reopen this for 4.0 while I coordinate with the Drupal team on a decent middle ground.

**Comment by wimleers** [comment]
Thanks for your comment on the Drupal issue! That helped us find this GitHub issue. (For those wondering, @kevin-brown's exact comment there can be found here: https://www.drupal.org/node/2346973#comment-9624861.)

I've replied there with our perspective/details, and I hope we can indeed find a decent middle ground. We completely understand your reasons for removing `input[type=hidden]` support, but we also would like to see `input[type=text]` support restored.

---

For the sake of simplifying/streamlining the conversation, I'm transplanting my comment there to this issue too:

<blockquote>
<p>That's awesome news! Thank you!</p>

Basically, all there is to know is this:
<ol>
  <li>Drupal has supported "free tagging" (also known as folksonomies) for … 10 years or so. You can type any tag you want, and type a comma to indicate a next one.</li>
  <li>To help users find/select existing tags, there is an autocomplete, which takes the space-trimmed string after the last comma — if any — and asks the server for autocomplete matches. (It's never been quite as awesome as Select 2 though :)) i.e. <code>foo, bar, baz</code> -> "baz" is being autocompleted.</li>
  <li>To type tags containing commas, we wrap them in double quotes. i.e. <code>Some Person, "Leers, Wim", Another Person</code> has 3 tags: "Some Person", "Leers, Wim" and "Another Person".
(This behavior would probably need to be implemented on the Drupal side, which is exactly what @amateescu did in <a href="#comment-9513997">#66</a>, until @nod_ remarked in <a href="#comment-9518139">#69</a> that  Select2 version 4 was about to be released, and this issue kind of got stuck on what to do now that Select2 no longer natively supports <code>input[type=text]</code>. In other words: you probably wouldn't even have to care, as long as we can still make it work just like we did for Select2 version 3.)</li>
  <li>Most importantly to you: what is described above, including the examples, are <em>exactly</em> what is sent to the server (commas, quotes, spaces and all). Basically, our UI has always been <code>input[type=text]</code> with some UI additions for autocompletion that helped the user get data in there in <code>input[type=]text]</code> faster and more easily — hence degrading "gracefully" to a very unhelpful, autocompleteless, mindblowingly simple UI: the plain <code>input[type=text]</code>.</li>
</ol>
</blockquote>

**Comment by theodoreb** [comment]
One way to solve this issue without major rearchitecturing would be to replace inputs by selects and get an event/callback in there to update the input value based on serialization rules. I'm pretty sure that's how we'd have done on it drupal side. 

That would mean that parsing and serializing values get back in scope for select2 though.

**Comment by kevin-brown** [comment]
The biggest challenge that I've been facing with this is what should be done when the `value` of the `<input />` is updated.

Right now we can easily re-pull the text and value from the `<option>` tags and convert those to data objects. In the past we had a `initSelection` method that handled this, but it was specific to `<input />` and poorly named.

I'm going to create a pull request locally (shortly) with the backwards compatibility adapters and what I've currently got.

**Comment by wimleers** [comment]
Is there anything else you need from the Drupal side?

**Comment by kevin-brown** [comment]
@wimleers I'm planning on rebasing the PR and merging it this weekend, along with doing the rc.1 release. There isn't anything else left for this on the Drupal side until it goes into further testing.

**Comment by aajahid** [comment]
Seems like this issue isn't fixed! 

Here is a jsfiddle that shows same code applied on both `<input />` and `<select>` to have get `tags` feature. 
The `<select>` tag works but `<input />` doesn't!

Requesting to reopen the issue.
Thanks.

**Comment by narbsy** [comment]
I investigated this for a bit since my use case was to use an `input[type='text']` element and select2  to provide some autocomplete support.

The `InputData` wrapper prevents this use case from correctly functioning, and there does not seem to be a good way to turn it off by default.

Locally, I tested this by commenting out the decoration of the `dataAdapter` with an `InputData` for `input` elements.

So, definitely think there's something incorrect with the compat layer here.

It would be nice to make it optional so that using a custom `dataAdapter` can override the compat behavior.

**Comment by lingceng** [comment]
I wrote a gist to **make select2 tags work with text input**.
As @theodoreb said:
> One way to solve this issue without major rearchitecturing would be to replace inputs by selects  and **get an event/callback in there to update the input value** based on serialization rules. 

```javascript
function select2InputTags(queryStr) {
  var $input = $(queryStr)

  var $select = $('<select class="'+ $input.attr('class') + '" multiple="multiple"><select>')
  if ($input.val() != "") {
    $input.val().split(',').forEach(function(item) {
      $select.append('<option value="' + item + '" selected="selected">' + item + '</option>')
    });
  }
  $select.insertAfter($input)
  $input.hide()

  $select.change(function() {
    $input.val($select.val().join(","));
  });

  return $select;
}
```

https://gist.github.com/lingceng/d1cd5ca5db9a777b31487769242c422f.js

**See the demo here:** https://jsfiddle.net/lingceng/h5baz3bo/13/
It's simple to use:
```javascript
select2InputTags('#select2Input').select2({
       tags: true, // Doesn't work either
       // tags:["red", "green", "blue"], // Doesn't work either
       multiple: true,
       tokenSeparators: [",", " "]
});
```

I'd like to make it a repo if you like it.

**Comment by konstruktur** [comment]
thanks @lingceng for this helpful gist! 

I just noticed some troubles with reloading fields with select2InputTags().  I work with a webquestionnaire tool (limesurvey) and use select2 4.0.5 to augment the textfields with multiselect and tagging. I just noticed, that when I fill in a field (select2 with select2InputTags), change page (one question per page) and come back the values (saved in the text fields) are reloaded, but it shows only the id, not the text.

So if I have 4 Options and loading them from an array:

``` javascript
var qID = {QID};  /* identify question in the survey */
var wordList1=[ { id: 1, text: 'Option 1' }, { id: 2, text: 'Option 2' }, { id: 3, text: 'Option 3' }, { id: 4, text: 'Option 4' } ];  /* create options for the select2 field */

$('#question'+qID+' input[type="text"]').each(function(i) {
	select2InputTags($(this)).select2({ 
		data: wordList1, width: '95%', 
		minimumResultsForSearch: -1, 
		tags: true, 
		tokenSeparators: [','], 
		placeholder: "...", 
		multiple: true, 
		debug: true
		}); 
	});
```

1)  I choose Option 1, Option 2 and type some text 'asdfg'. 
2)  I go forth to the next page and come back 
3a) the preloaded content for the text field is '1','2','asdfg' - so it only shows the ids, not the text. 
3b) the dropdown text for options '1' and '2' is also replaced by the id, e.g. there is no 'Option 1'  in the dropdown, but only '1' . (In this case it's '1', '2', 'asdfg', 'Option 3', 'Option 4')

I created a gist at https://jsfiddle.net/konstruktur/2oay3r9x/15/, but it can't show this pagechange and I unfortunately can't give a reproducible example, since I cannot give access to my installation of the survey software, but maybe someone, maybe @lingceng knows how to get the text instead of the ids and can adapt this great gist? Thanks a lot for your time!
