### ISSUE TITLE
Select2 4.0 - decorator doesn't apply while using custom dataAdater

### ISSUE THREAD

**Issue by prophe05** [select2/select2#3035]
When I define custom dataAdapter and minimumInputLength option (for example), decorator doesn't call.

**Comment by kevin-brown** [comment]
To prevent double-decorating adapters, Select2 will not automatically apply decorators when a custom adapter is used. On [the options page](https://select2.github.io/options.html), we include all of the decorators for the documented functions, labelled "Decorator" with the matching "Adapter" as well, so you can know what decorators to use in order to get the option working.

The `minimumInputLength` option is not yet documented, but it wraps the `DataAdapter` using the `MinimumInputLength` decorator, available at `select2/data/minimumInputLength`.

**Comment by bmathews** [comment]
Based on your answer above @kevin-brown, if we want to globally use a custom adapter, e.g., extend ResultsList to show a checkbox per #411, we'd have to manually come up with some system to manage all those decorator permutations, similar to how defaults.js does it with all the if statements based on options?
