### ISSUE TITLE
Behavior for working with keys

### ISSUE THREAD

**Issue by ova2** [select2/select2#3036]
Decided to create a separate issue. I have mentioned here https://github.com/select2/select2/issues/3031 the Twitter's Typeahead and psedocode. At the moment, when the focus is set on the input field and I press Enter key, the Dropdown gets open. But normally, the Enter key should submit the form. I think we can use the following pseudocode for Enter:

**Enter is Keyed**
```
IF dropdown menu cursor is on suggestion THEN
  close dropdown menu
  display suggestion in the input field
  prevent default browser action e.g. form submit
ENDIF
```

And for Up Arrow:

**Up Arrow is Keyed**
```
IF dropdown menu is open THEN
  move dropdown menu cursor up 1 suggestion
ELSE
  request suggestions for current query

  IF suggestions are available THEN
    render suggestions in dropdown menu
    open dropdown menu 
  ENDIF
ENDIF
```

similar for DownArrow.

**Comment by kevin-brown** [comment]
> But normally, the Enter key should submit the form.

This might be true for `<input type="text" />`, but I don't believe it is true for `<select>`.

The behaviour for the enter key is currently as follows, which matches what has been observed across a few browsers (Chrome, Firefox)

```
if "dropdown" is not  "open":
  open dropdown
else:
  select currently highlighted option
  close dropdown
```

The up/down arrow behaviour is not implemented when the dropdown is closed. _You can_ implement it on your own by catching the `keyup` events and checking if the dropdown is open.

**Comment by ova2** [comment]
Yes, it is not true for single select, but for **multiple** select you have an input field behind. User can input somethng into a multiple select. In my opinion, the behavior for multi select should be like DropDown example here http://www.primefaces.org/showcase/ui/input/autoComplete.xhtml

1. Click on arrow icon --> DrowDown gets open (like single selection).
2. Input something into the input field, suggestions are shown in the DropDown.
3. Press enter key when focus on the input field, the form gets submitted (default button is clicked automatically like behavior in other inputs).

By the way, can we display an arrow icon via configuration's option?

**Comment by ova2** [comment]
Do we have ```openOnEnter``` option in the Select 4.x? Select 3.5.x had it http://select2.github.io/select2/#documentation

**Comment by kevin-brown** [comment]
> Do we have openOnEnter option in the Select 4.x?

Nope, but feel free to make a pull request to add it (along with documentation).

**Comment by szgeri** [comment]
Select2's autocomplete feature stops working when you try to add a 2nd tag with keyboard only.

At the "Multiple select boxes" example, Type "Haw", press Enter. "Hawaii" tag added.
Now type "ala" for Alaska. You would expect autocomplete to work when entering the 2nd tag name. No autocomplete, no dropdown. That is the main bug (or missing feature) I found but I kept going.

Other bugs can be found:
If you press enter at this point, the dropdown appears with "Hawaii" selected. If you press Enter again, the Hawaii tag you entered before disappears and only the "ala" text will remain.

Press Enter again on the selected "Hawaii" option, "Alaska" will be selected but instead of adding "Alaska" as a new tag, select2 goes into a state when it stops caring about the keyboard. It looses focus.

**Comment by rubal404** [comment]
I am using select2 4.0.0 version. When using keyboard navigation on multi select dropdown, I am facing an issue in which able to select an option using enter key or ctrl + space. But once an option is selected, select dropdown loses focus and I have to tab again to bring focus on it for selecting other options.
