### ISSUE TITLE
Tagging support, deleting tags with multiple press of enter key

### ISSUE THREAD

**Issue by peterholmes** [select2/select2#3044]
Hello,

Found what I think is a bug with adding tags.

When adding new tags, if you consistently press the enter key, each tag is removed one after another. This did not happen with version 3.5.2, and seems to be a new bug. Unfortunately this results in anyone that enters tags to delete them quite easily once they have added the tag they require.

Has anyone else come across this problem?
Cheers!

**Comment by kevin-brown** [comment]
The issue here is that hitting enter will open the dropdown. This will automatically focus the first selected item, and hitting enter again will remove it. So it just ends up being a vicious cycle that means you can quickly remove a bunch of items by just holding enter.

For now I'm going to merge this into https://github.com/select2/select2/issues/3036.
