### ISSUE TITLE
tokenisation and ajax can not work well together on select 2 version 4

### ISSUE THREAD

**Issue by charliezhangqian** [select2/select2#3076]
When I include tags, tokenSeperators and ajax in Select 2 4.0, tokenSeperators can not work as well as when there is no ajax. When I only input space (the delimiter), it will take an empty string "" as a token and fail to handle duplicated tag issue.

Does anyone face the same problem on Select 2 version 4.0?

**Comment by charliezhangqian** [comment]
No solution to this issue?

**Comment by kevin-brown** [comment]
I was finally able to _maybe_ reproduce this issue. It would be best if you could create a jsbin that reproduces the issue you are seeing though, just so we are on the same page.

> it will take an empty string "" as a token

I'm guessing you mean the blank tag that appears at the top of the list? This appears to be because we are not stripping out the whitespace in our `createTag` method.

> fail to handle duplicated tag issue.

I'm not sure what you mean by this.

**Comment by charliezhangqian** [comment]
After I type a tag followed by a delimiter and then type a same tag again followed by a delimiter, I will see two identical tags in the bar but I am not able to remove any of them in the bar because they are actually not in the tag list (the value I get from select 2). It seems that the second tag can remove the first tag because I input the same tag twice. It is fine. The problem is that I can see them in the bar.

This problem only happens when I include ajax. Could you please give me an example of using both tag and ajax on Select 2 4.0? Thank you.
