### ISSUE TITLE
Select2 - Remote Data Loading Feature 

### ISSUE THREAD

**Issue by h3christophe** [select2/select2#3080]
When a result is selected from the search dropdown menu the value is added to the select DOM Element 
_unfortunately_ the actual text is not added
```
<select name="user_id" >
    <option value="1"></option>
</select>
```
it would be better if the text were added as well
```
<select name="user_id" >
    <option value="1">Username</option>
</select> 
``````
![screen shot 2015-02-26 at 4 07 25 pm](https://cloud.githubusercontent.com/assets/2474505/6404873/a43d7f4c-bdd1-11e4-9b43-a96da4b89a11.png)

Alternatively for multiple select element, select2 should have a function to retrieve the data of the selected options, so it can dynamically used somewhere else in the page 
This should work with Remotely loaded results

**Comment by kevin-brown** [comment]
> When a result is selected from the search dropdown menu the value is added to the select DOM Element _unfortunately_ the actual text is not added

Due to a difference in how `textContent` and `innerText` work in Chrome, setting `undefined` as the value will display differently.  When `textContent = undefined`, the `<option>` will appear blank but when `innerText = undefined` then it will appear with `undefined` (because it was converted to a string). Keep in mind that it is only undefined if you do not include the `text` key in your response, [or you are not mapping it](https://select2.github.io/announcements-4.0.html#changed-id).

When it is set to anything else, like it normally would be, the content is filled in fine for both `textContent` and `innerText`.

> Alternatively for multiple select element, select2 should have a function to retrieve the data of the selected options, so it can dynamically used somewhere else in the page

You can now (in rc.1) do this with `.select2('data')`, which will get you the internal data objects.
