### ISSUE TITLE
Disable options with dataAdapter

### ISSUE THREAD

**Issue by tcs-apeters** [select2/select2#3135]
It is not possible to disable the `<option> `when you use the dataAdapter.

I also tried to add the disabled `<option>` before calling `select2()`, but with no luck.

**Comment by kevin-brown** [comment]
Select2 determines if options are disabled through the `disabled` property on the data object, make sure you are passing it back if you are using a custom query method. This happens in [the `item` method](https://github.com/select2/select2/blob/e3d7cd2d6952fc4412e953f2b749ede316e70dc5/src/js/select2/data/select.js#L206-L212) of the `SelectAdapter` by default.

If you have a specific issue, we are going to need to see a jsbin in order to help debug any issues.
