### ISSUE TITLE
Highlight in multiple

### ISSUE THREAD

**Issue by Knoxvillekm** [select2/select2#3141]
Can you fix highlight. When select, "select2-results__option--highlighted" class moved to first selected in list, but must left on last selected.

Use "closeOnSelect: false" or select with Ctrl. Select2 4.0.0 rc1

**Comment by kevin-brown** [comment]
Right now we don't do this because Select2 resets the highlight when the dropdown is supposed to close. We can't determine where the mouse is because the user typically does not move their mouse quick enough for us to detect the `mouseover` event, and as far as I know it's not possible to determine the mouse position without any mouse events.

I am going to look into not resetting the highlight when the close event is cancelled.

**Comment by Knoxvillekm** [comment]
How about in onSelect event remember option and if need open again highlight it?

**Comment by Sciscitator** [comment]
Is there any solution for this? Unfortunately this issue makes disabling "closeOnSelect" for multi selects almost useless because it's very confusing when the Highlighting suddenly jumps to the top.
