### ISSUE TITLE
Remove empty tag

### ISSUE THREAD

**Issue by Knoxvillekm** [select2/select2#3146]
Select2 4.0.0 rc1

After createTag and clear input remove empty option.
http://jsfiddle.net/Knoxvillekm/jve3svq4/2/
(type something and clear)

And how about option to make new tag last in list? Like createSearchChoicePosition: 'bottom' in 3.5.2

**Comment by kevin-brown** [comment]
The issue here is that you are creating a new option and inserting it into the DOM. Select2 can't tell if this is supposed to be a tag or a brand new option that can always be chosen, so it plays it safe and treats it like any other option.

If you set [the `data-select2-tag` attribute](https://github.com/select2/select2/blob/a06379ce8d552b73409439ad73a1eaf809495937/src/js/select2/data/tags.js#L72) on the option, it will be treated like any other tag. This is the attribute that Select2 uses internally for marking options as tags, and they will be automatically removed after they are deselected.

> And how about option to make new tag last in list? Like createSearchChoicePosition: 'bottom' in 3.5.2

The data adapter has an `insertTag` method for this, but it hasn't made its way to an option yet. Feel free to create a pull request that does this though.
