### ISSUE TITLE
Minified versions throws error

### ISSUE THREAD

**Issue by Karmalakas** [select2/select2#3149]
4.0.0-rc.1 minified files versions shows error in console: `Uncaught SyntaxError: Unexpected string`

**Comment by kevin-brown** [comment]
If you can reproduce this in a jsbin that'd be great.

**Comment by Karmalakas** [comment]
I couldn't reproduce error adding by Select2 in JSBin from `//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0-rc.1/js/select2.min.js`, so I tried saving it on top of downloaded verios and error is gone. So it appears error is with the downloaded files from https://github.com/select2/select2/archive/4.0.0-rc.1.zip

**Comment by notacouch** [comment]
I get the same exact error, too. I was grabbing the file from dist/ last night and today.

A quick diff against the the cdn link above shows they are not the same.

**Comment by kevin-brown** [comment]
I still can't reproduce this issue.

> So it appears error is with the downloaded files from https://github.com/select2/select2/archive/4.0.0-rc.1.zip

I thought this had some potential, so I just did a diff against the CDN version and the `dist` version provided in that archive. They appear to be identical though, which makes sense because cdnjs pulls from the tag.

> A quick diff against the the cdn link above shows they are not the same.

The current master's `dist` files definitely differ from cdnjs's `dist` files, because one is newer than the other.

**Comment by notacouch** [comment]
I think I had only tried Google Chrome. I will try again tomorrow.

**Comment by notacouch** [comment]
Okay `4.0.0-rc.2` seems to have fixed it, both the archive and `dist` (which at the moment are exactly the same).

Thanks!
