### ISSUE TITLE
Version Select2 4.0.0 setting a title of selects

### ISSUE THREAD

**Issue by afattahi54** [select2/select2#3158]
I have updated to Select2 4.0.0-rc.2 and find that it will set the title of select element. 
Please see http://jsfiddle.net/h0mqofwq/1/
How can we disable it ?!

**Comment by Knoxvillekm** [comment]
set options: placeholder and allowClear
http://jsfiddle.net/Knoxvillekm/h0mqofwq/2/

Why when I set allowClear: true, I have selected option after init?

**Comment by afattahi54** [comment]
@Knoxvillekm you are asking something else, please ask a new question with new topic

**Comment by Hatamikhah** [comment]
yes, I want to disable this feature in Select2 4.0.0-rc.2 for specific reasons. Could you help me in this issue?

**Comment by afattahi54** [comment]
Manually removed by:

    $(".select2-selection__rendered").attr("title","");

**Comment by jwynveen** [comment]
This issue pertains to v3.5.2 as well and affects the use of select2 with jquery validate. Because select2 adds the title attribute, jquery validation uses that title as the validation message. It should be an option to disable this feature of automatically adding title attributes for the cases like this where it conflicts with other plugins.

Fiddle showing the issue. Click submit on form to see validation messages. https://jsfiddle.net/jwynveen/rn2vgnsj/2/

**Comment by Daijobou** [comment]
Maybe that helps? https://stackoverflow.com/a/46327202

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused now to fix UI bugs. But if you open a PR with unit tests, I will be glad to review and approve if everything is ok.
