### ISSUE TITLE
How much data do

### ISSUE THREAD

**Issue by ghostry** [select2/select2#3159]
I have a select contains 5000 data. Click after going two seconds to display the list.

**Comment by kevin-brown** [comment]
Ignoring the fact that large data sets work best with remote (AJAX) data...

Can you create a jsbin that we can test with? Also, what version are you using?

**Comment by ghostry** [comment]
http://jsbin.com/difoce/1/edit?html,css,js,output

jquery-2.0.3,Bootstrap v3.0.3,Select2 4.0.0-rc.2

**Comment by kevin-brown** [comment]
There are two parts to this that is making it slow.

1. The `query` call, that determines the in-memory list of results.
2. The `option` call, that converts a data object into an option in the results.

On my system, I got 250ms for the first `query` call, dropping to around 20ms for any afterwards. This is because we heavily cache the data objects after the first call to avoid speed issues. I also got around 300ms for the `option` call on all runs. The main performance problems here come from creating 5,000 DOM elements in memory, which we've optimized about as much as we possibly can.

You can alleviate some of these problems by requiring searching, so a more limited data set is displayed. You would do this using `minimumInputLength`, even setting it to `1` considerably reduces the time.

The other option, and probably something to look into, is turning this into a remote AJAX call instead of doing all the searching locally.
