### ISSUE TITLE
Adding new tag with tags:true does not select that option

### ISSUE THREAD

**Issue by catalinux** [select2/select2#3172]
When having a tags:true like this: https://select2.github.io/examples.html and you add a new option that is not select, so when posting values that new option is not selected.  Should not be this the default behavior? Is there any config option to do that?

Monkey patch is the only solution?

**Comment by cadecannon** [comment]
I also see this issue to the point where tags are unusable in their current state.

Here's a jsfiddle poorly attempting to display the issue:

https://jsfiddle.net/p7dcdqc6/3/

**Comment by kevin-brown** [comment]
The options should be selected. I've updated the jsfiddle to show the value of the `<select>` when a change is made to the value, and you should see the tags being added to there when they are selected.

https://jsfiddle.net/p7dcdqc6/4/

The reason why they do not show as selected in the inspector is because Select2 sets the JavaScript `selected` property, not the `selected` attribute. Unfortunately the inspector does not show the state of the properties, even though they are the ones you should be relying on.

**Comment by cadecannon** [comment]
@kevin-brown Yep, I see that now and it's posting correctly.  Thanks for your help.
