### ISSUE TITLE
Set data after init

### ISSUE THREAD

**Issue by Knoxvillekm** [select2/select2#3185]
select2 4.0rc2
I need method to set data after init, like ajax search result with properties from processResults. Can you help me?

Example:
```js
$('select').select2({
  ... ,
  ajax {
    ... ,
    processResults: function (data) {
      return { 
        results: $.map(data, function (item) {
          return {
      	    id: item.id,
            text: item.text,
            full: item.full
          }
        }) 
      };
    },
    ...
  },
  initData: [ { id: 1, text: 'text', full: true } ],
  ...
});
```
or 
```js
  $('select').select2({ ... });
  $('select').select2('data', [ { id: 1, text: 'text', full: true } ]);
```

**Comment by rolfeisenhut** [comment]
hello,
i've the same request, requiring updating of the data after initializing.

**Comment by rolfeisenhut** [comment]
there is a sample for version 2.3.5.2. for loading data via a function,
but this sample does not work in 2.4.

$("#e10_4").select2({
    data:function() { return { text:'tag', results: data }; },
    formatSelection: format,
    formatResult: format
});

**Comment by jumale** [comment]
+1
I need it too.
There are select boxes, which have a dynamic list of options (depends on some external parameters).
Currently I have to do it in a way like:
```js
$('#my_select').select2({
    data: [{id: 1, text: 'a'}, {id: 2, text: 'b'}, {id: 3, text: 'c'}] // load all the possible options
})
someExternalParameters.onChange = function () {
    var activeOptions = defineBasedOnExternalParameters();
    $('#my_select').find('option').each(function(){
        if (-1 === activeOptions.indexOf($(this).val())) {
            $(this).hide()
        } else {
            $(this).show()
        }
    });
}```

but it's not so good solution as:
```js
$('#my_select').select2({
    data: function () {
        var options = defineBasedOnExternalParameters();
        return options;
    }
})

**Comment by kevin-brown** [comment]
Right now passing `data` in when initializing Select2 is a shortcut that is equivalent to creating an `<option>` for each object passed in. This is why when you initialize Select2 multiple times with similar items, new `<option>` tags are created.

So a way that you can work around this, which is similar to what you would do if you were working with a native `<select>`, is to remove all of the `<option>` elements because initializing Select2.

```js
$("select option").remove(); or // .empty()
```

If you need to preserve existing selections, then you can filter those out as well

```js
$("select option:not(:selected)").remove();
```

**Comment by Knoxvillekm** [comment]
Can you add this code:
```js
    // Set initial data
    var initData = this.options.get('initData');
    initData.forEach(function(data) {
        var $options = self.dataAdapter.option(data);
        self.dataAdapter.addOptions($options);
        self.dataAdapter.select(data);
    });
```
to project after: 
```js
    // Set the initial state
    this.dataAdapter.current(function (initialData) {
      self.trigger('selection:update', {
        data: initialData
      });
    });
```

**Comment by almogdesign** [comment]
@kevin-brown thanks

**Comment by MrHubble** [comment]
I found [this answer](http://stackoverflow.com/questions/29058625/select2-4-0-push-new-entry-after-creation/29088562#29088562) on Stackoverflow by Kevin useful

**Comment by doapp-ryanp** [comment]
@MrHubble I can get the`<option>`s removed, but .change() does not re-paint with the current `<option>`s defined in the DOM. Any ideas?

**Comment by nicolasprnt** [comment]
Any updates on this?

Is there a method like $('select').select2('data', [ { id: 1, text: 'text', extra_data1: true } ]); to set data (including extra data) after initialization without completely rebuilding the Select2 instance (especially when using an Ajax configuration)?

Currently, I use { data: initial_data, ajax: ... }, but after initialization, I need to populate it with new data without rebuilding the entire configuration and while keeping the Ajax configuration active. A solution like $('select').select2('data', [ { id: 1, text: 'text', extra_data1: true } ]); would be ideal.

The approach using new options with data-* attributes is inefficient, especially when retrieving data via select2("data") since it doesn't include the extra data.
