### ISSUE TITLE
select2 is generating "span" tags instead of "divs"

### ISSUE THREAD

**Issue by murtali** [select2/select2#3198]
I'm using select2 within a bootstrap modal and the end result is generating span tags instead of divs.

```
<span class="select2 select2-container select2-container--bootstrap" dir="ltr"><span class="selection"><span class="select2-selection select2-selection--single" role="combobox" aria-autocomplete="list" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-labelledby="select2-message_type-container"><span class="select2-selection__rendered" id="select2-message_type-container"><span class="select2-selection__placeholder">Select a template</span></span><span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span></span></span><span class="dropdown-wrapper" aria-hidden="true"></span></span>
```

I tried both 4.0.0 and 3.5.x and the same thing is happening. Any reason why?

**Comment by kevin-brown** [comment]
A standard `<select>` is inline by default, so because of that we now use `<span>` tags to define the markup. A `<div>` is block-level by default, and isn't valid within many inline tags ([such as `<p>`](http://stackoverflow.com/q/8397852/359284)).

This shouldn't be too much of an issue when styling and working with the DOM.
