### ISSUE TITLE
Can no longer format the Tags with templateSelection

### ISSUE THREAD

**Issue by JGuymer** [select2/select2#3203]
Hi 

was just upgrading our application to v4 and noticed i can longer format the tags. we rely on colour in our tags depending on the type.

in the last version we could format the tags using formatSelection, 

var formatSelection = function (object, container) {

    $(container).parent().addClass(object.cssClass);
    $(container).text(object.text);

    return;
}

![screen shot 2015-03-28 at 14 22 24](https://cloud.githubusercontent.com/assets/8407740/6881410/3c3dff42-d556-11e4-88d7-69d0509eccf2.png)

it appears i can no longer access the tag container in templateSelection? Is there a way round this or is this by design/bug.

Thanks

James

**Comment by alepore** [comment]
i think is `$(container).addClass(object.cssClass);` not `$(container).parent().addClass(object.cssClass);`

**Comment by kevin-brown** [comment]
As @alepore alluded to, the issue here is that the tag's container (passed in as the second argument) is not inserted into the DOM until after the `templateSelection` method is called. As a result, you can't do anything with the templating method that would rely on it already being present in the DOM.
