### ISSUE TITLE
4.0.0.rc2 - outline visible after closing select2 with Esc

### ISSUE THREAD

**Issue by kantyka** [select2/select2#3215]
If you close basic select2 (like the one on top of https://select2.github.io/examples.html) by pressing Esc, there is an outline visible. 
This can be fixed in css:
`.select2-container .select2-selection--single{
outline: 0
}`

**Comment by kevin-brown** [comment]
This is intentional, as the outline indicates that the container is still focused (and can receive keyboard events). The outline should be there if you click on the container a second time to close it, and if the dropdown does not have a search box.

It shouldn't be too difficult to hide it in your own theme though.
