### ISSUE TITLE
Add container to templateResult

### ISSUE THREAD

**Issue by Knoxvillekm** [select2/select2#3222]
Container need for set classes, styles, etc to option.

example:
```js
select2({
  templateResult: function(result, container) {
    if (!result.id) { return result.text; }
    $(container).addClass(result.resultClass);
    return result.text;
  }
});
```

code:
```js
  Results.prototype.template = function (result, container) {
    ...
    var content = template(result, container);
    ...
  };
```

**Comment by stretch4x4** [comment]
Yep I could use this too, going to work on a pull request for this item

**Comment by Igloczek** [comment]
Thumbs up, I need this feature too, because Select2 doesn't work well with FastClick (need extra "needsclick" class)

**Comment by hubsonx** [comment]
I have applied Select2 to my picklists in Salesforce Lightning components and everything works fine on the desktop and on my mobile phone (android 5), but on the Ipad mini nothing happens when I click on the select box.

I have discovered that lightning components use fastclick natively and I couldn't find the resolution for this in the boards. 

I have tries to apply the 'needsclick' class to my selects by it has not helped me.
Any ideas how to fix this?

**Comment by superKalo** [comment]
@hubsonx here's how I managed to finally fix it.

I have Select2 4.0.1 and FastClick 1.0.6 (both latest by the time I am writing this)

```javascript
var $customSelects = $('select');

$customSelects.select2({
    /**
     * Adds needsclick class to all DOM elements in the Select2 results list
     * so they can be accessible on iOS mobile when FastClick is initiated too.
     */
    templateResult: function(result, container) {
        if (!result.id) {
            return result.text;
        }
        container.className += ' needsclick';
        return result.text;
    }
});

/**
 * Additional to tweaking the templateResult option in Select2,
 * add needsclick class to all DOM elements in the Select2 container,
 * so they can be accessible on iOS mobile when FastClick is initiated too.
 *
 * More info about needsclick:
 * https://github.com/ftlabs/fastclick#ignore-certain-elements-with-needsclick
 *
 */
$customSelects.each(function(index, el){
    $(el).data('select2').$container.find('*').addClass('needsclick');
});
```

Here's [jsfiddle with an example](https://jsfiddle.net/superKalo/oj0sLr1n/), so you can test and make sure my code works ;-)

PS: Thanks @Knoxvillekm for your initial suggestion that fixes the dropdown list elements. I only changed it to apply class via Vanilla JS, instead of calling jQuery for that (this should perform faster).

**Comment by nobruds** [comment]
Hi, somebody knows why after I change the container cssClass I can't click on the element? its like its disabled. 
thanks
