### ISSUE TITLE
Cannot destroy select2 after creating with custom Adapter

### ISSUE THREAD

**Issue by tlshaheen** [select2/select2#3226]
I'm using `Select2 4.0.0-rc.2`, the full version, with `Bootstrap 3.2.0`.

After implementing #2873 to use select2 inside of a Bootstrap Modal, my `select2('destroy')` method now throws an error - `TypeError: d is undefined ...Array.prototype.slice.call(arguments,1);return d[c](e)}throw new Error("Invalid ...`. I was able to replicate this in a fiddle: http://jsfiddle.net/8yua1zue/

Is there a bug here, or am I latching onto an Adapter incorrectly?

**Comment by kevin-brown** [comment]
The issue does not have anything to do with the custom selectors, the issue is that `$.fn.select2.amd.require` is asynchronous, so you are trying to destroy Select2 before it is initialized.

You can confirm that by looking at the console at this fiddle: https://jsfiddle.net/p18eurd6/

![image](https://cloud.githubusercontent.com/assets/1991850/6971996/b4a9a82c-d94e-11e4-8328-c3c838281523.png)

Now, this usually wouldn't be an issue because most people do not immediate destroy Select2 after it is created.

**Comment by tlshaheen** [comment]
Ah, ok. Makes sense, sorry about that! I tried a `setTimeout(<destroy>)` and that did work.
