### ISSUE TITLE
Dropdown adapter is missing a bind method

### ISSUE THREAD

**Issue by patrykkopycinski** [select2/select2#3239]
Hi guys,

I would like to use AttachContainer decorator but for that i need to create custom dropdownAdapter, so i found some jsbin how to use it
http://jsbin.com/yisetuhuji/2/edit?html,js,output

and there it seems work well, but when i changed the version to 4.0.0-rc.2 and when i chose something from dropdown list the dropdown doesn't disappear. I can't hide the search box also. 
http://jsbin.com/jucofenodo/1/edit?html,js,output

Could i ask you to check this out and provide me some solution how to make it working? Thanks

**Comment by jaredevantabor** [comment]
I'm also using the AttachContainer decorator to attach the drop down list to the select field while using select2 on a jquery-ui modal. Using the examples posted above and on the Options page, I have been able to get it working correctly using the AttachContainer decorator AND the DropdownSearch decorator, however I don't want to use the DropdownSearch. I changed the custom adapter definition to ``var CustomAdapter = Utils.Decorate(DropdownAdapter, AttachContainer); `` so that it is no longer importing this decorator, but now I get an error message on the console: 
```Uncaught TypeError: undefined is not a function select2.full.js:4855 
S2.define.Select2._bindAdapters select2.full.js:4748 
S2.define.Select2 select2.full.js:5794 (anonymous function)```

**Comment by molily** [comment]
AttachContainer seems to be broken in 4.0.0. You can monkey-patch the missing `bind` method though:

```javascript
AttachContainer.prototype.bind = function(decorated, container, $container) {
  // Just pass the call through to the decorated class
  decorated.call(this, container, $container);
};
var CustomAdapter = Utils.Decorate(DropdownAdapter, AttachContainer); // etc.
```

Hope this helps.

**Comment by kevin-brown** [comment]
@molily Interesting, do you know why that would solve the issues? The `AttachContainer` decorator doesn't modify the `bind` method, so I'm not sure how that has any effect.

**Comment by jaredevantabor** [comment]
@molily @kevin-brown that workaround helps remove the dependency on the DropdownSearch, thank you both for your help in resolving this! 

However, I'm now experiencing some odd behavior when I'm searching by means of typing my search via the keyboard (after adding your workaround). When I type a search word and hit enter, the searched list item appears to show up correctly with the class "select2-selection__choice," but the text that was typed to originally to search is not cleared and the select2 element doesn't regain focus back in order to continue typing new search. The focus appears to remain on the drop down menu. 

Should I need to add another adapter to gain this functionality? It seems like its odd behavior with the matching.

**Comment by molily** [comment]
> Should I need to add another adapter to gain this functionality?

Yes, most likely DropdownSearch. And MinimumResultsForSearch as well if you use `options.minimumResultsForSearch`. I ended up copying the adaptor logic from Select2, see the issue I just created: #3411

**Comment by joefiorini** [comment]
I just ran into this issue myself. Select2 uses the Dropdown adapter by default, so we know that the Dropdown adapter does work, somehow. I did some digging into the default behavior to see what happens when calling `select2` without any options.  As we know, the search input shows up by default. Therefore, the `Dropdown` adapter _always_ gets decorated with the `Search` decorator.

What about when you pass `minimumResultsForSearch: Infinity` to turn off the search input? You'd think that would remove the Search decorator, but it actually just _hides_ the search input; the `Search` decorator still decorates the `Dropdown` adapter. In fact, the only possible way that you can have a `Dropdown` adapter _without_ the `Search` decorator is by requiring it yourself and passing it in for the `dropdownAdapter` option. And that's when you start getting errors.

This says to me that the real problem is that, at this time, select2 doesn't actually support using the `Dropdown` adapter without the `Search` decorator. As @jaredevantabor discovered above, you _have_ to use it in order for the adapter to get is `bind` function. That in and of itself isn't really a problem, except that it's not documented. Perhaps we need a warning in the docs explaining this?

So if you don't want search in your dropdown? Just add an additional decoration using the `MinimumResultsForSearch` decorator and pass the `minimumResultsForSearch: Infinity` option into `select2` like you normally would.

Here is the code I used to create a dropdown using the `AttachContainer` decorator with search disabled:

```
        $.fn.select2.amd.require(
            [   'select2/utils',
                'select2/dropdown',
                'select2/dropdown/search',
                'select2/dropdown/attachContainer',
                'select2/dropdown/minimumResultsForSearch'
            ],
            function(Utils, Dropdown, Search, AttachContainer, MinimumResultsForSearch) {

                var CustomAdapter = Utils.Decorate(
                                                        Utils.Decorate(
                                                            Utils.Decorate(Dropdown, Search),
                                                            AttachContainer),
                                                            MinimumResultsForSearch);

                element.find('select').select2(
                    {   multiple: scope.multiSelect === 'true',
                        minimumResultsForSearch: Infinity,
                        dropdownAdapter: CustomAdapter
                    });
            });
```

or for the more functionally inclined, you could replace the calls to `Utils.Decorate` with a `reduce` like:

```
                var CustomAdapter =
                    _.reduce([Search, AttachContainer, MinimumResultsForSearch],
                             function(Adapter, Decorator) {
                                 return Utils.Decorate(Adapter, Decorator);
                             }, Dropdown);

```

**Comment by MatthewPringle** [comment]
To have the Attach Container close on select, as you originally asked, you need to also include closeOnSelect 

jQuery.fn.select2.amd.require( [ 'select2/utils' , 'select2/dropdown' , 'select2/dropdown/attachContainer' , 'select2/dropdown/search' , 'select2/dropdown/closeOnSelect' ] , function ( Utils , DropdownAdapter , AttachContainer , DropdownSearch , closeOnSelect ) {
        
        /* Positioning */
        var CustomAdapter = Utils.Decorate( Utils.Decorate( Utils.Decorate( DropdownAdapter , DropdownSearch ) , AttachContainer ) , closeOnSelect );
		
	/* Style Select */
        jQuery( '#select' ).select2({
            width: '100%',
            placeholder: "Select an option",
            multiple: false,
            closeOnSelect: true,
            dropdownAdapter: CustomAdapter
        });

    });
