### ISSUE TITLE
$.fn is undefined when using require() in node

### ISSUE THREAD

**Issue by leftmostcat** [select2/select2#3282]
In the jquery.select define in dist/js/select2.js, there is an error on [line 5555](https://github.com/select2/select2/blob/f2268caf23d2a50944f1d8f8211f1501fa259163/dist/js/select2.js#L5555) when select2 is require()d server-side (for shared server-side/client-side code). Execution of the node file results in the following:

TypeError: Cannot read property 'select2' of undefined

In each other instance where $.fn is accessed in this file, it has been wrapped in another function which is declared on a prototype object, suggesting that it is not being actively run server-side.

This occurs with current master (c80b4b0).

**Comment by webholics** [comment]
Is there any progress on this problem. I can reproduce it with the current version of select2.
The PR #3288 did not fix it.

**Comment by lkrnac** [comment]
+1 for fixing this

**Comment by brookslyrette** [comment]
Would love to know if there is any progress on this.

**Comment by frontenddeveloping** [comment]
+1 not for node only.
Any commonjs like solution, for example ES2015 modules by webpack+babel

**Comment by jreading** [comment]
This is still jacked, no? I simply can't use 4.x in browserify-d app...

**Comment by lightning18** [comment]
Are there any workarounds, at least? :smiley:

**Comment by davidohayon669** [comment]
+1 for a fix

**Comment by jreading** [comment]
Turns out I just needed another browserify alias for jquery:  `jQuery`

Here's some fried shrimp:
🍤 🍤 🍤 🍤 🍤 🍤 🍤 🍤

**Comment by davidohayon669** [comment]
I'm glad to hear its a small thing,
Got any quick suggestion for what to do exactly with Webpack?

**Comment by frontenddeveloping** [comment]
@davidohayon669 

Take a look at the `module.noParse` field in Webpack.

**Comment by davidohayon669** [comment]
noParse on the file didn't work. select2.js was still looking for a global $ on the import and couldn't find it

this solution helped me eventually
https://65535th.com/jquery-plugins-and-webpack/

**Comment by batterseapower** [comment]
I had this problem when trying to use select2 in my Typescript tests via node-ts, no webpack. The problem is that when you require jquery in an environment where "window" is not available, Jquery does something weird. Normally you would expect it to export the usual "jquery function" but when "window" is missing it instead exports a *constructor function* that takes a window and returns the usual Jquery function.

This is the cause of the "$.fn is undefined" error -- select2 is trying to access the ".fn" property on the constructor function, rather than the thing returned by that function.

So the solution for me was to make the "window" object available. I used jsdom for this:
```
const jsdom = new JSDOM('<!doctype html><html><body></body></html>');
global.document = jsdom.window.document;
global.window = jsdom.window;
```

**Comment by niteshluharuka** [comment]
Do we have any solution for this as of now?
