### ISSUE TITLE
bug with the dupe check in defaultTokenization

### ISSUE THREAD

**Issue by franckl** [select2/select2#3283]
When copy/pasting the following "a a b" in the auto Tokenization example available in the documentation for Select2 3.5.3 you get two duplicate tokens, "a" and "a". 

It should not allow duplicate in this case.

![image](http://zippy.gfycat.com/HarmfulWickedItaliangreyhound.gif)

**Comment by nickbarry** [comment]
I observe a similar problem that is probably due to the same part of the code.

## Steps to reproduce the issue

1. Go to this demo page: https://select2.github.io/examples.html#tokenizer
2. In the tags field, type "red,  red" [note TWO spaces after the comma]
3. Note that "red" now exists twice. 

## Expected behavior and actual behavior

When I follow those steps, I see..."red" twice.

I was expecting..."red" once. It seems that the extra padding of the spaces prevents the dropdown from recognizing "  red" as the same as the existing "red" item. It seems that the spaces are stripped away afterward, because when I inspect the source for the second "red" token, there aren't any spaces in the title or innerText of the element. So the spaces should probably be stripped away before checking if the text matches any existing tags.

## Environment

Browsers
- [ ] Google Chrome

Operating System
- [ ] Windows 10

Libraries
? Whatever's on your demo page

## Isolating the problem
- [x] This bug happens on the examples page: https://select2.github.io/examples.html#tokenizer
I don't know where else, since I don't yet have select2 set up on my machine.

**Comment by alexweissman** [comment]
May be the same issue described in #4610.
