### ISSUE TITLE
browserify errors if jquery.mousewheel is not in node_modules

### ISSUE THREAD

**Issue by leftmostcat** [select2/select2#3287]
When including dist/js/select2.js, browserify fails upon reaching [line 5328](https://github.com/select2/select2/blob/master/dist/js/select2.js#L5328) due to jquery.mousewheel not being present in node_modules/ for select2.

**Comment by kevin-brown** [comment]
Still need to do some testing here to see if we can just change the word `require` (local variable) to something else, as it doesn't look like Browserify is looking at the syntax tree at all.

**Comment by Svjard** [comment]
+1

**Comment by samholmes** [comment]
+1

Why doesn't select2 just include jquery-mousewheel as a dependency in the package.json file??

**Comment by kevin-brown** [comment]
> Why doesn't select2 just include jquery-mousewheel as a dependency in the package.json file??

jquery-mousewheel is an optional dependency, which is surprisingly difficult to do with browserify. Unlike most module loaders, browserify does not allow modules to be loaded on the fly.

**Comment by samholmes** [comment]
If it's optional because jquery-mousewheel is a shim, then it must be decided if Select2 wants to handle the shim or let the developer handle the shim. A package shouldn't have an *optional* dep. The way I see it, there are two options:

1. Let the developer add the jquery-mousewheel package to his project, and pass this off to Select2 under some kind of configuration. This option is basically saying that Select2 isn't concerning itself with shims/polyfills.
2. Require the jquery-mousewheel package as a dependency in Select2 package.json. This is saying that Select2 uses the jquery-mousewheel package as a shim/polyfill when it's needed, and so it is required to be bundled with it. Select2 can still be smart on when it uses the jquery-mousewheel plugin (using feature detection and whatnot).

The first one is better if you want to keep Select2 more lean and focused (unix-philosophy-like), but the second option is certainly easier on the developer.

**Comment by jorrit** [comment]
I think it should be an explicit dependency too.

jquery.select2.js contains:

```javascript
define([
  'jquery',
  'require',

  './select2/core',
  './select2/defaults'
], function ($, require, Select2, Defaults) {
  // Force jQuery.mousewheel to be loaded if it hasn't already
  require('jquery.mousewheel');
```
The requirejs docs explicitly state on http://requirejs.org/docs/errors.html#notloaded:

> In particular, the following will not work:
> //THIS WILL FAIL
> define(['require'], function (require) {
>     var namedModule = require('name');
> });
> This fails because requirejs needs to be sure to load and execute all dependencies before calling the factory function above.

**Comment by vinogradov** [comment]
+1

**Comment by LKay** [comment]
+1

I hope it will be finally resolved soon...
Any plans to make library commonjs, amd compatible without the need of these hacks mentioned above?

**Comment by FutureKode** [comment]
+1

**Comment by Hiswe** [comment]
+1

**Comment by schrepfler** [comment]
+1

**Comment by jthompson18** [comment]
+1

**Comment by chotikarn** [comment]
+1

**Comment by erlendoh** [comment]
+1

**Comment by ubaydinoyatov** [comment]
+1

**Comment by kevin-brown** [comment]
This should have been fixed by https://github.com/select2/select2/commit/8edf3c64082be59b9506f3ad6dd84073b6eb5841.
