### ISSUE TITLE
Placeholder width is 0px when select2 is initialized

### ISSUE THREAD

**Issue by brandonhall** [select2/select2#3292]
We have a Backbone app which inits `select2` before it is visible on the page. As a result, the `select2-search__field` width is always `0px` because that's the `innerWidth` when it's initialized. This caused placeholders to be hidden.

Here's the relevant block of code in `select2`...

```
 if (this.$search.attr('placeholder') !== '') {
  width = this.$selection.find('.select2-selection__rendered').innerWidth();
} else {
  var minimumWidth = this.$search.val().length + 1;
  width = (minimumWidth * 0.75) + 'em';
}
```

As a result, the solution was to use `setTimeout` which initialized select2 after it was visible on the page
but that causes all sorts of bouncing around on the page as the elements are initialized.

I added an OR condition to use 100% if innerWidth is 0 to prevent this. Like so: `width = this.$selection.find('.select2-selection__rendered').innerWidth() || '100%'`

I'm not sure it's the preferred solution but it does the job and fixes the issue.

**Comment by kevin-brown** [comment]
While there is a lot of good information here, would it be possible for you to create a jsbin/jsfiddle where we can reproduce this?

**Comment by brandonhall** [comment]
I don't know if it can be replicated in jsbin/jsfiddle since it requires a template language, dynamic DOM insertion. Without the element in the DOM, it would be tricky to reproduce in one of those tools.

**Comment by donald-slagle** [comment]
I'm running into the same issue. I'm using Aureila and created a custom control that uses select2. The custom control initializes select2 before it is rendered and the placeholder width is set to 0px. If I inspect it in chrome and remove the 0px width it displays correctly.

**Comment by wbercx** [comment]
Same issue here, also in a Backbone app where Select2 gets instantiated on render, rather than when actually shown in the DOM, so innerWidth() fails.

What I ended up doing was `width = this.$selection.find('.select2-selection__rendered').innerWidth() || '100%'`, as suggested by @brandonhall, but that still resulted in the input field not being wide enough to display the entire placeholder in some cases. This seems to be the case because the inline search is floated to the left.

An extra line of CSS to stop `float: left` from being applied when there are no selected items did the trick there: 
    `.select2-container .select2-search--inline:only-child { float: none; }`

**Comment by Joyrex** [comment]
I'd like to add that this fix works exactly like @wbercx mentions - the additional CSS keeps longer than usual placeholders from being cut off when using the JS fix proposed by @brandonhall.

Is there any reason this still isn't merged into the current release?
