### ISSUE TITLE
v4 is difficult to use with Typescript

### ISSUE THREAD

**Issue by nchen63** [select2/select2#3315]
We’re finding that using the v4 Select2 library is a little difficult to use with TypeScript due to the required AMD loader notation. For example, to override a data adapter such as `ArrayData` in Typescript, one would normally extend a class. Instead with AMD, it’s more difficult because the user has to call `Utils.Extend()`, assign new functions directly to .prototype to override base class calls, and call `.__super__.contructor.call()` in the constructor. Am I approaching this correctly, or can you suggest a cleaner way of doing things?

**Comment by Trapulo** [comment]
Same hell. I was using 3.x but 4.0 is an hell and I cannot maket it working... I cannot write a custom dataAdapter, any idea?

**Comment by jzabroski** [comment]
@nchen63  Did you ever figure out a solution to this?

**Comment by kevin-brown** [comment]
Using decorators (which are recommended over adapters) with TypeScript isn't that much different from normal JavaScript. It's actually a bit cleaner (because of TypeScript's classes).

```typescript
class MyAmazingDecorator {
    constructor(decorated: Function, $element: JQuery, options) {
		decorated.call(this, $element, options);
    }
    bind(decorated: Function, container, $container: JQuery) {
		decorated.call(this, container, $container);
		
		container.on('close', function () {
			alert('Why did you close this?');
		});
	}
}

$.fn.select2.amd.require(['select2/utils', 'select2/data/array'], function (Utils, ArrayAdapter) {
	var adapter = Utils.Decorate(ArrayAdapter, MyAmazingDecorator);
	
	$('select').select2({
		dataAdapter: adapter
	});
});
```

And if you want to extend a class (instead of decorating it), Select2's class structure is actually directly compatible with TypeScript's. So you can use the standard TypeScript inheritance without too many issues.

```typescript
$.fn.select2.amd.require(['select2/data/array'], function (ArrayAdapter: typeof Function) {
	class MyAmazingAdapter extends ArrayAdapter {
		constructor($element: JQuery, options) {
			super($element, options);
		}
		bind(container, $container: JQuery) {
			super.bind(container, $container);
			
			container.on('close', function () {
				alert('Why did you close this?');
			});
		}
	}

	$('select').select2({
		dataAdapter: MyAamazingAdapter
	});
});
```

_Note: all of this has been compiled using the online [TypeScript playground](https://www.typescriptlang.org/play/) and verified [in this jsbin](http://jsbin.com/tonesamoxo/1/edit?html,js,output)_.
