### ISSUE TITLE
v4 select not being closed when clicking on element with stopPropagation (while v3 does)

### ISSUE THREAD

**Issue by vedmack** [select2/select2#3316]
Hi,

I noticed that while in the select v3 the select element got closed when user clicked on element with stopPropagation, in the new version v4 of select the select element stays open

Steps to reproduce: 

1) open select element
2) click the "click me" button

Expected results:

select element being closed when clicking the "click me" button

See samples: 

[3.5.2](http://jsbin.com/pojucimuga/1/edit?html,js,output)

[4.0.0](http://jsbin.com/fumipuvuse/1/edit?html,js,output)

**Comment by daftspunk** [comment]
We are also affected by this over @ OctoberCMS, any pointers as to how we can fix this in the interim?

**Comment by kevin-brown** [comment]
There isn't an easy fix with this, as Select2 relies on the `click` event propagating.

There were plans a few months back to bring back the click mask as a decorator, and it shouldn't be _too_ difficult to implement right now (as a wrapper for `dropdownContainer`, most likely.

**Comment by daftspunk** [comment]
I thought so, it was difficult to see where the logic is.

There is a simple jQuery plugin called 'clickOutside', how would this be converted to a decorator as you suggest? Appreciate anything I can get at this point! :+1: 

```
$.fn.extend({
    clickOutside: function(handler, exceptions) {
        var $this = this;

        $('body').on('click', function(event) {
            if (exceptions && $.inArray(event.target, exceptions) > -1) {
                return;
            } else if ($.contains($this[0], event.target)) {
                return;
            } else {
                handler(event, $this);
            }
        });

        return this;
    }
})

// When anything *other* than .container (or nested children) is clicked
$('.container').clickOutside(function() {
    // Close dropdown
})
```

**Comment by kevin-brown** [comment]
It might be useful to mention that Select2 uses [that exact pattern](https://github.com/select2/select2/blob/34224604880875a47e5f6e4b5cc3bfe2e01f7b4b/src/js/select2/selection/base.js#L119-L136) (catching `click` on the `body`, checking the target) for closing the dropdown. The problem is when the `click` doesn't make its way up to the `body`, because `stopPropagation` is being called.

I also just rediscovered [a `ClickMask` decorator](https://github.com/select2/select2/blob/34224604880875a47e5f6e4b5cc3bfe2e01f7b4b/src/js/select2/selection/clickMask.js) for the `selectonAdapter` which _might_ still work, even though it hasn't been touched for half a year.

**Comment by daftspunk** [comment]
Great stuff, thanks for pointing out that code!

Using a mask would certainly be more efficient and reliable. The auto closing behavior is a UX pattern that is expected in most cases and would be unusual to want it to stop--hence why the current behavior feels like a bug, although I know it's not. So long as the mask can be disabled then everyone should be happy. Using a mask could also have the cool side effect of being able to style the mask, like a modal backdrop :-)
