### ISSUE TITLE
The widget does not accept empty string as value

### ISSUE THREAD

**Issue by salarmehr** [select2/select2#3322]
Select2 does not accept `{'id':'',text:'unknow'}` as an option. It is shown in pop-down menu but when you select it, nothing is selected. Is there any workaound?

**Comment by kevin-brown** [comment]
What version of Select2? Can you reproduce this in a jsfiddle?

**Comment by salarmehr** [comment]
@kevin-brown Version 4.0. I will try to reproduce it in a jsfiddle.

**Comment by ifightcrime** [comment]
Having the same problem on 4.0.3: https://jsfiddle.net/3toxu6q2/

The option value should be set as empty ex: `<option value="">Placeholder</option>`

**Comment by kevin-brown** [comment]
@ifightcrime I'm still not sure what you mean. The value is being set to an empty string, and the option is selected in your jsfiddle.

You can verify this by adding additional options, so you can observe the selection changing.

https://jsfiddle.net/bphpkv6z/

**Comment by ifightcrime** [comment]
The html rendered should have the attribute `value` set with an empty string. Otherwise for example calling jQuery val() on it will return "Placeholder" instead of an empty string which makes it harder to validate field presence. It also even does the same to the form data when submitting the form.

Check out the jsfiddle I updated: https://jsfiddle.net/bphpkv6z/3/

<img width="400" alt="screen shot 2016-06-08 at 6 48 32 pm" src="https://cloud.githubusercontent.com/assets/616525/15916633/b293a258-2da9-11e6-8729-b88d575f7bea.png">

<img width="930" alt="screen shot 2016-06-08 at 6 51 34 pm" src="https://cloud.githubusercontent.com/assets/616525/15916694/3c601cbe-2daa-11e6-9d5f-dcfa8247ff16.png">

**Comment by ifightcrime** [comment]
PS now that I'm looking, this may be actually be a different issue than what @salarmehr had.
