### ISSUE TITLE
AllowClear not working in muliple select2

### ISSUE THREAD

**Issue by macrawat** [select2/select2#3337]
~~~php
<?=     $form->field($model,'course_choice')->widget(Select2::classname(), [
    'data' => Courses::getCourseList(),
    'size'=>Select2::MEDIUM,
    'options' => ['placeholder' => 'Select Courses ...', 'multiple'=>true],
    'pluginOptions' => [
        'allowClear' => true,
    ],
])
    ?>
~~~

I am using multiple select2 with active form(yii2 basic),applying  allowClear true in plugin options not working. What could be the issue ??

**Comment by kevin-brown** [comment]
This has only been "supported" since 4.0.0, but I personally wouldn't recommend using it.

---

This appears to be an issue that is not directly related to Select2, but instead is related to an integration or downstream project that is not officially supported by Select2.  It is recommended that you create a ticket at the downstream repository or send a message to the [mailing list][ml] for help.

https://github.com/kartik-v/yii2-widget-select2

[ml]: https://github.com/ivaynberg/select2#mailing-list
