### ISSUE TITLE
Almond inside select2.js

### ISSUE THREAD

**Issue by Poplava** [select2/select2#3372]
Guys, why do you put Almond.js source code inside the select2.js build?
I've broken my brain while debugging on the issue with a requirejs optimizer.

**Comment by wbercx** [comment]
Did you manage to get it working? This is doing my head in at the moment.

**Comment by kevin-brown** [comment]
There is probably a duplicate ticket about this, but...

Before doing the 4.0.0 release I did a few tests with r.js and didn't run into any problems. What problems specifically are you running into?

**Comment by simonedeponti** [comment]
I have I think the same problem. What happens is that when you use `r.js` (via `grunt-contrib-requirejs`) in the final file Select 2 ends up on top of everything (including `requirejs` itself).

This means that the initial if doesn't find `define`, falls back to browser globals and you end up with `jQuery` not being found.

Is it maybe that the use of a slightly different intro and outro (compared to the usual ones I see on most libraries) confuses `r.js`?

**Comment by wbercx** [comment]
Apologies for the late reply.

@simonedeponti That is exactly what is happening to me too. Select2 ends up being the very first thing in the built file, define check fails, and when running `factory(jQuery)`, jQuery comes out being undefined. Shimming it to specify that Select2 depends on jQuery seems to make no difference at all. It always ends up on top before anything else is defined. This occurs when using `dist/js/select2.js` or `dist/js/select2.full.js`.

I am currently loading Select2 from the `src/js/jquery.select2.js` file. To get that working, I had to specify paths to the Select2 `src` directory and to `jquery.mousewheel` in my `require.config`.

When I did not set the path to the `src` directory, as soon as it would load `./select2/core` and `./select2/defaults` inside the `define` in `jquery.select2.js`, strange things happened. It would end up trying to load `src/js/jquery.select2/core` for example. I found this quite odd, because it seemed to use part of the filename to represent the `.` to calculate the relative path from.

Either way, the final result is an optimized file that works.

**Comment by simonedeponti** [comment]
I have resolved it in a similar way (right before seeing your reply). What I did was to add (via shim) a dependency on `requirejs` and `jquery` (or `almond` if you use that) and it seems to work.

My guess is that `r.js` somehow got confused when reading out `select2` dependencies and decided it could do without `jquery`.

**Comment by Poplava** [comment]
Sorry for the late feedback.

Today I got this problem again :(

I sure it because Almond is included in the build file...

**Comment by vukoje** [comment]
Today this broke my brain too. I'm surprised no one is taking care of this.

**Comment by kevin-brown** [comment]
Note that the bug that was previously mentioned was fixed in https://github.com/jrburke/requirejs/issues/1342. It should be fixed by upgrading to version 2.1.18 of higher of the r.js build tool.

You can pull from the `src` directory instead of the compiled `dist` files if you do not want to use the packaged versions. You will need to still require `jquery.select2` in order for Select2 to be loaded and attached.
