### ISSUE TITLE
select2.full.js is not compatible with query option

### ISSUE THREAD

**Issue by dbwhddn10** [select2/select2#3395]
http://plnkr.co/edit/o4A5mA

second element cannot select query data item

**Comment by kevin-brown** [comment]
Here's a plunkr that uses your code but runs as-is: http://plnkr.co/edit/vGe5Rhq0aNjmhXmPkssB?p=preview

And removing your second `query` method (which was overriding the first) fixes your issue with no results: http://plnkr.co/edit/vGe5Rhq0aNjmhXmPkssB?p=preview

![image](https://cloud.githubusercontent.com/assets/1991850/7786357/4739d766-0195-11e5-9c52-e523cc1d6f9b.png)


----

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://github.com/select2/select2#mailing-list
[irc]: https://github.com/select2/select2#irc-channel
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes

**Comment by dbwhddn10** [comment]
http://plnkr.co/edit/o4A5mA?p=preview
@kevin-brown $('#select2') element's initSelection not operate

**Comment by kevin-brown** [comment]
http://plnkr.co/edit/9e80kf3A4D6PUCJeFiGB?p=preview

The issue here appears to be that in your `initSelection` and `current`, you are checking to see if the value was set. But your `<select>` has no options, and none of them are `selected`, so there is no set value and `.val()` is returning `undefined`.

> $('#select1') element's dataApater.current is operate.

If you put a log at the top you will notice that it is being triggered.

----

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://github.com/select2/select2#mailing-list
[irc]: https://github.com/select2/select2#irc-channel
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes
