### ISSUE TITLE
Select2 Outputs to JavaScript Console

### ISSUE THREAD

**Issue by shefik** [select2/select2#3399]
When using Select2, the object keeps outputting to console.log when rendered.

**Comment by snichini** [comment]
you have to set the options
```javascript 
debug:false
```

**Comment by kevin-brown** [comment]
Select2 will only output to the console under a few conditions, usually because something wrong is happening (or may happen). Most of the common, not-as-harmful warnings are disabled by default and can be enabled by setting `debug: true` when initializing Select2 (or `$.fn.select2.defaults.set('debug', true)` globally).

By default, the following cases will log a message to the console without debug enabled:

- [jQuery wasn't found when Select2 was setting up](https://github.com/select2/select2/blob/fdb2b6aaf2265e356611f14e81be3f8b4b080d7c/dist/js/select2.js#L463-L469)
- [You called `.select2('anything')` when Select2 was not initialized on an element](https://github.com/select2/select2/blob/fdb2b6aaf2265e356611f14e81be3f8b4b080d7c/dist/js/select2.js#L5348-L5353)

More may be added to the future, but these will be triggered as errors (`console.error`) and usually provide a more clear explanation to the (browser-triggered) error that is going to follow it.

> you have to set the options `debug: false`

This is done by default.
