### ISSUE TITLE
Highlight is reset when new data is appended to the results

### ISSUE THREAD

**Issue by nasospsa** [select2/select2#3412]
Check the "Loading remote data" example on the examples page

**Comment by nasospsa** [comment]
src/js/select2/results.js, line: 248
dist/js/select2.full.js, line: 984

If you disable this line, "self.setClasses",
it works as intended.

Still cant understand why this function has to be called here

**Comment by nasospsa** [comment]
Any news on that?

**Comment by kevin-brown** [comment]
> Any news on that?

It's a bug, we're aware of it. We always encourage pull requests if anyone has the time to track down and correct the issue, otherwise tickets wait until they show up near the top of our list.

This ticket is not currently attached to a milestone, so there is no release where we can point to where this problem will be fixed.
