### ISSUE TITLE
does not respect "selected" attribute if value attribute is empty string, instead displays Placeholder

### ISSUE THREAD

**Issue by Zxurian** [select2/select2#3422]
Fiddle: http://jsfiddle.net/7k3d406e/
Second example "Empty" should be selected, instead it's displaying the placeholder. If you update the second select and put anything in the value attribute, then select2 works as it should, defaulting to the selected option.

**Comment by kevin-brown** [comment]
The placeholder by default works when the value is a blank string (generally `<option></option>`, but really it just needs to be the value). In your case, the selected value is the blank string, so Select2 detects that the placeholder option is selected and displayed the placeholder.

You can change the value to detect the placeholder on by passing in an object as the placeholder instead of a string. It follows the same format as the data object that Select2 uses, with the `id` being the value and the `text` being what to display.

```js
{
  id: 'the option value',
  text: 'The placeholder to display
}
```

This is documented [in the placeholder documentation](https://select2.github.io/options.html#placeholder).

**Comment by Zxurian** [comment]
so just to clarify, if I have one or more options that have an empty value within a select statement, then it's required for me to specify the placeholder option with a different value, otherwise select2 will overwrite the selected with the placeholder value?

**Comment by kevin-brown** [comment]
Based on the [current detection code](https://github.com/select2/select2/blob/bd6148e39f753ed2880f674a90b42ffe446b893a/src/js/select2/selection/placeholder.js#L33), yes that is correct.
