### ISSUE TITLE
How to bind select2 on dynamic element?

### ISSUE THREAD

**Issue by ustb** [select2/select2#3442]
I don't find any solution to bind select2 on dynamic element.
If there is a option like selector,I think it will solve the problem.

for example:
<code>
$('body').tooltip({
    selector: '[data-toggle="tooltip"]'
});
</code>

**Comment by kevin-brown** [comment]
Your example works for tooltips because they are triggered on an event. In order for something like Select2 to work like that, there would have to be some event triggered that would initialize Select2.

It's difficult to detect elements that are appended to the DOM, and it's not worth it to do it anyway.

---

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://github.com/select2/select2#mailing-list
[irc]: https://github.com/select2/select2#irc-channel
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes
