### ISSUE TITLE
Usability issue in infinite scrolling

### ISSUE THREAD

**Issue by pranav2410** [select2/select2#3479]
i have select2 with infinite scrolling,
the problem is whenever select2 fetches more results from remote data-source the highlight is shifted to the first element in the list instead of highlighting the next element in list
for repo : on your examples page 
1) try Loading remote data example
2) enter some keyword
3) use down arrow key to load more data and go to last element so that it will load more data
4) the focus goes to first element of drop down after loading new data

**Comment by pranav2410** [comment]
any update on this?

**Comment by AlexanderLeonov** [comment]
I ran into the same problem. We currently use version 3.5 and we have plans to migrate to version 4, but in order to do that it must support "keyboard-only" model well, so this behavior "as is" will not work for us.

So I did some investigation and it appears to me that the problem is with setClasses function. It does not follow "separation of concerns" principle: instead of just setting classes on newly loaded items like its name suggests it does also change highlighted item (lines after $options.each() cycle). This leads me to three points:
- Changing highlighted item is definitely a separate concert and it should not happen here, regardless of considering anything else;
- "results:append" event handler (through setClasses() call or by any other means) should not change highlighted item in dropdown at all. It should still call setClasses() though to update "aria-selected" on any newly loaded items if they've already been selected before current data loading;
- For performance reasons it should probably go through only newly loaded items, not all of them, cause previously loaded data had already been processed on previous data loads and user actions. Even if personally I didn't see any performance problems yet it doesn't mean that it should not be optimized.

So my conclusion is that setClasses() definitely should be rewritten.

Kevin - what do you think? I can prepare pull request to fix it if it works for you.

**Comment by kevin-brown** [comment]
> Kevin - what do you think? I can prepare pull request to fix it if it works for you.

If you can think of a better way to handle `setClasses`, I'm all for it. I'll gladly review any pull requests that are sent in.
