### ISSUE TITLE
IE11 and appending buttons to the multiselect dropdown

### ISSUE THREAD

**Issue by wilkmit** [select2/select2#3486]
I am attempting to append some buttons before the select2 drop down list. Everything is working fine but IE11 and IE10 are giving me some issues. It seems to only fail when attempting to append inside the drop down. Ask me anything and I appreciate the help in advance.

Update: It seems to work sometimes so you may need to play around with it to see the issues.

**Fiddle**

http://jsfiddle.net/wphqwvLf/11/

**HTML**    
    
    <label for="positionType" class="required ">Position type(s):</label>
    <select id="positionType" class="width100" multiple>
        <option>11111111111111</option>
        <option>22222222222222</option>
        <option>33333333333333</option>
    </select>

**JS** 

    $("#positionType").select2({
        placeholder: "<<< Select >>>",
    });

    $(".select2-selection").one("click", function () {
        $('#select2-positionType-results').before('<button id="positionTypeSelectAll" type="button" class="btn btn-default">Select all</button><button id="positionTypeNone" type="button" class="btn btn-default">None</button>');
    });

    $(".select2-selection").click(function () {
        $("#positionTypeSelectAll").click(function () {
            $("#positionType > option, #positionType > optgroup > option").prop("selected", "selected");
            $("#positionType").trigger("change")
            $("#positionType").select2('close');
        });
        $("#positionTypeNone").click(function () {
            $("#positionType > option, #positionType > optgroup > option").removeAttr("selected");
            $("#positionType").trigger("change");
            $("#positionType").select2('close');
        });
    });

**Comment by kevin-brown** [comment]
You should be using `.prop('selected', true)` and `.prop('selected', false)` instead of `.prop('selected', 'selected')` and `.removeAttr('selected')`. Select2 uses the `selected` DOM property instead of the DOM attribute to maintain the selected state.

---

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://github.com/select2/select2#mailing-list
[irc]: https://github.com/select2/select2#irc-channel
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes

**Comment by wilkmit** [comment]
Thanks
