### ISSUE TITLE
Double instantiation causes extraneous change event

### ISSUE THREAD

**Issue by herbalite** [select2/select2#3549]
In my code I accidentally called select2() twice on the same select tag.

The result was that we got extra change events. Took me quite a while to figure out the cause of this issue and why change events were issued even when no visible user changes were done in the select box.

My request: Can the creation/instantiation part of select2 safeguard against possible multiple instances on the same select element?

Ideally, there would be an optional debug message. Undecided however: Should options be updated if they differ between different calls? Probably not, if multiple assignments are deemed an error.

**Comment by kevin-brown** [comment]
[Select2 should destroy itself](http://git.io/vq3NL) if it's intialized twice, and that should kill any extra events being triggered or handled by the original instantiation. So, we're going to need some more information in order to figure out what the issue is.

----

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by herbalite** [comment]
After your explanation and inquiry and my further further investigation I close this report for now, as I realize it's hard to guard select2 from what was happening in all browsers tested with (Chrome, FF), using the latest libraries of select2, jquery and jquery-ui and browsers) Also making an easy test case seems not to be possible because in my case select2 is embedded within a jQuery-ui widget

To make it short, async calls, a triggered change event, there is the possibility that the browsers got the change event at the wrong moment. 

So I trust your explanation that select2 destroys itself properly for the time being. Sorry for taking up zour valuable time
