### ISSUE TITLE
Placeholder only works when there's an empty option element

### ISSUE THREAD

**Issue by samholmes** [select2/select2#3553]
This is clearly a bug. If there's no option element with the selected attribute, then the first element is selected even when a placeholder being used for the option element.

The plugin should default to the placeholder text if there is no selected option.

**Comment by kevin-brown** [comment]
There is no difference between a `<select>` without any selected options, and a `<select>` where the first option has the `selected` property set. You can confirm this at the following jsbin, which does not use Select2

http://jsbin.com/mirizuseco/1/edit?html,js,output

Select2 needs the empty option for the _placeholder_, because the browser does not supply a _placeholder option_ by default. This is expected behaviour, as Select2 is supposed to be a drop-in replacement for a standard `<select>`.

**Comment by samholmes** [comment]
*I will refer to the standard `<select>` element as Select1.*

I see. So, Select1 will have the first element selected and doesn't support placeholder. If I were to use Select1, the first option would be submitted in my forms even though I (the user) didn't select the first option. So, it makes since to make Select2 consistent with the behavior of Select1.

*I found out that Select2 supports `data-` attributes for options, such as the placeholder option.* :+1: 

I will argue this: why not make Select2 automatically add a empty element when the placeholder option is used for convenience? The reasoning is this: if you're using the placeholder option without an empty option in your select, it doesn't do anything, so you must be redundant by adding an empty option. Also, since the placeholder attribute isn't supported in Select1, it would make since that the `data-placeholder` attribute (or option) makes Select2's behavior different from Select1 (in other words, Select2 can still remain a drop in replacement). Making the placeholder option for Select2 more convenient to use is a win IMO.

**Comment by kevin-brown** [comment]
Thank you for continuing this discussion, it's an issue that comes up from time to time and it's (still) not well documented.

> why not make Select2 automatically add a empty element when the placeholder option is used for convenience?

In one word: _magic_

Select2 strives to be a _drop-in replacement_ for a standard `<select>` and is limited by some of the same restrictions. [As I explained above](https://github.com/select2/select2/issues/3553#issuecomment-119399115), there is a reason for why this happens _as of 4.0.0_ because of how the browser handles default selections. While there are plenty of things that Select2 _could do_, we are trying to encourage _third-party plugins_ to hold some of the more "magical" features that could be implemented. Avoiding extra "magic" in the core allows us to take the focus off of _edge cases_, _unexpected behaviour_, and _browser compatibility issues_ that could otherwise cause problems.

If we were to automatically generate the placeholder option, there would be a few situations that we would have to handle

- Select2 initialized without `placeholder`

  At this point, Select2 would behave as it normally does.

- Select2 initialized with `placeholder` and includes an `<option>` with a matching value (typically blank)

  Select2 would again behave as it normally does, with the placeholder being displayed whenever the corresponding `<option>` was selected.

- Select2 initialized with `placeholder`, but does not include an `<option>` that holds it

  Select2 would need to automatically generate a placeholder and then add it as an `<option>` to the `<select>`. This isn't actually that difficult - Select2 already has the ability to generate an `<option>` from a data object, and a data object is automatically generated for the `placeholder`.

  This would have to handle two different situations though

  - If there were no options explicitly selected, Select2 would have to detect this and change the selected option back to the newly created placeholder. This shouldn't be too difficult to detect, the first option will be selected by default in these cases.

  - If there were options that were explicitly selected, Select2 could just keep them selected and add the hidden `<option>` in the background.

  But there's a problem: What's the difference between a `<select>` where no options were selected (so the placeholder should be displayed) and a `<select>` where the first option was selected? _There is no difference, and that's a problem._

That third case would cause an issue where Select2 could not detect when the placeholder needed to be reset to the default. And that's a problem, as **all `<select>` elements where the first element is selected would be broken**.

This extra convenience would come with _broken edge cases_ and _unexpected behaviour_.

It's easier to explain that you need to add the placeholder option because of the spec than explain why Select2 is injecting a new `<option>` for some reason. [We already do that for the `data` option](https://github.com/select2/select2/issues/3185#issuecomment-88955394) (for backwards compatibility reasons) and [even that needs to be documented](https://github.com/select2/select2/issues/3348#issuecomment-101287137) _because it is unexpected_.

**Comment by samholmes** [comment]
>But there's a problem: What's the difference between a <select> where no options were selected (so the placeholder should be displayed) and a <select> where the first option was selected? There is no difference, and that's a problem.

Wouldn't the difference be that the first option has a `selected` attribute? If it does, then keep that selected, but still add the empty option.

Why would someone ever want a placeholder if there is no empty option in the select?

**Comment by kevin-brown** [comment]
> Wouldn't the difference be that the first option has a selected attribute?

The `selected` property is set by the browser for the first option if no other options have it. This isn't behaviour that can be overridden, and it's _probably_ part of the specification.

Here's a new jsbin that shows what I mean by that

http://jsbin.com/fudohozusu/1/edit?html,js,output

Even after inserting the placeholder, the `value` is still set to the original option and it's still `selected`.

**Comment by samholmes** [comment]
What if you use the actual attribute in this instance: http://jsbin.com/botonofojo/1/edit

**Comment by kevin-brown** [comment]
> What if you use the actual attribute in this instance

The `selected` HTML attribute is not accurate after the initial page load. It does not reflect the state of currently selected options, and is not synchronized with the `selected` JS property.

http://jsbin.com/kukotugefu/1/edit?html,js,output

**Comment by samholmes** [comment]
Makes sense. Looks like the only way placeholders can work is when the select has the multiple attribute. When it's a multiple select, it's possible to not have a selection, so the empty option element isn't necessary.

**Comment by svivian** [comment]
Just came across this issue myself. I think this is a big failure of the docs. [They just say](https://select2.github.io/examples.html#placeholders) to add `placeholder: "Select a state"` but don't explain you need an empty option element.

In fact, I'd been trying to get this to work for a while and ended up using [the code from here](https://select2.github.io/announcements-4.0.html#flexible-placeholders) when I didn't want or need that particular setup.

**Comment by kevin-brown** [comment]
@svivian We're tacking the documentation fixes for this in https://github.com/select2/select2/issues/3939.

**Comment by RahamSher** [comment]
Dear @samholmes try this one.
<select class="select2" multiple="multiple" placeholder="Select State">
    <option value="AK">Alaska</option>
     <option value="HI">Hawaii</option>
</select>
and in your script write this.
$( ".select2" ).select2( { } );

**Comment by SudhaVijayakumar** [comment]
This worked for me,
 
$("#e1").select2(
              {
                  matcher: oldMatcher(matchStart),
                  **placeholder: {
                      id: "-1",
                      text: "Select an option",
                      selected:'selected'
                  },**
                  allowClear:true,
                  data:
                  [
                     **{
                         id: -1,
                         text: '',
                         selected: 'selected',
                         search:'',
                         hidden:true
                     },**
                  {
                    id: 1,
                    text: 'Italy',
                    search: "Italy",
                    children:
                    [
                        { 
                            id: 2, 
                            text: 'Sardinia',
                            search: "Italy Sardinia",
                            selected:false
                        },
                        { 
                            id: 3,
                            text: 'Sicily',
                            search: "Italy Sicily",
                            selected: false
                        }
                    ]
                },
                {
                    id: 4,
                    text: 'United Kingdom',
                    search: "United Kingdom",
                    children:
                    [
                        { 
                            id: 5,
                            text: 'Guernsey',
                            search: "United Kingdom - Guernsey",
                            selected: false
                        },
                        { id: 6, text: 'Jersey',
                        search: "United Kingdom - Jersey",
                        selected: false
                        }
                    ]
                }
            ]
        });

**Comment by rsmithlal** [comment]
Thanks for this issue! I was wondering why my select2 was displaying the first option text instead of the placeholder text with a value of null. Adding a blank option solved the issue for me. Thanks!

**Comment by snewell92** [comment]
I just ran into this behavior with an ajax-loaded single selection. I added placeholder and allowClear in the options per the docs, but it didn't work and I was confused. I eventually simply looked at the source code of the docs and saw the original html markup had a blank option tag, so I added that,

Some of the docs (like [this one](https://select2.github.io/options.html#my-first-option-is-being-displayed-instead-of-my-placeholder) ) seem to assume I know about this blank option deal, which I did not (and that particular section wasn't really what I was looking for, so I didn't end up reading that until just now). Reading this thread has enlightened me greatly.

I'm strongly in favor of explicitly adding instructions to include a blank option alongside the introduction of the `allowClear` option in the docs with links to either this issue or some specs spelling why the blank option needs to be there. So much so I might add a PR for it, unless y'all think that's not a good idea.

Although, it seems like [PR 1522](https://github.com/select2/select2/pull/1522) made this change, but it doesn't seem to be reflected in the example or options page anymore...?

Thanks for making an awesome tool that I use a lot! 😀 Much love <3 <3.

**Comment by AllanPooley** [comment]
@rsmithlal Thanks! this seems definitely like the simplest solution

For others, here's an example: 

On your front end (in my case PHP):

```
              <select id="price-max-selector" name="<?php echo PRICE_MAX_TAG ?>">
                <?php foreach($price_range as $price): ?>
                  <option></option>
                  <option value="<?php echo $price ?>" <?php echo $active_price_max == $price ? 'selected' : '' ?>>
                    <?php echo '$' . number_format($price); ?>
                  </option>
                <?php endforeach; ?>
              </select>

```

And then in your JS:

```

  $('#price-min-selector').select2({
    placeholder: 'This is my placeholder'
  });

```

Presto!

**Comment by FeklistovGleb** [comment]
Very bugs component in our application see another components

**Comment by Soni-Sakshi** [comment]
> There is no difference between a `<select>` without any selected options, and a `<select>` where the first option has the `selected` property set. You can confirm this at the following jsbin, which does not use Select2
> 
> http://jsbin.com/mirizuseco/1/edit?html,js,output
> 
> Select2 needs the empty option for the _placeholder_, because the browser does not supply a _placeholder option_ by default. This is expected behaviour, as Select2 is supposed to be a drop-in replacement for a standard `<select>`.
