### ISSUE TITLE
single select in Firefox selects last element by default, place holder with empty option doesn't work

### ISSUE THREAD

**Issue by naeemshaikh27** [select2/select2#3556]
This is something I get only in firefox, for single select element even while having an empty option for placeholder. works fine in chrome and IE

```
<select id="functionalRole" name="functionalRole" required="required"  data-placeholder="Functional Role" style="width: 100%" class="form-control">
<option></option><option value="4">4</option>
<option value="3">3</option>
<option value="1">1</option>
<option value="2">2</option>
<option value="5">5</option>
</select>
```

and Jquery:

```
$('select').not('.notSelect2').select2({});
```

when I inspect the element I can see the last option does not have attribute selected, but select2 shows it as selected.

**Comment by kevin-brown** [comment]
I still need to test this in order to reproduce the issue you are seeing.

> when I inspect the element I can see the last option does not have attribute selected, but select2 shows it as selected.

Select2 relies on the `selected` DOM property, not the `selected` attribute. Unfortunately your browser's development tools only show the state of the `selected` attribute, even though that's not the right one to be checking.
