### ISSUE TITLE
$dropdownContainer memory leak ?

### ISSUE THREAD

**Issue by drekinov** [select2/select2#3559]
Hello we use select2 v4.0 with marionettejs.
select2 is called inside behaviors and on view clean up .select2('destroy') is called

however $dropdownContainer.on('mousedown') event listener is not `off` and GC -

Proposed fix: 

```js
Dropdown.prototype.destroy = function () {
    // Detach mousedown and prevent memory leak
    this.$dropdownContainer.off('mousedown');
    // Remove the dropdown from the DOM
    this.$dropdown.remove();
  };
```

if event is not `off` then heap snapshots show yellow background reference to events['mousedown'].
After some trial and error that leads to `AttachBody.prototype.bind`

**Comment by kevin-brown** [comment]
`$dropdownContainer` is a DOM object generated and managed by Select2. It's the container that gets appended to the `<body>` or right after the selection container, depending on what option you chose.

We were working off of the assumption that it would be removed from the DOM (and eventually garbage collected) when `Dropdown.destroy` was called, but as you can tell that doesn't actually happen. This is because the container itself is never removed from the DOM, but the dropdown within it is.

It's a bug, `AttachBody.prototype.destroy` should be calling `$dropdownContainer.remove()`.
