### ISSUE TITLE
Inline unclosing dropdown

### ISSUE THREAD

**Issue by Krekotun** [select2/select2#3573]
Hi, i want to create select with inline opened options dropdown.
What i mean 
![image](https://cloud.githubusercontent.com/assets/1017140/8648386/f21ca01e-2968-11e5-90bd-cedbff10df3f.png)

How to make this?

Before i tried to prevent closing

```
$tags.on 'select2:close', (e) -> $tags.select2 'open'
```

But i cant click anywhere on the page, because click is prevented by select2 and page jumping to select every time.

**Comment by kevin-brown** [comment]
It's not possible at the moment, and I don't see it happening in the future because of how Select2 has to monitor the dropdown. You can't do this with a standard dropdown, and Select2 emulates a standard one as much as possible.

---

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://github.com/select2/select2#mailing-list
[irc]: https://github.com/select2/select2#irc-channel
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes
