### ISSUE TITLE
Using Adapter to modify dropdown

### ISSUE THREAD

**Issue by MuyBien** [select2/select2#3602]
Hi !
I'm trying to migrate from Chosen to Select2. It's working but I want to modify some aspect of the interface of the dropdown : 
- [ ] put a loup icon in the filter input
- [ ] add options [All, None] to a multiple select
- [ ] change the HTML of a tag when it's added on a multiple select
- [ ] change the clear icon

But I can't get how the adapter are working... I read [this](http://stackoverflow.com/questions/30631024/add-decorator-to-data-adapter-in-select2-version-4-x/30631849#30631849) but I can't see where I have to define all that and where I can't define that I don't want to change how results are made but just append some HTML before...

Can someone show me the way... ? What is the adapter to add content before to the dropdown whithout modifying the results display ? Which adapter I have to use to modify the clear icon ? Which adapter I have to use to modify the tag HTML ?  

Thanks.

**Comment by alexweissman** [comment]
This appears to be a usage question, rather than a bug report or feature request.  Please see our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Usage questions should be discussed on the [forums](https://forums.select2.org) instead.

There is already an open request to update the documentation with a guide on how to implement custom Adapters, and I believe a blog post floating around out there as well.
