### ISSUE TITLE
Selected attribute not getting set when selecting item

### ISSUE THREAD

**Issue by derekisbusy** [select2/select2#3645]
The underlying select>option element is not being updated with the selected="selected" attribute. This was working before so not sure if it's something from a Select2 update or browser update. I have tried this in both Chrome and Firefox and neither gets the selected="selected" attribute set.
![select2-issue](https://cloud.githubusercontent.com/assets/5118781/9065007/4a445e7c-3a9d-11e5-8f77-6f864d80edb6.png)

**Comment by kevin-brown** [comment]
Select2 uses the [JavaScript `selected` DOM property](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement) instead of the HTML `selected` attribute. Generally this shouldn't be an issue, as the option is actually being selected and the value that is sent to the server will reflect that.
