### ISSUE TITLE
Space as a token separator causes pill to not be deleted with backspace

### ISSUE THREAD

**Issue by rnt363** [select2/select2#3658]
here's a fiddle example: http://jsfiddle.net/qj5ob4dh/

just try to click on the select2 and remove the pill using backspace. It will quickly go away and immediately come back again.

Diagnosis: 
In https://github.com/select2/select2/blob/dd9af6893450bbb054ca79546a16bb18198f3e88/src/js/select2/selection/search.js#L127-L135 (Search.searchRemoveChoice), the option is unselected and the input's value is changed to the old text PLUS a space. If the user makes space a token separator then this immediately triggers the text to become a pill again.

**Comment by kevin-brown** [comment]
This is happening due to a few bugs, and they're all coming together to cause confusion.

1. When hitting backspace, we remove the choice and put the text in the text box
2. But browsers will still continue backspacing, removing the last character. So we _add a space to the end_
3. But the tokenizer kicks in and sees a token, so it _tokenizes the choice back_

I think this might be a duplicate, but I'll leave this open until I find it.
