### ISSUE TITLE
Select2 doesn't remove created option on destroy()

### ISSUE THREAD

**Issue by releu** [select2/select2#3666]
The following code creates select with two options:

```
$("select").select2({ data: [ { id: 1, text: "foo" } ] });
$("select").select2({ data: [ { id: 2, text: "bar" } ] });
```

http://jsfiddle.net/z264kv65/

Is it ok?

**Comment by kevin-brown** [comment]
This is a duplicate of another ticket which I wasn't able to find in the minute I spent checking.

---

Yes, this is ok because `data` is supposed to be a _helper option_ for converting an array of data options to the HTML versions. If you need to re-initialize Select2 with new data, you should call `.empty()` first to remove the created options.

**Comment by releu** [comment]
Thanks

**Comment by Xustis** [comment]
Ty so much, all day stuck with this shit, I didn't know what was going on, you could put this in the documentation at https://select2.org/programmatic-control/methods
