### ISSUE TITLE
select2 4.0 brings older list in suggestion with query method and minimumInputLength not taking effect

### ISSUE THREAD

**Issue by dipalm** [select2/select2#3675]
I am in process of upgrading select2 version 3.5.1 to 4.0. I required to use query method for mandate. 

I ran into two specific issues.

1. minimumInputLength is not taking effect
2. When user focus searchbox, The past results are displayed with Searching.. is first item. (If I assign empty result then it resolves the problem but then it displays No results found message)

Please refer to my code snippet below.

 

    var self = this, $view = $(view);

            $.fn.select2.amd.require(['select2/data/array', 'select2/utils', 'select2/data/minimumInputLength'], function (ArrayData, Utils, MinimumInputLength) {

                function CustomData($element, options) {
                    CustomData.__super__.constructor.call(this, $element, options);
                    this.options = options;
                }

                Utils.Extend(CustomData, ArrayData);

                CustomData.prototype.query = function (params, callback) {
                    //callback({ results: [] });
                    self.searchText(params.term);
                    q(ko.unwrap(self.qPromise)).then(function () {
                        var select2data = $.map(ko.unwrap(self.dataSource), function (obj) {
                            obj.id = obj.id || obj.Id + obj.KeyDoc;
                            obj.text = obj.text || obj.Headline;
                            return obj;
                        });
                        callback({ results: select2data });
                    });
                }

                // Decorate after the adapter is built
                Utils.Decorate(CustomData, MinimumInputLength);

                $view.select2({
                    dataAdapter: CustomData,
                    multiple: ko.unwrap(self.multiple),
                    templateResult: ko.unwrap(self.formatFunc),
                    escapeMarkup: function (markup) { return markup; },
                    dropdownParent: $('.' + ko.unwrap(self.containerClass)),
                    placeholder: ko.unwrap(self.placeHolderCaption),
                    minimumInputLength: 1,
                    allowClear: true
                });

            });

Every time I wish to assign new options in suggestion list (no cached no stored)
Please suggest workaround.

Thanks in advanced

**Comment by kevin-brown** [comment]
You are passing `CustomData` into the `dataAdapter` instead of passing the result of `Utils.Decorate()`, which is the decorated class. [This Stack Overflow question might be helpful](http://stackoverflow.com/q/30631024/359284).

---

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://github.com/select2/select2#mailing-list
[irc]: https://github.com/select2/select2#irc-channel
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes

**Comment by dipalm** [comment]
Thanks Kevin. It worked for me. I just required to change  dataAdapter: CustomData to dataAdapter: Utils.Decorate(CustomData, MinimumInputLength).

Thanks again
