### ISSUE TITLE
Can't select the same index in multiple select

### ISSUE THREAD

**Issue by luchengSMU** [select2/select2#3679]
### questions
- As the title says, when I have chosen some results in first search, I can choose **the same index** of the result in second search, and its background color is grey in the second search.
- What confused me is that these two results are completely different.
### pic

![image](https://cloud.githubusercontent.com/assets/8745537/9292944/ceb83090-4446-11e5-9c86-0c144693b2c7.png)
### code

```
$(this).select2({
            ajax: {
            url: ajaxUrl,
            dataType: 'json',
            delay: 500,
            data: function (params) {
                return {
                    q: params.term
                };
            },

            processResults: function (data, page) {
                var i = 1;
                var results = [];
                for(var record in data.object) {
                    var result = {
                        id: i++,
                        text:  data['object'][record][name] + '(' + data['object'][record][id] + ')'
                    }
                    results.push(result);
                }
                return {
                    results: results
                };
            },
            cache: false
          },

          minimumInputLength: 1
        });
```

**Comment by kevin-brown** [comment]
Select2 does id-based matching for results when using AJAX (and, to a lesser degree, data arrays) because it does not have a DOM element attached to it and most people don't return an accurate `selected` property. This means that if two results have the same id, and one of them is selected, the other result will also appear as selected (shown with a grey background).

Right now you are using the index within results (JS engine dependent, `for ... in ...` loops aren't actually ordered in ES5) for the `id`, so selecting the result at index `1` of one search will show index `1` of all searches as selected.

It's not totally clear what you are looking for here, so I've also included the basic debugging questions in case this is a bug.

----

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by alexweissman** [comment]
This appears to be a usage question, rather than a bug report or feature request.  Please see our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Usage questions should be discussed on the [forums](https://forums.select2.org) instead.
