### ISSUE TITLE
Infinite scrolling does not work with custom dataAdapter

### ISSUE THREAD

**Issue by rmscdm** [select2/select2#3683]
In the select2 code, we have this:

```
if(options.ajax != null) {
  options.resultsAdapter = Utils.Decorate(
      options.resultsAdapter,
      InfiniteScroll
  );
}
```

However, when using a custom dataAdapter, we don't use the ajax attribute, so we can't get infinite scrolling.  The workaround I found was to just set ajax to an empty object, so it's truethy and infinite scrolling is added to the results adapter.  My guess is that this was just an oversight, so giving you guys a heads up.  

Thanks for a great control.

**Comment by kevin-brown** [comment]
Totally misread this at first.

Because the only cue we have to check for infinite scrolling support ([for now](https://github.com/select2/select2/pull/3580)) is the `ajax` option, that's what we use for dynamically adding the decorator to the results. So if you are using a custom data adapter which needs infinite scrolling, you should be including the `ajax` option.

**Comment by siccovansas** [comment]
@rmscdm could you give a code example showing how you managed to use `dataAdapter` with infinite scrolling? I'm having a hard time trying to convert [this Select2 3.5 example of infinite scrolling for local data](http://stackoverflow.com/a/25466453/1266303) to Select2 4.0.
