### ISSUE TITLE
Id as text

### ISSUE THREAD

**Issue by chetanra** [select2/select2#3703]
Does select2 control support handling data where Id is text instead of a number?  I can change the server behavior to emit numeric id but want to evaluate this option before going down that route.

Here is the data I am dealing with:
[{id:"f32dc1ad-047b-48a7-8ce0-6910ee92def9",name: "name1"}, {id:"6c3bff47-fd2f-48cc-a3ff-f5a0e70cda9b", name:"name2"]

**Comment by kevin-brown** [comment]
Select2 will actually [coerce all ids to strings](https://github.com/select2/select2/blob/bd6148e39f753ed2880f674a90b42ffe446b893a/src/js/select2/data/select.js#L264) internally, so it's fine if you pass in an id as a string.

We need to do this because the `value` attribute of an `<option>` is a string.
