### ISSUE TITLE
Search does not work properly.

### ISSUE THREAD

**Issue by Leftyx** [select2/select2#3707]
If you go to **Loading array data** [example](https://select2.github.io/examples.html#data-array) and input **i** inside the search box it should select **invalid** but it highlights **duplicate** instead.

I am experiencing the same problems with some of my searches.

**Comment by kevin-brown** [comment]
"duplicate" has an "i" in it, just like "invalid" and "wontfix" (which also appears).

Select2 will display all results that match your search, and it will display them in the order they appear within the `<select>` tree. In the case of array/ajax data, this is the order that the options are passed back. It will also highlight the first result automatically, which is why you are seeing "duplicate" being highlighted.

You can change the order that results appear using the `sorter` option. And you can order the results based on the search term as explained [in this Stack Overflow answer](http://stackoverflow.com/q/31991217/359284#32106792).

**Comment by Leftyx** [comment]
Thanks for your explanation, Kevin.
