### ISSUE TITLE
Multiple pre-selected options not displaying

### ISSUE THREAD

**Issue by nguyening** [select2/select2#3721]
http://jsfiddle.net/9038k4Ls/

Trying to add pre-existing selections programmatically by appending selected ```<option>```s into a ```<select>```, but only the most recent one appears to be showing, though the tagging example in the docs seems to be behaving fine. I've also tried having static options pre-selected in the page, but that also doesn't seem to work. The one difference I can see in the example and mine, is that my autocomplete options are populated via AJAX..

**Comment by kevin-brown** [comment]
If you want to allow for multiple items to be selected, you should use the `multiple` attribute on your `<select>`.

https://jsfiddle.net/d5ywnhk9/1/

The issue was that when you aren't using `<select multiple>`, the browser will only allow for one selection and that _will_ trigger undefined behaviour. This also fixes the issue with dynamically generating the options.

https://jsfiddle.net/d5ywnhk9/2/

Though note that if you generate them after initializing Select2, you are going to need to trigger a `change` event as you are changing the selections and Select2 won't automatically detect it.

https://jsfiddle.net/d5ywnhk9/3/
