### ISSUE TITLE
select2 does not inherit style from parent

### ISSUE THREAD

**Issue by tillahoffmann** [select2/select2#3733]
The select2 suggestions do not inherit the style of the parent but only use the style of the `<body>`. This is a consequence of the suggestions being appended to the tail of the document with absolute positioning. It seems counterintuitive to have the suggestions styled differently from the component itself.

The issue is reproduced here: http://jsfiddle.net/sfp59jf2/1/

**Comment by kevin-brown** [comment]
> This is a consequence of the suggestions being appended to the tail of the document with absolute positioning.

Yup, and as a result there isn't too much we can do about this.

> It seems counterintuitive to have the suggestions styled differently from the component itself.

Select2 doesn't inherit styling from the parent elements because the effort involved is pretty intense, and it's not something we're really interested in implementing.

You can style Select2 using themes (we have ones for Bootstrap and soon one for Material). The full builds of Select2 also support a `containerCssClass` and `dropdownCssClass` option that allow you to add classes to the selection and dropdown of Select2.

**Comment by tillahoffmann** [comment]
Just for completeness, the styles can be inherited from the parent provided that select2 is initialised with `dropdownParent: <DOM or jQuery parent element>` (see a working example here: http://jsfiddle.net/sfp59jf2/2/). This fails if the positioning of the parent element is relative however (see an example here: http://jsfiddle.net/sfp59jf2/3/, #3303).

**Comment by kevin-brown** [comment]
These two tickets are relevant for anyone using `dropdownParent`

- https://github.com/select2/select2/issues/3303 (position bug)
- https://github.com/select2/select2/issues/3526 (documentation)
