### ISSUE TITLE
allowClear with multiple="multiple" triggers a 'change' on every item cleared.

### ISSUE THREAD

**Issue by vans163** [select2/select2#3773]
If you clear a multiple select with say 5 items. change event will trigger 6 times.  1 for each item cleared and once for finalization. This is on firefox.

The problem is line 1714: this.trigger('unselect', unselectData);   apparently unselect triggers the change event.

Possible fixes are comment out this line as it looks useless.  
Another fix is to trigger a custom event called unselect-select2 for example to not trigger the change event.
Another fix is to rewrite change event to be called change-select2 and bind that, but this needs to be propogated throughtout the code.

**Comment by apbeilchick** [comment]
Same thing is happening in IE11.  Also, after invoking the "clear all", the dropdown list appears without adding the select-container--focus class

**Comment by gracedigital** [comment]
Using select2 4.0.3 from CDN.  I've created a multi-select via HTML and initialized it via javascript where multiple options are selected. However if I clear one of the selected options they all clear.  Is there a fix or work around for this?

**Comment by alexweissman** [comment]
This issue is solved as of 4.0.6-rc.0 (see https://github.com/select2/select2/pull/5058#issuecomment-334550960).

**Comment by al** [comment]
Apologies for commenting on such an old issue but I'm seeing the above behaviour on 4.0.13 (select2.full.js), i.e. multiple change events being fired in response to clearing a multiple select.

As this has been marked as resolved I just wanted to clarify whether or not it is considered a bug?

In my scenario I'd just like to submit a form on change and would like to keep that logic generic rather than have to worry about whether the event is coming from Select2 or otherwise have to intercept and handle Select2 specific events.

```js
$form.on('change', 'select, input', (event) => {...})
```

Does it deserve a new issue or have I missed something maybe?

**Comment by Narghor** [comment]
Hello

I have the same problems with the latest release.
Change event is firing for each item cleared ... 

How can we prevent this ?

**Comment by Mckill3r** [comment]
I have the same issue with 4.1.0-rc.0

**Comment by aanish27** [comment]
"select2": "4.1.0-rc.0",
"select2-bootstrap-5-theme": "1.3.0"

I had the same issue and found a workaround by calling the built-in event select:clear which is triggered after clearing along with change ,

https://select2.org/programmatic-control/events
clear event
$('.select2-select').on('select2:clear', function () {
   // data retrieval
})

change event - add this as the first line of code because it still triggers the 'change' on every item cleared 
if($(this).val().length == 0) return;
