### ISSUE TITLE
a is undefined

### ISSUE THREAD

**Issue by ajkosh** [select2/select2#3777]
...ath.random()>>>0),Da=0;function Ea(a,b,c){return a.call.apply(a.bind,arguments)
![screenshot from 2015-09-17 15 48 25](https://cloud.githubusercontent.com/assets/8582472/9930777/b77cf94e-5d53-11e5-825c-e8eb545373b6.png)
this error is coming when i m using select2 inside my form

**Comment by sainag** [comment]
I'm getting the same error for google maps.. Error is from the following js file..
http://maps.google.com/maps-api-v3/api/js/22/5a/main.js 

Do you have any other information about this?

**Comment by kevin-brown** [comment]
You are using the minified version of Select2, and you are running into an issue with it. Because it's minified, all of the debugging names have been removed, which makes error messages mostly useless (except for telling you there is a problem).

Try using the non-minified version of Select2, and adding a comment with the exact error it is giving you there. If you are using a pre-compiler which is bundling Select2 with your other scripts, you may need to disable minification within that.

I'm closing this off for now and I'll reopen it if a more clear error message is posted.
