### ISSUE TITLE
Select2 style is not rendered as expected in Bugzilla GUI

### ISSUE THREAD

**Issue by aileenja** [select2/select2#3787]
Hi,
I've attempted to apply select2 styles and enable search box for bugzilla's component (multiple) selection list in its query page like below:

$(function(){
  $('select#component').select2({
    placeholder: "Select components",
    allowClear: true
  });
});

but some of its styles, dwonward triangle for scrolling for example, aren't rendered as expected.

Is it commonly observed that the styles defined in select2.css cannot override the styles applied by other application - Bugzilla in my case? and how can I overcome it?

Thanks,

**Comment by kevin-brown** [comment]
It's not uncommon for Select2 to have conflicting styles, but usually this is because of overly-broad styles.

---

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://github.com/select2/select2#mailing-list
[irc]: https://github.com/select2/select2#irc-channel
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes
