### ISSUE TITLE
Multiple select : disable already selected options

### ISSUE THREAD

**Issue by Intrepidd** [select2/select2#3788]
It feels really weird that when you select some options in select2, when you press the down key, you may end up on an option that you already selected, and you can't spam key down enter to add all options.

IMHO selected options should be unselectable.

Is this something you'd be interested in ? Maybe not default but actionable with an option ?

I have this monkey patch at the moment if someone is interested :

```javascript
$.fn.select2.amd.require(['select2/results'], function (Results) {
  var oldOption = Results.prototype.option;

  Results.prototype.option = function (data) {
    if (this.$element.is('[multiple]')) {
      if (data.real_disabled === undefined) {
        data.real_disabled = data.disabled;
      }
      data.disabled = data.real_disabled || data.selected;
    }
    return (oldOption.apply(this, [data]));
  };
});
```

**Comment by Intrepidd** [comment]
BTW the change would look like that : 

```javascript
if (data.disabled || data.selected) {
  delete attrs['aria-selected'];
  attrs['aria-disabled'] = 'true';
}
```

instead of 

```javascript
if (data.disabled) {
  delete attrs['aria-selected'];
  attrs['aria-disabled'] = 'true';
}
```

I'd gladly submit a PR with tests and docs

**Comment by kevin-brown** [comment]
> IMHO selected options should be unselectable.

I'm going to have to reject this feature request, as it deviates from the standard expectation of a multiple select. As you can achieve it through a monkey patch, I'm also going to reject the request for a new option for it - that's why we built the decorator and adapter system.

Also, setting `aria-disabled` for a selected option will horribly mess with screen readers.
