### ISSUE TITLE
"Please Enter 1 or More Characters" duplicating itself and persisting

### ISSUE THREAD

**Issue by LinzardMac** [select2/select2#3798]
I have found an anomaly that happens regularly when using Select2 4.0.0 with an AJAX requested data set and multiple select options set to 'true' 

It appears that it happens when I have have a select2 field that already has values set in it and I delete one of those values before typing in it. Clicking in the field with the sole purpose to delete a selected item results in the message to appear but clicking outside of the field or inside the field to enter a new name does not clear it. 

Here is a video screencast of the problem: http://cl.ly/2o2j070Q2d2O
Here is a screenshot of the resulting markup: http://cl.ly/image/3W192x032E32

If this is a bug that can not be fixed, is there a way to simply disable this message?

**Comment by Lindsayanng** [comment]
Just did a little test to see if I could force this by doing the following: 
`var $eventSelect = jQuery("#ee");
$eventSelect.on("select2:unselect", function (e) { jQuery('.select2-container:contains("Please enter 1 or more characters")').remove(this); });`

The goal was to simply always remove that container (which has no defining class/ID btw) by force on the 'unselect' event. I thought this would work because they continually piled up. However in doing this I found that the following error occurs: 

"Uncaught TypeError: b.replace is not a function" 

So it seems that it is TRYING to replace the message container when you unselect an element but for some reason that span persists.

**Comment by Lindsayanng** [comment]
Woops sorry forgot to include my select2 code 

`function select2(){
jQuery("#ee").select2({
	multiple:true,
	ajax: { // instead of writing the function to execute the request we use Select2's convenient helper
		url: myAjax.ajaxurl,
		dataType: 'json',
		quietMillis: 250,
		data: function (termContainer, page) {
				//get selected image ID to send along
				var id = jQuery('.attachment-details').data('id');
				return {
				search:termContainer.term, // search term
				post_id: id, 
				action: 'getUsers', 
				
				};
		}, // end data 
		processResults: function (data) {
						// you should map the id and text attributes on version 4.0
						var select2Data = jQuery.map(data.results, function (obj) {
						return obj;
						}); // end map
						
						return {
						results: select2Data,
						}; 
		}, // end process results
		cache: true 
	}, //end ajax
    templateResult: formatRepo,
    escapeMarkup: function (m) { return m; } // we do not want to escape markup since we are displaying html in results

});`

**Comment by kevin-brown** [comment]
Are you ever destroying Select2 when you are changing items? It looks like Select2 is duplicating the dropdown for some reason, which it shouldn't be doing.

The next step would be to get a jsbin that consistently reproduces the issue, so we can start tracking down where the cleanup isn't happening.

---

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by Lindsayanng** [comment]
Revisiting this issue. I am having a hard time getting a demo that shows my scenario. The only conflict I can see with my own code is that the select2 field exists inside of a backbone view which is re-rendered after the save event is done. Otherwise I don't really see a reason for this happening. 

So destroy isn't really appropriate here because I am not switching views. The <span> tags for the "Please enter 1 or more characters" message appear repeatedly when I'm removing items from the list. Why would I destroy them at any point? They do not appear after saving and the view is re-rendered. 

What steps can be used to reproduce the issue? Currently trying to get code to reproduce in a fiddle. 
What is the bug and what is the expected outcome? The <span> that contains the minimum character message is removed from the dom when it is not needed. 
What browser(s) and Operating System have you tested with? Mac Yosemite & Mavericks Safari, Firefox, and Safari (all most current versions of each)
Does the bug happen consistently across all tested browsers? Yes
What version of jQuery are you using? And what version of Select2? It seems this system (WordPress) uses jQuery v1.11.3  and select2 is 4.0
Are you using Select2 with other plugins? No.
