### ISSUE TITLE
Issue - AllowClear on <input> - HTML-tag

### ISSUE THREAD

**Issue by flowbeh** [select2/select2#3802]
Hello,

I'm currently occurring a strange issue concerning the reset of a select field, initialising the select2() on an `<input>` - html tag.

My current code:

``` html
<form ...>
    <input type="text" id="foo" />
</form>
<script type="text/javascript">
$('#foo').select2({
    data:data,
    placeholder: 'Testselect',
    allowClear: true
});
</script>
```

Hitting now the clear-button, select2 will reset the internal variable but still keeps on showing the option selected before (which is wrong). Only after hitting the "x" - button a second time, it'll reset the input value. Initialising the select2 on a `<select>` - html tag, the value will be reset on the first hit as it worked in the previous versions.

Someone else experiencing this problem?

Thank you & best regards!

**Comment by bphtmg** [comment]
I'm also having this issue.  I've created a fiddle to show the behavior:

https://jsfiddle.net/Lguh3Lzn/

`#input1ex` shows the behavior that I believe flowbeh is describing; you have to hit the "x" to dismiss the selected item twice for the placeholder to reappear.  (The `.val()` of the control is correctly set to the placeholder's id after clicking the "x" only once, but the selected item's visual representation remains.)

`#input2ex` shows something strange that I came across when attempting to address the first issue.  Adding a "selected: true" to the data item causes the "x" to work as expected (dismissing the item after a single click, and showing the placeholder), but the option can never be re-selected.  This is possibly by design, if `selected: true` is not a valid property for the data items, but it does initially show that item as selected in the dropdown.  `.val()` does not return the correct value initially, but does return the placeholder's -1 id after clearing the item.

`#selectex` shows the same example using a standard `<select>` and `<option>` tags, which works as expected.

Any input on this issue would be appreciated... thanks!
