### ISSUE TITLE
Uncaught error when calling .select2() on widget update in WordPress widget.php

### ISSUE THREAD

**Issue by twoelevenjay** [select2/select2#3810]
`Uncaught query function not defined for Select2 s2id_widget-daily_deal_widget-__i__-select_product`

displays when calling .select2() on widget update in WordPress widget.php

```javascript
jQuery(document).ready(function($) {
	$('.daily_deal_widget').select2();

	$(document).on('widget-updated widget-added', function(){
		$('.daily_deal_widget').select2();
	});
});
```

Also asked here: http://wordpress.stackexchange.com/questions/204507/uncaught-error-when-calling-select2-on-widget-update-in-wordpress-widget-php

**Comment by markussc** [comment]
Had the same issue whenever calling .select2() on a previously initialized select2 object. Workaround is to destroy (.select2("destroy")) element before re-initializing.

**Comment by kevin-brown** [comment]
The problem is that you are using a class selector and an older version of Select2. In Select2 3.5.x and below, all classes from the original select were copied to the `<div>` for the Select2 container. So your class selector is picking up the original `<select>`/`<input />` boxes as well as the Select2 containers and this is causing problems.

I'd recommend using a more specific selector instead. [Here's a related Stack Overflow question.](http://stackoverflow.com/q/33106176/359284)
