### ISSUE TITLE
Placeholder cutting text off when initialized inside hidden element

### ISSUE THREAD

**Issue by brunoDegaspare** [select2/select2#3817]
I can see that this is an old issue that still has not been fixed.

I am using the latest version and still have this issue. I added the following css however it breaks select2 on IE.

```
.select2-container .select2-search--inline {
    float: none !important;
}
```

Any solution for this case?
![screen shot 2015-10-07 at 15 12 28](https://cloud.githubusercontent.com/assets/7714748/10339968/db2283a2-6d05-11e5-9bc6-64f375de4c34.png)

**Comment by kevin-brown** [comment]
This is _usually_ an issue with Select2 not properly setting the width somewhere.

I also thought this had a duplicate that was already open, but I wasn't able to find it after a quick search.

**Comment by vakopian** [comment]
Here is a jsfiddle to reproduce this (including a workaround): https://jsfiddle.net/agq08j5z/1/
Notice that the control is hidden initially (`display:none` on the parent div). So it seems that if the control is hidden the internal input's width is not set correctly by select2. If you remove `display:none` everything works.

**Comment by catmeme** [comment]
I'm experiencing this bug when initializing select2 in a hidden tab. I'm not sure if this issue is related.

**Comment by tanloverluke** [comment]
@vakopian thank you VERY MUCH the workings of your workaround, though I had to take the width of an input field above the select2. strange but it works anyway.

**Comment by alexweissman** [comment]
There are now two competing proposed solutions for this bug:

- #4776
- #4898

These need someone to review them.

**Comment by vluzrmos** [comment]
My workaround was trigger the event `change` when the `select` becomes visible:

```javascript
//please use your own selector/context....
$('select').trigger('change');
```

**Comment by callmejed** [comment]
This still seems to be an issue, at least for me. I did notice that the .select2-search__field **parent** has a float: left, that when disabled fixes the width issue. Not sure if that contributes. I'm not really sure what it's accomplishing; I didn't dive into that part too deeply.

**Comment by sp193** [comment]
This issue seems to be changing slightly over the years. Or we are observing the effects of multiple problems.

For me, I have issues with select2 assuming the wrong width if belongs to a hidden parent: https://jsfiddle.net/NozomiTypeR/6pLzy1ak/44/
In this fiddle, there are 2 similar select2 controls. The working one is always visible, while the hidden one can be revealed with the button.
We can get slightly different behaviour if you switched jQuery versions. For my own project, I need to use jQuery v1.12.4, which is why it is currently set to use v1.9.1. With jQuery 1.x, the width becomes 100, while it is 0 when jQuery 3.3 is selected.

As for why: up to [this jQuery Github PR](https://github.com/jquery/jquery/pull/3741), jQuery had a problem with computing the width of elements under specific conditions. In this example, it fails to compute the width of the element because the jQuery outerWidth (similar for innerHeight, innerWidth, height, width, outerHeight and outerWidth) function will call the width cssHook, which in turn calls getWidthOrHeight(). getWidthOrHeight() may obtain a width in %, which is then returned as it is. The width function does not check what was returned and passes it through parseFloat, which results in the 100% becoming just 100.
In newer jQuery versions, this bug was solved, but the width of such a hidden element becomes 0.

Perhaps this was why #3292 could have worked, while yet the author of #4898 disagreed (the jQuery PR was still recent back then).

By the documentation of jQuery's outerWidth function(), it can obtain the width of a hidden element if it is hidden, by temporarily unhiding it. However, this does not work if the element is hidden because of its parent.

I don't understand how #4776 is related to this. But now that jQuery can return a 0 for the width of hidden elements, #3292 should work.

**Comment by sp193** [comment]
I tried out the solution suggested by #3292 and it did not seem to restore the normal behaviour fully. I get a select2 control that is at least long enough for the placeholder text, but it does not fill up all available space (like the normal version does).

It could be because _placeContainer() will place a copy of the container with a width set to "auto", due to jQuery returning a 0. So my solution is to change the "auto" returned by _resolveWidth() to "100%", along with the suggested change from #3292.

**Comment by lvalladares** [comment]
This is still happening on 4.0.13, i've 4 selects in the same form and happens only in some of them randomly... I couldn't find a pattern

**Comment by msykes** [comment]
I am also experiencing this behaviour. If the element is hidden and not visible due to any parent being hidden before initializing select2 on it, then the width of the input field is 0, i.e. a sliver.

For me, the workaround is making sure all offending parents are visible by showing them just before select2 and hiding hem again.

**Comment by Rikaelus** [comment]
> My workaround was trigger the event `change` when the `select` becomes visible:
> 
> ```js
> //please use your own selector/context....
> $('select').trigger('change');
> ```

This solution worked for me. Not ideal and it's only placeholders, but I'm in perfectionist mode.

**Comment by rbnzdave** [comment]
> > My workaround was trigger the event `change` when the `select` becomes visible:
> > ```js
> > //please use your own selector/context....
> > $('select').trigger('change');
> > ```
> 
> This solution worked for me. Not ideal and it's only placeholders, but I'm in perfectionist mode.

I hadnt realised this was why one of my placeholders was fine and the other wasnt. I'd trigger change after loading the data into the modal bootbox, whereas in the "new" mode of it there was no existing selection so didnt fire change.
Other observations were that if I made a selection (using multi select but didnt matter how many things i selected) _and then cleared it_ it would display the placeholder correctly.
 -none of the previous style fixes worked for me.
-This solution worked exactly as needed.
