### ISSUE TITLE
Knockout.js-Integration

### ISSUE THREAD

**Issue by abazanvillanueva** [select2/select2#3819]
https://github.com/select2/select2/wiki/Knockout.js-Integration

Does anyone have a wording jsfiddle of it?
Thanks

**Comment by kevin-brown** [comment]
The old knockout.js integration was required to get Select2 3.x to work.

Now in 4.x, it's mostly not needed because Select2 uses a `<select>` as the element that holds the data.

---

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://github.com/select2/select2#mailing-list
[irc]: https://github.com/select2/select2#irc-channel
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes
