### ISSUE TITLE
multiple select: catch and override enter keyup event

### ISSUE THREAD

**Issue by leizard** [select2/select2#3852]
Hi, everyone. 
In select2 multiple, the enter keyup triggers the dropdown selection, which I don't need. I want to catch the enter keyup event and submit the value when user press enter. I tried this:

```
$('select2-search-field > input.select2-input').on('keyup', function(e) {
   if(e.keyCode === 13) 
      // do something
});
```

but not working. How can I archive it ?
Thank you.

**Comment by alexweissman** [comment]
This appears to be a support question, rather than a feature request or bug report.  So, I am closing it.  

If you have discovered an underlying bug causing this problem, please search the open issues and comment there (or if an issue specifically about the underlying bug is not already open, you may open a new one - just make sure it identifies the **underlying bug**).

If, on the other hand, this is simply a matter of using Select2's features properly, it should be discussed on the [forums](https://forums.select2.org) instead.
