### ISSUE TITLE
 translated into many languages question

### ISSUE THREAD

**Issue by feifeiiiiiiiiiii** [select2/select2#3869]
I want to translated language in ['zh-CN','en'], when choose 'en' use 'en' language and other use 'zh-CN' language, but I found Only one language effective, i look up the source and found code:

```
    $.extend($.fn.select2.defaults, $.fn.select2.locales['en']);

``` 

pls help me how solve it? (select2 version: 3.5.2)

**Comment by kevin-brown** [comment]
Any version of Select2 before 4.0.0 can only support one active language at a time. This isn't something that will be changed in the foreseeable future.

Select2 4.0.0 allows you to specify the language with the `language` option during initialization, which is slightly better.

**Comment by lopis** [comment]
I know this issue is old as balls but I had this exact same issue and the solution was quite simple... For anyone like me stuck in super old software, you need to include the JS files for the locales you want (except for english, that one is pre-loaded) and then do this when your app changes language:

```
          $.extend($.fn.select2.defaults, $.fn.select2.locales['en']); // set the language files
          $('select[data-select-search]').select2(); // restart select2.
```
