### ISSUE TITLE
ajax got response but result not show in select2

### ISSUE THREAD

**Issue by bobby38** [select2/select2#3879]
i use select2 to retrive a list in json from my database... i see response and filter result in firebug but i can not have any sesult show in my drop box

my jquery look like that:

```js
$('#country2').select2({
    ajax: {
    url: "{{path('report-filter-list', {'type': 'country'})}}",
    dataType: 'json',
    delay: 250,
    multiple:true,
    data: function (params) {
    return {
    q: params.term, // search term
    page: params.page
                        };
                    },
                    processResults: function (data, page) {
                        return {
                            results: data.items
                        };
                    }
                },
                minimumInputLength: 3,
              
            });
``` 

my select: 

```html
<select  class="input-xxlarge"  multiple="multiple" id="country2" name="country[]">
```

and the response:

```json
[{"text":"American Samoa","id":"AS"},{"text":"Canada","id":"CA"},{"text":"Central African Republic","id":"CF"},{"text":"Dominican Republic","id":"DO"},{"text":"Holy See (Vatican City State)","id":"VA"}]
```

anything i do wrong...was working in 3.5.4 but input hidden not post on submit

**Comment by kevin-brown** [comment]
Your `processResults` method should be

```js
processResults: function (data) {
  return {
    results: data
  }
}
```

Because your response is giving back an array instead of an object with an `items` attribute.

----

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://github.com/select2/select2#mailing-list
[irc]: https://github.com/select2/select2#irc-channel
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes
