### ISSUE TITLE
Provide original event when relaying select2 events

### ISSUE THREAD

**Issue by rockshandy** [select2/select2#3885]
I was hoping to have a way to find the last key code when listening for 'select2:closing', but I couldn't figure out how to get it cross browser. For Chrome and IE I see some global `event` variable is set with the last event, but not in Firefox. It would be great if the original event was attached to the triggered select2 event's parameters or something.

My use case was to detect if select2 was closed by clicking away, or hitting the 'esc' key.

**Comment by kevin-brown** [comment]
The event will be attached in the few cases where we have a reference to it. You will be able to access it as `event.params.originalEvent`. Not all events will have this, because the Select2 internals are abstracted away from the DOM events in many places.

We're going to _slowly_ get better at this.
