### ISSUE TITLE
Autocompletion problem??

### ISSUE THREAD

**Issue by harrywang** [select2/select2#3891]
Hi,

When I tried the example, I type "d" for state and Nevada was highlighted and I was expecting "Delaware" be highlighted. Same for "w", which highlights "Hawaii" instead of "Washington". Is there a way to change this behavior?

Thanks!!

**Comment by kevin-brown** [comment]
This is the expected behaviour of Select2, it sorts results in the order that they are given (DOM order or AJAX order). You may be interested in the following Stack Overflow questions, depending on what you are looking for:

- [Select2 - Sorting results by query](http://stackoverflow.com/q/31991217/359284#32106792)
- [Select2 search - match only words that start with search term](http://stackoverflow.com/q/31571864/359284#31575725)
