### ISSUE TITLE
After all data has been downloaded, why make more ajax requests?

### ISSUE THREAD

**Issue by divyangbw** [select2/select2#3927]
Hey there, a simple question regarding 4.x. I'm currently using AJAX to load data by pagination. Assuming I have a dataset of 100 items, and all those 100 items are downloaded, why would searching then make server requests? Assuming all data has been loaded, to reduce server stress, shouldn't select2 pick up the filtering? If this is not possible in this version for whatever reason, ideas on how I can achieve this?

**Comment by morrow95** [comment]
Just because your data does not change (the same 100 results) doesn't mean others won't.  For instance, in my use case we retrieve results from our database which is ALWAYS changing, therefore, the results can be different every time.

**Comment by divyangbw** [comment]
I agree @morrow95. I'm trying to figure out of there is some option or if I need to implement custom caching myself. 

To answer you question though, my data will be changing not-so-frequently, but will be changing nevertheless. So not in this session, but maybe 30 minutes later, something might have changed. In some cases, I'd also have pretty large data-sets (>20,000) so loading all that data in one go....bad idea, even from the backend prospective. So can't really retrieve just once.

My goal is, for the current session (which usually last not more than a couple of minutes), keep loading data normally in pages. However, once all the data is loaded (more useful in cases where the data is small like 20 or 30 options), then use select2's matcher (even if a custom implementation) instead of making a request for each character or couple of characters typed. I do have a couple of ideas, but want to make sure I'm not missing out on something select2 4.0 already does, plus not sure how efficient it would be yet :grimacing: .

**Comment by kevin-brown** [comment]
> I'm trying to figure out of there is some option or if I need to implement custom caching myself.

Select2 does not support this out of the box, but it can be done by implementing a custom data adapter (or a decorator for the standard AJAX one).

Part of the issue is that, as previously mentioned, Select2 cannot guarantee that the state of the data has not changed between requests. The other issue is that Select2 cannot guarantee that all results have been returned, and as such it will never know that there are no more results in the query.

**Comment by divyangbw** [comment]
@kevin-brown I see. Makes sense, thanks :)

**Comment by mkoch42** [comment]
@kevin-brown Trying to figure out how to implement custom data adapter to do what @divyangbw is asking, with one twist.  Rather than caching the results, the goal is to just reload the page that we were on when we last selected something in the select2 and have the correct option we last selected pre-selected when that page is returned.

So if you have 20 pages and the user has scrolled down to page 3 and then selects an option from that page, the goal would be to cache that we are on page 3 of the results and that option with value=X had been selected.  This way when the select2 is clicked on the next time, it would request page 3 and pre-select the option with value=x. 

If you can steer me towards solving this or a thread that could help guide me in the right direction that would be super helpful.

**Comment by alexweissman** [comment]
Kevin probably won't respond to you, based on his activity history.  Have you seen https://bojanv91.github.io/posts/2017/10/extending-select2-with-adapters-and-decorators?  Seems like we could really use some proper docs for the adapter/decorator plugin system.
