### ISSUE TITLE
placeholder when using data

### ISSUE THREAD

**Issue by p2media** [select2/select2#3939]
If you specify dynamic options via `data` select2 won't respect the `placeholder`

Here is my Testcase:

``` js
var myData = [{
    id: 0,
    text: '1. Option',
}, {
    id: 1,
    text: '2. Option',
}, {
    id: 2,
    text: '3. Option Group',
    children: [{
        id: 20,
        text: '3.1. Option',
    }, {
        id: 21,
        text: '3.2. Option',
    }, {
        id: 22,
        text: '3.3. Option',
    }],
}, {
    id: 3,
    text: '4. Option',
}];

var $s = $('<select />');
$('body').append($s);

$s.select2({
    data: myData,
    placeholder: 'my placeholder',
});
```

Here is a [JSFiddle](https://jsfiddle.net/9wpdnmvf/1/)

I'm using `jQuery 1.11.3` and `Select2 4.0.1-rc.1` with `grunt-contrib-uglify ~0.9.2`

**Comment by mayankiiitm** [comment]
You need to put an empty option tag, so in your case, push an element to your array like {id:'',text:''}.

check [JSFiddle] (https://jsfiddle.net/9wpdnmvf/2/)

**Comment by p2media** [comment]
It worked, thanks!

Can anyone add the `documentation` label to this issue?

**Comment by kevin-brown** [comment]
_Technically_ this is covered in the documentation under "[My first option is being displayed instead of my placeholder](https://select2.github.io/options.html#my-first-option-is-being-displayed-instead-of-my-placeholder)", though it's not really complete and it doesn't mention the `data` option at all.

Pull requests to improve the documentation are always appreciated.

**Comment by alexweissman** [comment]
This has been clarified in the new docs, and in fact we have an entire new chapter on placeholders: https://select2.org/placeholders
