### ISSUE TITLE
Collision of multiple versions - how to isolate our copy?

### ISSUE THREAD

**Issue by psprindys** [select2/select2#3942]
Hi there,

Background information. We create and distribute WordPress plugins and we use Select2 in our UI. Our users install those plugins on their websites by themselves together with themes and plugins developer by other developers.

Now, we run into an issue multiple times when we loaded 4.0 (which supports ajax search on select elements) and some other theme/plugin loaded 3.5 which does not support ajax and this breaks our UI with "Uncaught Error: Option 'ajax' is not allowed for Select2 when attached to a <select> element".

The problem is that we have no control on what other themes/plugins our users install and what version of Select2 those themes/plugins use.

We tried to load the 4.0 version before all other scripts as well as after all other scripts, it looks like 3.5 does something that prevents 4.0 from overriding it while it overrides 4.0 if loaded later.

What would be the best way to isolate our version of Select2 and our UI scripts?

Thanks!

**Comment by kevin-brown** [comment]
It should be possible (but not necessarily easy) to isolate Select2 4.0.0. It is nearly impossible to isolate older versions because they rely on global variables, while Select2 4.0.0 is actually pretty self-contained (with some exceptions).

I'm guessing you are running into a situation similar to the following jsbin: http://jsbin.com/jejawesoro/1/edit?html,js,output

You can see both Select2 4.0.0 and 3.5.2 are being loaded in the same bin, and 3.5.2 is winning the battle.

But this can be fixed by taking a reference to `$.fn.select2` after you load the plugin. You can then either call this function directly (using `.call()`) or re-set the reference when you need it. I would _personally recommend_ calling the function directly, so other plugins aren't breaking because of you.

You can see this in action here: http://jsbin.com/pelulolime/1/edit?html,js,output

And using the function directly has the benefit of both Select2 3.x and 4.x working on the same page without any problems: http://jsbin.com/kosolelamo/edit?html,js,output
