### ISSUE TITLE
Could I use tags with duplicate value?

### ISSUE THREAD

**Issue by thearabbit** [select2/select2#3958]
Could I use tags with duplicate value?
```js
type 1: theara
type 2: rabbit
type 3: theara
```
Please help me.

**Comment by kevin-brown** [comment]
This is not possible out of the box, because Select2 doesn't allow for duplicate tags to be created, but [it is possible with some extra code](https://github.com/select2/select2/issues/1002).

----

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://github.com/select2/select2#mailing-list
[irc]: https://github.com/select2/select2#irc-channel
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes

**Comment by elyasmv** [comment]
https://stackoverflow.com/a/68540536/8705204
