### ISSUE TITLE
.select2("val", "somevalue") not working on ajax

### ISSUE THREAD

**Issue by Jean-PaulvHouten** [select2/select2#4035]
Hi there,

I am using ajax to load all the options of the dropdown.
After that I am using the code $('#@Html.IdFor(model => model.Visitor.Nationality)').select2("val", data.Nationality); to select a nationality based on the data that is posted in the model.
Unfortunately this does not work when using AJAX, it does work on pre-defined select lists.

**Comment by kevin-brown** [comment]
This is because `.select2('val', some_value)` is [the same as](https://github.com/select2/select2/blob/bc1996417041d9b6131bd8c2ba911984c7b6f2d9/src/js/select2/core.js#L487) `.val(some_value).trigger('change')`. As a result, you must have an `<option>` in your `<select>` that has the matching `value` in order for Select2 to respond, it won't automatically create an `<option>` for you.

You can read more about this in [this Stack Overflow answer](http://stackoverflow.com/q/30316586/359284#30328989).

**Comment by Jean-PaulvHouten** [comment]
It works now, but I stumbled upon the next issue, whenever I use this, for some reason it open the "please type in 1 character to search" in the left top corner.
This only happens on a multi select version, not on the normal ones.
