### ISSUE TITLE
how to bind select2 to a  dynamically dom

### ISSUE THREAD

**Issue by yuanming3936** [select2/select2#4043]
eg:  Creates a new select node ,  how bind select2

**Comment by kevin-brown** [comment]
As long as the element exists within the DOM, you can initialize Select2. You can't initialize Select2 on a detached DOM node because it creates new elements outside of the `<select>`.

---

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://github.com/select2/select2#mailing-list
[irc]: https://github.com/select2/select2#irc-channel
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes
