### ISSUE TITLE
New option text is concatenated to old option text on option change

### ISSUE THREAD

**Issue by jasrys** [select2/select2#4078]
Hi - An old selected option's text does not seem to be removed upon selection of a new option and as a result, the new selected option's text is concatenated to the old selected option's text.

Here's a fiddle:  http://jsfiddle.net/aecoa3ok/

1. search for 'opt' and select 'Option 1'
2. search again for 'opt' and select 'Option 2'
3. click 'show text'

Expected result:  alert with 'Option 2' text shown
Actual result: alert with 'Option 1Option 2' text shown

**Comment by kevin-brown** [comment]
Calling `$('select').text()` does not give the text of the selected option, it gives the text of all options contained within the `<select>`. The only reason why it gives "Option 1" after selecting the first option is because there is only only `<option>` tag under the `<select>`.

You can get the text for the selection option using `$('select option:selected').text()`.

http://jsfiddle.net/aecoa3ok/1/

**Comment by jasrys** [comment]
Aha!  Thanks for the quick and helpful response.
