### ISSUE TITLE
Ability to edit tags on click

### ISSUE THREAD

**Issue by finkelm** [select2/select2#4083]
As above, it would be nice to have the ability to edit tags on click or the ability to drag and drop the order of tags (should order be important).

**Comment by kevin-brown** [comment]
> or the ability to drag and drop the order of tags (should order be important)

There is already a ticket for this at https://github.com/select2/select2/issues/3004.

**Comment by stevdom** [comment]
Hi,

I recently [a plugin](https://goodies.pixabay.com/jquery/tag-editor/demo.html) with the expected behavior (both: edit-on-click and drag-n-drop), still I'd like to stick up with _select2_ rather than requiring X additional plugins for each use-case.

Has anybody come up with a solution based on _select2_ (with or without changes within base source)?
