### ISSUE TITLE
How override default "text" key to custom key?

### ISSUE THREAD

**Issue by alexpts** [select2/select2#4086]
```javascript
{ id: 4, text: 'wontfix' }  ->  { id: 4, name: 'wontfix' }.
```

**Comment by kevin-brown** [comment]
The docs are pretty terrible about recommending how to correct this issue.

The _preferred_ way is to fix change the property names at the data source, so they match the `id` and `text` that Select2 is expecting. We understand that this isn't always possible, which is why we have a few hooks where you can do the mapping on the client side.

This is covered briefly in the 4.0.0 announcement:
https://select2.github.io/announcements-4.0.html#changed-id

_I'm going to mark this as a documentation issue._

**Comment by alexpts** [comment]
May be create options for this keys?

```javascript
$.fn.select2.defaults.set("pk-prop", "id");
$.fn.select2.defaults.set("text-prop", "text");
```
