### ISSUE TITLE
I can not create a tag if the text is part of the selected tag

### ISSUE THREAD

**Issue by alexpts** [select2/select2#4093]
Example - http://codepen.io/alexpts/pen/QyOyWm (3) , select form.

**Comment by kevin-brown** [comment]
I was able to reproduce this with the following codepen: http://codepen.io/anon/pen/qbVMob?editors=101

1. Open the dropdown
2. Type "some"
3. Hit the enter key

Note that this is only an issue when selecting the tag using the keyboard, using a mouse does not cause any issues.

After stripping this down it's happening because you are hiding any selected elements, but Select2 is still trying to highlight them. Select2 will only select a result on "enter" if it is highlighted. If there are no highlighted results (or the highlighted result has already been selected), nothing will happen.

**Comment by andenq** [comment]
Is there a workaround for this? Maybe disable the dropdown completely?
