### ISSUE TITLE
select2:selecting event (get clicked value)

### ISSUE THREAD

**Issue by 440459012** [select2/select2#4099]
can you add functionality to get the current clicked value in :selecting event, not in :select

**Comment by kevin-brown** [comment]
You should be able to get the current clicked value using

```js
evt.args.data.id
```

Because the arguments for preventable events are passed in as the `.args`.

---

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://github.com/select2/select2#mailing-list
[irc]: https://github.com/select2/select2#irc-channel
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes

**Comment by JohnLiTangshan** [comment]
I also get the same issue, I can't get the value by  evt.args.data.id, there is no args property in the events.
Thanks
