### ISSUE TITLE
Not able to clear the value on clicking the cross button.

### ISSUE THREAD

**Issue by himanshu0a** [select2/select2#4135]
I am using the 4.0 version of Select2 with single select option and the issue I am facing is that if I try to clear the selection using the cross sign the value does not gets cleared.Earlier on clicking the cross sign it use to open the select2 drop down but that i have handled butstill the drop down value does not gets cleared.

Below is the code

 $("#SelectedPrimaryClaimIds").select2(
           {
               tags: true,
               placeholder: 'Please Select',
               minimumInputLength: 0,
               allowClear: true,
               multiple: false,
               ajax: {
                   type: "GET",
                   url: '/Matter/GetPrimaryClaimList',
                   dataType: 'json',
                   contentType: "application/json; charset=utf-8",
                   //delay: 250,
                   data: function (params) {
                       return {
                           searchTerm: params.term
                       };
                   },
                   processResults: function (data) {

                       return {
                           results: data
                       };
                   }
               },
               formatResult: contractFormatResult,
               formatSelection: contractFormatSelection,
               escapeMarkup: function (m) { return m; },
               createTag: function (tag) {
                   return {
                       id: '*' + tag.term,
                       text: tag.term,
                       isNew: true
                   };
               }
           }).on("select2:unselecting", function (e) {
               $(this).data('state', 'unselected');
           }).on("select2:open", function (e) {
               if ($(this).data('state') === 'unselected') {
                   $(this).removeData('state');
                   e.preventDefault()
                   var self = $(this);
                   setTimeout(function () {
                       self.select2('close');
                   }, 1);
               }
           });
Please suggest a quick solution.

**Comment by kevin-brown** [comment]
More than likely you're forgetting the empty `<option></option>` tag for the placeholder, and that's why it isn't working.

---

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://github.com/select2/select2#mailing-list
[irc]: https://github.com/select2/select2#irc-channel
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes

**Comment by himanshu0a** [comment]
I have tried the solution provided but failed to find a soltuon .

Moreoverwe are using DropDownList for which below is the code
<td>@Html.DropDownListFor(m => m.SelectedPrimaryClaimIds, Model.PrimaryClaimList, new { @class = "customtext" })</td>

**Comment by himanshu0a** [comment]
I am able to clear the values in IE9 but not in IE11 or other browser such as FireFox and Chrome.

**Comment by kevin-brown** [comment]
There's a good chance that this issue is specific to what you're doing with .NET/MVC considering others have had similar configurations without many issues. All signs are still pointing to there not being an `<option>` for the placeholder.

[DropdownListFor default value](http://stackoverflow.com/q/7229626/359284)
