### ISSUE TITLE
Select2 does not work in Meteor/Bootstrap Modal

### ISSUE THREAD

**Issue by domschiener** [select2/select2#4137]
I have been trying for some time now to get select2 to work with Meteor. I am basically getting data from a MongoDB collection and then creating a profile with that data. A user can then click on "Delegate", which makes a modal popup where the select2 box is. Here you can see the HTML code: https://github.com/domschiener/liquid-democracy/blob/master/app/client/templates/dashboard/delegates/delegates.html#L64 and here I'm declaring the select2 box inside the modal: https://github.com/domschiener/liquid-democracy/blob/master/app/client/templates/dashboard/delegates/delegates.html#L103

Here is the Javascript code where I'm enabling select2 https://github.com/domschiener/liquid-democracy/blob/master/app/client/libraries/dashboard/delegates/delegates.js#L1

The weird thing is that it seems to work fine on localhost (meaning that the select2 box works locally), but when I deploy the app on my server the select2 box does not render and just remains in the old html/css. 

Anyone have a suggestion of what Im doing wrok?

**Comment by domschiener** [comment]
Also, I have tried certain hacks as suggested here http://stackoverflow.com/questions/18487056/select2-doesnt-work-when-embedded-in-a-bootstrap-modal but none of them helped solve the problem.

**Comment by kevin-brown** [comment]
The fix for Select2 within a Bootstrap modal is usually https://github.com/select2/select2/issues/600#issuecomment-102857595.

Any issues between production/local deployments are outside of the scope of Select2, I'd recommend checking your JavaScript console and making sure Select2 is actually being loaded.

----

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://github.com/select2/select2#mailing-list
[irc]: https://github.com/select2/select2#irc-channel
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes
