### ISSUE TITLE
formatNoMatches doesn't work

### ISSUE THREAD

**Issue by alfredopacino** [select2/select2#4163]
Hi, I found tons of thread about this question, maybe it's time to get a definitive answer (that I haven't).
The problem is add a link to the formatNoMatches text that shows a form for adding new items.

I'm stuck at beginning of this problem:  **formatNoMatches** doesn't work, with this code I still see "No result found", what am I doing wrong? maybe the option is changed in select2 v4?

```
$("#sel").select2({
     formatNoMatches: function (term) {
            return 'No user matches "' + term + '".<br/><span class="link">Click&nbsp;here</span>';
        },
        minimumInputLength: 0,
    });

```

**Comment by kevin-brown** [comment]
`formatNoMatches` has become the `noMatches` key of the `language` option in 4.0.0, as we have moved that to a new localization section of the options.

You might want to implement your message using tagging though, so you can use a custom template to control what happens when the link is clicked.

http://stackoverflow.com/q/14577014/359284#30021059

**Comment by alfredopacino** [comment]
Ok this is my simple select2 init, I get an empty string <span></span> in case of no results

```
    $("#decidingbody").select2({
       ajax: {
            url: "/api/dashboard/chambers",
            dataType: 'json',
            delay: 250,
            data: function (params) {
                return {
                    q: params.term,
                };
            },
            processResults: function (data, params) {
                console.log(data)
                var ret = $.map(data.docs, function (obj) {
                    obj.id = obj._id;
                    obj.text = obj.name;

                    return obj;
                });
                return {
                    results: ret
                };
            },
            cache: true
        },
        tags:true,
        createTag: function (params) {
            return false
        },
        templateResult: function (data) {
            var $result = $("<span></span>");
            $result.text(data.text);
            return $result;
        },
        language: {
            noResults: function() {return "No results <a href='http://google.com'>Add new value</a>"; }
        },
        escapeMarkup: function (markup) {
            return markup;
        },
        minimumInputLength: 0
    });

```

**Comment by alfredopacino** [comment]
It looks like I solved simply removing tags:true, not sure it's a bug or it's just my faulty code.
For tagging I just set the attr "multiple" in the select.

**Comment by Xerotherm1c** [comment]
>         tags:true,
>         createTag: function (params) {
>             return false
>         },
>         templateResult: function (data) {
>             var $result = $("<span></span>");
>             $result.text(data.text);
>             return $result;
>         },
>         language: {
>             noResults: function() {return "No results <a href='http://google.com'>Add new value</a>"; }
>         },
>         escapeMarkup: function (markup) {
>             return markup;
>         },

Thank you @antonioaltamura for your detailed code example. By using the `language` and `escapeMarkup` options, I was able to inject html as desired, but using `tags: true` even in conjunction with your `createTag` override breaks (perhaps prevents) the desired effect when using `noResults`.

Because `tags: true` is not an option (as explained above), how can I capture the currently entered search term that is prompting the `noResults` `li` to be displayed? I tried adding a `term` parameter (like so: `noResults: function(term) { ... }`) but I receive an error that `term` is undefined.
