### ISSUE TITLE
Select2 closes immediately if minimumResultsForSearch is not met

### ISSUE THREAD

**Issue by jonathan-dejong** [select2/select2#4166]
Hi!

Updated to 4.0.1 and discovered that there's a bug with `minimumResultsForSearch` in Chrome.
If the requirements for this are not met (say I have 4 results and `minimumResultsForSearch` is set to 5) the select2 dropdown immediately closes on mouseup. That is to say, When the click is "pressed down" it  appears but as soon as I release it closes. 

Did not see this behaviour in 4.0.0 but I could be wrong. 
Tested in latest Chrome, Firefox and Safari and I can only see this issue in Chrome.

**Comment by kevin-brown** [comment]
Any chance you can create a jsbin that reproduces this issue? I can't reproduce this on the examples page.

https://select2.github.io/examples.html#hide-search

**Comment by jonathan-dejong** [comment]
I’ll see if I can get an example up.. 

Med aldrig sinande vänlighet,
Jonathan de Jong
Webbutvecklare och Webbdesigner
Tigerton AB

Epost: jonathan@tigerton.se <mailto:jonathan@tigerton.se>
Mobil: 0737 85 02 62
Adress: Monbijougatan 17G, 211 53 Malmö
Webb: www.tigerton.se <http://www.tigerton.se/>

**Comment by jonathan-dejong** [comment]
Hmm strange. I can't replicate the issue in jsfiddle. However I've seen it happen on a few sites as well as on my dev site for plugins in WordPress.

**Comment by graham73may** [comment]
Having this exact issue... Same situation with the problem happening in Wordpress and not jsfiddle. Using 4.0.6

My ES6 module gets compiled down with babel, this is all that's in it:

```
/* global jQuery */

import $ from 'jquery';
import Select2 from 'select2';

class Filters {
    constructor () {
        $(window).on('load', () => {
            new Select2();

            $('select.facetwp-yearly').select2({
                minimumResultsForSearch : -1,
                width : '100%'
            });
        });
    }
}

export default Filters;

```

Works fine if I comment out `minimumResultsforSearch`

**Comment by squelchdesign** [comment]
I'm also seeing this behaviour, but only in Firefox. 🤷‍♂️

The issue seems to be to do with the dropdown not positioning itself well on Firefox. Sometimes, with developer tools open, it will open in strange positions above the selection box but, most of the time, it opens with the dropdown positioned over the top of the selection box. When the search field is there it presumably absorbs the mouseUp event from the user clicking on the selection box, but when it's _not_ there the dropdown receives the mouseUp event and therefore closes, thinking whatever was under the mouse was selected by the user.

I too am using this in a WordPress environment. I can't imagine that's directly the issue, but perhaps something in the theme or a plugin is clashing with either Select2's JS or CSS and causing it to calculate the position for the dropdown incorrectly?

My selection box:

![Screenshot 2021-07-21 at 17 49 55](https://user-images.githubusercontent.com/3788658/126527778-676f3593-de9c-47a0-8767-6fea043dd62f.jpg)

With the search field present, dropdown remains open on mouse-up:

![Screenshot 2021-07-21 at 17 49 25](https://user-images.githubusercontent.com/3788658/126527851-c00dc467-dbee-4484-8f9e-e41e2b83f137.jpg)

Without the search field present, dropdown closes as soon as the mouse is released:

![Screenshot 2021-07-21 at 17 49 49](https://user-images.githubusercontent.com/3788658/126527933-c6330f2e-ac57-45f9-ba8e-9311b71c4a68.jpg)

In this state if I click into the selection box and keep the mouse button down, drag away to a blank area of the page, and then release, then the dropdown remains open.

In Chrome the dropdown seems to reliably appear below the selection box as expected.

Tested versions [4.0.13](https://github.com/select2/select2/tree/4.0.13) and [4.1.0-rc.0](https://github.com/select2/select2/tree/4.1.0-rc.0) and the issue was present in both.

@jonathan-dejong: did you ever manage to find a workaround for your issue?

**Comment by squelchdesign** [comment]
Okay, solved my issue above. In WordPress, when you're logged in, you have the admin bar at the top of the screen, which sets a 32px offset on the body. Take a look at: https://select2.org/dropdown#dropdown-placement

On Chrome I wasn't logged in, thus no admin bar, and so that's why the issue didn't appear there.

In Firefox, while logged in,

`jQuery(document.body).offset();`

outputs

`Object { top: 32, left: 0 }`

Hope this helps save someone else an hour of debugging!

**Comment by benwallis** [comment]
> Okay, solved my issue above. In WordPress, when you're logged in, you have the admin bar at the top of the screen, which sets a 32px offset on the body. Take a look at: https://select2.org/dropdown#dropdown-placement
> 
> On Chrome I wasn't logged in, thus no admin bar, and so that's why the issue didn't appear there.
> 
> In Firefox, while logged in,
> 
> `jQuery(document.body).offset();`
> 
> outputs
> 
> `Object { top: 32, left: 0 }`
> 
> Hope this helps save someone else an hour of debugging!

Thanks @squelchdesign, is there a solution to make it work with the admin bar?

**Comment by squelchdesign** [comment]
I did something like this:

```
// Fix for Select2 dropdowns on WP when logged in: offset applied to <html> causes dropdowns to render badly

if ( $('body.logged-in.admin-bar').length > 0 ) {
    $('html').attr( 'style', 'margin-top: 0 !important;' );     // Necessary to override WP's !important
    $('#the-first-div-on-the-page').css({'margin-top': 32});    // Move the 32px gap to the first div on the page
}


// Enable Select2:

$('#my-dropdown').select2({ … });
```

Basically the code disables WordPress's 32px margin-top on the HTML tag, and then adds a new margin-top of 32px to the first div on the page. This still works with the WordPress admin bar, and prevents the issue with Select2 dropdowns on the page.

On the site that I created this for the first div on the page had a unique name and would always be present, so it was easy to do with a simple jQuery selector, but you could easily make something more generic if you don't know what the first div is going to be.

Note that I fixed up the margin-top BEFORE calling `.select2()` on my dropdown.

**Comment by benwallis** [comment]
The admin bar inline CSS can be removed like this:

```
function remove_admin_bar_bump()
{
    remove_action('wp_head', '_admin_bar_bump_cb');
    return true;
}
add_filter('show_admin_bar', 'remove_admin_bar_bump');
```

https://wordpress.stackexchange.com/questions/349491/remove-annoying-wp-adminbar-css

**Comment by squelchdesign** [comment]
But presumably that means that the page content slips under the admin bar. While it's probably not a showstopper for the most part, it would drive me insane! 😁

You could however combine the solution you've listed above with the creation of a div that's 32px high which would push the page content back down the page again. Something like (but note that this is completely untested):

```
function alt_admin_bar_bump()
{
    add_action('wp_head', function() {
        echo '<div style="height: 32px;"></div>';
    });
    remove_action('wp_head', '_admin_bar_bump_cb');
    return true;
}
add_filter('show_admin_bar', 'remove_admin_bar_bump');
```

**Comment by benwallis** [comment]
Yes I moved the margin to the body with this CSS:

```
@media (max-width: 767px) {
  body.admin-bar {
      margin-top: 46px;
  }
}

@media (min-width: 768px) {
  body.admin-bar {
      margin-top: 32px;
  }
}
```
