### ISSUE TITLE
Unselect not working when search field is outside viewport

### ISSUE THREAD

**Issue by plachance** [select2/select2#4172]
Hi,

There's a bug when unselecting an item in a multi-value Select2 while the search field is outside the viewport.

**Steps to reproduce :**
1. Create a Select2 control with a lot of options and multiple selection enabled.
2. Select as many options as necessary to have the search field outside the viewport. You can also reduce the window's size.
3. Ensure that the Select2 doesn't have the focus.
4. Unselect an item.

See this jsFiddle : https://jsfiddle.net/qctgeqp1/

**Expected outcome :**
The unselected item is removed from the Select2 control.

**Actual outcome :**
The unselected item is not removed from the Select2 control.
The focus is set on the search field.
The viewport is scrolled to show the search field.
The dropdown is shown on Chrome, but not on Firefox.

Tested on Chrome and Firefox with Select2 4.0.1, jQuery 1.12.0.

I haven't found any workaround yet.

Thank you.

**Comment by Stafie** [comment]
@plachance @kevin-brown any solution here?

Thanks!

**Comment by plachance** [comment]
@Stafie still no solution or workaround.

**Comment by dombesz** [comment]
I'm sure that there is a race condition between the events, since I don't always get the issue.
Removing the trigger for the search field focus solves the issue. Apparently the focus is triggered twice, since there is the `open` https://github.com/select2/select2/blob/083c2112df22d73d432f806411524104f8b72056/src/js/select2/selection/search.js#L34-L36 event is also triggered.

Here is the event that needs to be removed: https://github.com/select2/select2/blob/083c2112df22d73d432f806411524104f8b72056/src/js/select2/selection/search.js#L54-L56

``` 
container.on('open', function () {
      self.$search.trigger('focus');
});
```

**Comment by elakkuvan** [comment]
any solution here?

**Comment by elakkuvan** [comment]
I am also facing issue

**Comment by hovjacky** [comment]
Hello, any solution to this please?
