### ISSUE TITLE
Using in Context with Angular JS

### ISSUE THREAD

**Issue by sandeep06011991** [select2/select2#4185]
Is it advisable to use this plugin with angular js 
<select name="codes[]" ng-model="formData.codes" id="multi-append-code"
                                            class="select2" multiple="multiple" style="width:500px;"
                                             ng-options="
                                             code.id as code.region+' '
                                            +code.network  for code in codes track by code.id" value="[[code.id]]" >
                                        <option></option>

and then run ('#multi-append-code').select2()

**Comment by kevin-brown** [comment]
Last I heard, Select2 4.x works natively with AngularJS. I would avoid using Select2 3.x with AngularJS, because I know it definitely doesn't work.

----

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://select2.github.io/community.html
[irc]: https://select2.github.io/community.html
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes
