### ISSUE TITLE
"Uncaught TypeError: Illegal constructor" in jquery.js:3148 when select for a first time

### ISSUE THREAD

**Issue by AlexanderMatveev** [select2/select2#4196]
This callback fails only on first item selection after page render.

See screenshot:

![2016-02-18 19 16 43](https://cloud.githubusercontent.com/assets/1456669/13149862/31d6809a-d674-11e5-90db-8155d9a83e7f.png)

**Comment by kevin-brown** [comment]
At the very least, we're going to need the full traceback and Select2 version in order to start figuring out where this error is.

---

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on the examples page][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[examples]: https://select2.github.io/examples.html
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by Trapdafifou** [comment]
hope he will answer,  I got the same problem

**Comment by jpic** [comment]
@Trapdafifou could you answer @kevin-brown 's questions by any chance ?

**Comment by Trapdafifou** [comment]
I can't i'm very bad developer and this is for a tricky bug i think i can't reproduce this bug without showing my project.

**Comment by Trapdafifou** [comment]
All I can do is to give you the exact error 

Uncaught TypeError: Illegal constructor
    at j (vendors.js:2)
    at Object.add [as done] (vendors.js:2)
    at n.fn.init.n.fn.ready (vendors.js:2)
    at n.fn.init (vendors.js:2)
    at n (vendors.js:2)
    at DecoratedClass.SelectAdapter.select (vendors.js:15395)
    at DecoratedClass.ArrayAdapter.select (vendors.js:15672)
    at Select2.<anonymous> (vendors.js:15469)
    at Select2.Observable.invoke (vendors.js:12975)
    at Select2.Observable.trigger (vendors.js:12965)

**Comment by Trapdafifou** [comment]
UP For me it was just a Document.ready before the function to add it now works perfectly
thanks for your help !

**Comment by alexweissman** [comment]
This issue does not appear to conform to our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Please re-read the contributing guidelines _carefully_ and then edit your question.  Once your issue complies with the guidelines, we can reopen it.

**Comment by rohitkudos** [comment]
Uncaught TypeError: Illegal constructor
    at eng_xml ((index):659)
    at HTMLDocument.<anonymous> ((index):671)
    at i (jquery.js:2)
    at Object.fireWith [as resolveWith] (jquery.js:2)
    at Function.ready (jquery.js:2)
    at HTMLDocument.K (jquery.js:2)
