### ISSUE TITLE
data id cannot be an object, only string?

### ISSUE THREAD

**Issue by keyscores** [select2/select2#4227]
Searched here and posted on: http://stackoverflow.com/q/35717211/359284

With select2 v4.0.2-rc.1,  there are 2 required parameters for each list item: "id", and "text". 
All is well if both your id and text are String types. However when I try to make id into an Object, I get errors. Inspecting in the console, I can see that id = ["[object Object]"]

The code I'm using to generate the list for select2:

    var list = [ "apple", "banana", "orange"]
    var list =  _.map(list, function(each){
     return { id: { myName: each, otherData: 1 }, text: each }
    });

    $(".js-example-basic-single").select2({
      data: list
    });
    //>  ["[object Object]"]

I can't see anywhere in the docs whether "id" can only be a string and not an object. 

Is it possible to have "id" be an object? If so, is there any special syntax?

**Comment by kevin-brown** [comment]
This was something that was changed in 4.0.0, the `id` must be a string because an `<option>` value must be a string. Select2 will automatically convert any non-string ids to an id.

https://github.com/select2/select2/releases/tag/4.0.0-beta.1

I'm leaving this open as this has not yet been documented, except for in the old release notes.

**Comment by keyscores** [comment]
Ok worth mentioning in the docs that one can add other properties to the data object. 

    data: { whatever: "nevermind" }

It allowed me to circumvent the string only constraint.
