### ISSUE TITLE
Multiple default values (selected="selected") means they dont clear when you remove them

### ISSUE THREAD

**Issue by add1ct3dd** [select2/select2#4241]
http://jsfiddle.net/j8b0f5gp/1/

You can see the top 3 values are "defaulted" as already selected - if you try and clear them they get removed from the UI, but are still there in the select (and still selected).

**Comment by kevin-brown** [comment]
It's not clear what the issue is here, the options are being unselected. You can verify this by logging the `.val()` after every change.

https://jsfiddle.net/zwjm9erk/

Note that Select2 doesn't modify the `selected` attribute on the `<option>` (HTML), but rather the `selected` property on the `HTMLOptionElement` (JavaScript DOM), when selected and unselecting things.
