### ISSUE TITLE
Select2 doesn't work in dynamically new elements with MutationObserver

### ISSUE THREAD

**Issue by Serpentsoft** [select2/select2#4282]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a repeater to add some elements dynamically in run-time
2. include underscore.js to use each function in it.
3. Write the following code in separated js file...

` 

         MutationObserver = window.MutationObserver || window.WebKitMutationObserver || window.MozMutationObserver;

         var observerjQueryPlugins = new MutationObserver(function (repeaterWrapper) {

        _.each(repeaterWrapper, function (repeaterItem, index) {
            
            var jq_nodes = $(repeaterItem.addedNodes);

            jq_nodes.each(function () {

                // Color Picker ( WORKS GOOD )
                $(this).parents('.repeater-container').find('.xx-color-picker').wpColorPicker();

                // Date Picker ( WORKS GOOD )
                $(this).parents('.repeater-container').find('.xx-datepicker').datepicker({
                    dateFormat: "dd MM, yy",
                    showAnim: "slideDown",
                    changeMonth: true,
                    numberOfMonths: 1
                });

                 // Select2 (Doesn't WORK - Infinite Page Load)
                 $(this).parents('.repeater-container').find('.xx-select2').select2();
                
           }); 
        }); 
    });

    observerjQueryPlugins.observe(document.body, {
        childList: true,
        subtree: true,
        attributes: false,
        characterData: false
    });`

## Expected behavior and actual behavior

When I follow those steps, I see...
Infinite page load when create a new element in the repeater control but when disabling Select2 the colorPicker and DatePicker working properly

I was expecting...

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 1.11.3 in WordPress
- Select2 version: 4.0.0

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kevin-brown** [comment]
I'm going to take a wild guess here and say that the issue is that Select2 adds a bunch of elements into the DOM when it is initialized, and one of those is triggering the same mutation event that you are catching. It's not something that can be solved within Select2, I'd recommend filtering down your `.xx-select2` element set to not include `<select>` elements that have already been initialized.

---

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://select2.github.io/community.html
[irc]: https://select2.github.io/community.html
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes
