### ISSUE TITLE
Solution when clear button is pressed

### ISSUE THREAD

**Issue by jstuardo** [select2/select2#4332]
I have implemented select2 4.0.2 in my site with Bootstrap 3 theme.

The problem I have was concerning "x" clear button. When pressed, nothing happend but opening the drop down.

To solve it, I have replaced this code, in line 1760 of select2.js:

`this.$element.val(this.placeholder.id).trigger('change');

this.trigger('toggle', {});
`
By:

`this.$element.val(this.placeholder.id).text(this.placeholder.text).trigger('change');

//this.trigger('toggle', {});`

That way, it was also solved the problem that caused the drop down to be opened when the clear button is pressed.

I think you should implement this in the official release.

**Comment by kevin-brown** [comment]
More than likely you are missing the blank placeholder option, and that's why it wasn't working.

---

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on the examples page][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[examples]: https://select2.github.io/examples.html
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by jstuardo** [comment]
No.... this is the definition:

$("#departamento").select2({
            theme: "bootstrap",
            placeholder: {
                id: '',
                text: 'Todos los departamentos'
            },
            allowClear: true,
            language: 'es',
            minimumResultsForSearch: 20,
            minimumInputLength: 1,
            ajax: {
                url: "@Url.Action("Departamentos", "Maestro")",
                dataType: 'json',
                delay: 250,
                data: function (params) {
                    return {
                        q: params.term, // search term
                        page: params.page
                    };
                },
                processResults: function (data, params) {
                    params.page = params.page || 1;

                    return {
                        results: data.items,
                        pagination: {
                            more: (params.page * 30) < data.total_count
                        }
                    };
                }
            },
        });

**Comment by ToreOlavKristiansen** [comment]
I see the same as @jstuardo. His solution works for me. Thanks :) Do you want a pull request for this @kevin-brown?
