### ISSUE TITLE
Select2 doesn't trim text in <option> tag

### ISSUE THREAD

**Issue by guoyunhe** [select2/select2#4412]
```html
<select multiple="multiple" style="width:400px">
  <option value="1">
         Dog
  </option>
  <option value="2">
         Cat
  </option>
  <option value="3">
         Monkey
  </option>
  <option value="4">
         Panda
  </option>
</select>
```

```javascript
$('select').select2();
```

When backspace delete tag, you can see here are a lot of spaces in text.

Screenshot:

![spectacle d14927](https://cloud.githubusercontent.com/assets/5836790/15976308/9b26f95a-2f5a-11e6-881a-1505876dd922.png)

Demo:

http://codepen.io/guoyunhebrave/pen/OXMBQr

**Comment by kevin-brown** [comment]
Select2 pulls the `text` from the `<option>` based on the [`text` property of the `<option>`](https://developer.mozilla.org/en-US/docs/Web/API/DOMString). This is important to know, because it follows the standard HTML rules of parsing an `<option>` and relies on the browser doing it properly. Nowadays, most browsers parse it properly and a handful of them will render it properly.

Whitespace is significant at times in HTML, and I can't easily explain the whitespace rules because it's complex. But **whitespace around text within an element is significant**, and as you've seen the browser will not remove it. As a result, Select2 will also see the whitespace and doesn't strip it out (we used to, but that caused a _new class of problems_).

My recommendation is to not include the whitespace around the option text, and instead render it with the rest of the `<option>` on one line.

```html
<select multiple="multiple" style="width:400px">
  <option value="1">Dog</option>
  <option value="2">Cat</option>
  <option value="3">Monkey</option>
  <option value="4">Panda</option>
</select>
```
