### ISSUE TITLE
how to set an alternative value when search and match the id attribute?

### ISSUE THREAD

**Issue by johnzhang2013** [select2/select2#4415]
Hello all,
There is an very special and good requirement when use this plugin.
My data source looks like this:

{id: '1', text: 'john zhang', 'sc': 'JZ'},
{id: '2', text: 'ray lee', sc: 'RL'},
{id: '3', text: 'bruce lee', sc: 'BL'},
{id: '4', text: 'jack cheng', sc: 'JC'},
....by the way 'sc' means 'shortcut'

How to make it when people type 'JZ' /'RL'/'BL'/'JC',The according option will be selected or showed?

I hope I already made this problem clear.

**Comment by johnzhang2013** [comment]
anybody could help me or just guide me.
This is very important for my current project.
@kevin-brown

**Comment by SgtOddball** [comment]
I don't think there's a way to utilise secondary values since that's more of an edge case than anything else. 

As an idea, i've not tried to do it but could HTML code be passed through for the 'text' value? In which case, add the shortcut but wrap it in span to hide it (change it's colour text to match the background, no more visible text) which should then allow the shortcuts to be picked up? 

That is a massive speculation and is probably a crap idea but it's the sort thing i'd try for an edge case before trying to add a large new feature to the core select2 (since i don't remember ever seeing a reference to such a capacity anywhere before for select2).

**Comment by alexweissman** [comment]
How about a [custom matcher](https://select2.org/searching#customizing-how-results-are-matched)?  You could access your extra field via `data.sc`.

You can customize how selections _appear_ by using the [templateSelection](https://select2.org/selections#templating) option.
