### ISSUE TITLE
Virtual keyboard obscures dropdown items for multi-select in mobile views

### ISSUE THREAD

**Issue by johndoefromhere** [select2/select2#4425]
I could not believe it, but select2 is completely broken on mobile devices, while https://github.com/select2/select2/issues/1541 is marked as closed.

Please, either fix it or announce you're not going to do anything about it, so we can stop waiting and hoping, and switch to Chosen instead.

Please, provide us with an estimated date!

Thank you very much!

**Comment by SgtOddball** [comment]
??? Just tested it now on both an Android phone (running 5.0.1 android) on both chrome and firefox, works perfectly fine for both. 

Fired up the iPad and that works like a charm too.

So, you're going to have to be more specific about your setup and exactly how its not working, since without being able to repeat the issue, it can't be fixed.

**Comment by kevin-brown** [comment]
> So, you're going to have to be more specific about your setup and exactly how its not working, since without being able to repeat the issue, it can't be fixed.

This gets to the point much faster than what you're about to read.

----

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on the examples page][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[examples]: https://select2.github.io/examples.html
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by johndoefromhere** [comment]
After clicking on a field, virtual keyboard appears covering displayed list of options (well, most of it). I have to scroll down a bit to even see it. Even a standard select would be better than this.

I'm using Android 4 and multiply select.

**Comment by SgtOddball** [comment]
The virtual keyboard kicks in because you've got the searching enabled and thus needs text entering. There's a couple of ways around this. 

1. Hide the search box [as shown here](https://select2.github.io/options.html#how-can-i-permanently-hide-the-search-box)
```javascript 
$('select').select2({
  minimumResultsForSearch: Infinity
});
```

2. Prevent focus on select like this;
```javascript
$('select').on('select2:open', function(e) {
    $('.select2-search input').prop('focus',false);
})
```

3. Read more - [Like this issue thats been raised along time ago and has a number of different ideas and options listed.](https://github.com/select2/select2/issues/1541)


Finally, don't kick and scream like a spoilt child with threats of no longer use a free and open sourced plugin that has a vibrant and knowledgeable community that has probably encountered your problem before and can be found with a couple of minutes of searching.

**Comment by Rasala** [comment]
@SgtOddball I have similar problem on Android. Unfortunate I don't have a device so I'm using VM.

I've disabled the search focus as you suggested but when I'm clicking on this search the search closes.

Problem occurs on Android 6.

**Comment by alexweissman** [comment]
Pinning this so we can add @SgtOddball's solution for mobile views to the documentation.
