### ISSUE TITLE
select2 4.0.3 Searching has strange character appended to it now?

### ISSUE THREAD

**Issue by mkoch42** [select2/select2#4431]
Just updated from 4.0.2 both css and js and now the searching message in the ajax lazy load functionality has a wierd character at the end.  SS below!

Thanks
Matt

![image](https://cloud.githubusercontent.com/assets/831101/16159589/b07e6432-3491-11e6-9df2-d73d573a6285.png)

**Comment by kevin-brown** [comment]
This is a good sign that you saved the JS file with an ASCII (or at least, non-UTF8) encoding. The "Searching..." translation includes the unicode ellipsis character, which wasn't encoded properly when you saved it.

**Comment by istrau2** [comment]
@kevin-brown I am getting something similar: Searchingâ€¦ is displayed instead of Searching...

I used npm to install select2. Not sure about file encodings.

When I go to node_modules/select2/dist/js/select2.js I can see that the text Searchingâ€¦ is in the file, so it is not as if the browser is responsible. The actual file is incorrect. Not sure what I am doing wrong...

 I am on Windows 10 if that helps.

**Comment by Graynoble** [comment]
I am also having this issue using the latest Select2 4.0.5.  My page is encoded using utf-8.

**Comment by robsilva** [comment]
@Graynoble Do you have 
<html lang="en"> ?

**Comment by Graynoble** [comment]
Hi @robsilva ,

Yes, I tested it this morning.  I do have <html lang="en">

I am still getting the strange characters in the "Searching..."

**Comment by kgajera** [comment]
Adding the 'charset' attribute to the script fixed it for me:

`<script type="text/javascript" src="select2.js" charset="UTF-8"></script>`

**Comment by Graynoble** [comment]
Thank you kgajera! Perfect for my project!

**Comment by becher** [comment]
You can use searching option in the  select2 to modify your text 
"searching": function () {
          return "your message here";
        },
