### ISSUE TITLE
Getting the selected values

### ISSUE THREAD

**Issue by beno** [select2/select2#4449]
I have a multiple select box, remote data source through a transporter function, and some initial values set by adding the relevant options and setting initial values like so:

   $('#selectable').select2(options).val([id, id, id]).trigger("change")

This all works fine. But when I start adding/removing values, while the underling option tags are being modified, the newly selected ones don't get the 'selected' property. So from jQuery's point of view, the select never gets any new values set. Subsequently, I can't retrieve the select's value with

```
$('#selectable').val()
```

for subsequent processing. In short: how do I retrieve the selected values from a select2 multiple select? The only possible way I found was through the "select2:select" event, but that would mean I need to keep an array in sync, which is too ugly a hack for my taste.

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on the examples page][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[examples]: https://select2.github.io/examples.html
[test-case]: https://css-tricks.com/reduced-test-cases/

**Comment by ozc** [comment]
I came across the same error. Getting selection from either from ajax data, or just text entered directly, when the form is sent to server, only the last one is sent. When I checked the select options none of them is selected. Only data-select2-tag=true attributes were there and that's no use for this.

Another bug is, if some text is written but not clicked on it and clicked outside the selectbox elsewhere on the page, there is still an option tag for it. Till select box is clicked again. When the select box is clicked again, that option is deleted. The problem is, by this time user may submit the form.

**Comment by leandro-mnc** [comment]
I'm having the same issue. 

> "only the last one is sent" ...

**Comment by alexweissman** [comment]
The correct way to retrieve the current selections is either via `.select2('data')`, or using a `find(':selected')` selector.  Do **not** rely on the `selected` attribute.  

See https://select2.org/programmatic-control/retrieving-selections
