### ISSUE TITLE
Set option background color

### ISSUE THREAD

**Issue by sagaio** [select2/select2#4483]
According to https://github.com/select2/select2/issues/3628 it should now be possible to style the "option"s but I can't seem to get it to work.

This is one of my "option"s:
`<option value="RAL 1005" class="ralcp-A98307" style="background-color:#A98307" data-color="#A98307">RAL 1005</option>`

This is the Select2 output: 
`<li class="select2-results__option select2-results__option--highlighted" id="select2-ralcp-select-result-mxpt-RAL 1005" role="treeitem" aria-selected="false">RAL 1005</li>`

None of the above attributes seems to be inherited by the Select2 options.
I also have a class `.ralcp-A98307` but that neither gets inserted into the Select2 markup. I have no templating or formating setup in Select2. As you can see I'm simply trying to apply a unique background color to each option. What am I missing?

Browsers
- [X] Google Chrome
- [X] Mozilla Firefox
- [ ] Internet Explorer

Operating System
- [X] Windows
- [X] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- jQuery version: 1.12.4
- Select2 version: 4.0.5

**Comment by alexweissman** [comment]
This appears to be a support question, rather than a feature request or bug report.  So, I am closing it.  

If you have discovered an underlying bug causing this problem, please search the open issues and comment there (or if an issue specifically about the underlying bug is not already open, you may open a new one - just make sure it identifies the **underlying bug**).

If, on the other hand, this is simply a matter of using Select2's features properly, it should be discussed on the [forums](https://forums.select2.org) instead.
