### ISSUE TITLE
Tab and Esc should select the option

### ISSUE THREAD

**Issue by Glideh** [select2/select2#4578]
I can see many issues concerning the next input focus but not any concerning selecting an option with <kbd>TAB</kbd> or <kbd>ESC</kbd>.

With `4.0.3` (ie: current [official examples](https://select2.github.io/examples.html)):
- Open a single select2 with default options
- Highlight an option with the keyboard
- Hit <kbd>TAB</kbd> or <kbd>ESC</kbd>
- The `select` will keep his original value
- The only way with the keyboard is <kbd>ENTER</kbd> (which I avoid to use in forms)

Shouldn't it select the highlighted option as it does with a standard `select` ?

_Tested on OSX with Chrome and Firefox_

**Comment by dbeusee** [comment]
I agree with tab to select highlighted option, but not esc.

**Comment by Glideh** [comment]
Only <kbd>TAB</kbd> would be ok for me but <kbd>ESC</kbd> does select the option on a standard `<select>`

**Comment by dbeusee** [comment]
If you use up/down arrow keys, that's true (because the arrow keys actually change the field - in chrome you can see it happening), but not if you just hover the mouse over the option.  However, <kbd>TAB</kbd> changes it in both cases (in chrome, not IE).  I think <kbd>ESC</kbd> should **not** update it in both cases.

**Comment by Glideh** [comment]
Indeed, I didn't check with the mouse.

**Comment by c4blackarrow** [comment]
Yes Esc, should simply close the dropdown (and keep focus on the field), while Tab should commit the value , close the dropdown (and keep focus on the field).

Then we can have a separate debate about if using the arrow keys should act as a regular select in that they have already selected the new value (rather than the mouse which does not).  Either way, in a regular select the Esc and Tab keys appear to work the same because the value has already been committed by the arrow key functionality, hence why they look like the act the same.

Note that there are also several other interactions with the keyboard that do not match (Enter commits but loses focus on the field) which should be dealt with as well.

**Comment by Glideh** [comment]
It would seem logical to have the same behavior than regular selects on major browsers.

**Comment by ryanpcmcquen** [comment]
For reference:

```js
foo.select2({
  selectOnClose: true
});
```

Somewhat mimics this behavior.

**Comment by dbeusee** [comment]
Yes, somewhat.  There are differences that should be fixed.

**Comment by diegodesouza** [comment]
Has this been fixed? The way I'm interacting with the select2 is to open I hit `space` to select something i hit `enter`, but if i try tabbing to continue to the next field, I have lost the index count, meaning it goes back to 0.

**Comment by mota57** [comment]
the property  selectOnClose: true didn't work. 😢  even I put tabindex="999"  and the select to is not even select it. it just jump from one input to another.

**Comment by CGollhardt** [comment]
Not sure why this is closed? Have I overlooked something? My typicial workflow is to search something in the select (via the search box) and press tab -> Result: The original value is restored.

**Comment by alexweissman** [comment]
See #4820 for the canonical issue for this feature request.
