### ISSUE TITLE
multiple value not get in post in php

### ISSUE THREAD

**Issue by dhavalmodi7** [select2/select2#4592]
## Prerequisites
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ ] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue

1.
2.
3.
## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...
## Environment

Browsers
- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer

Operating System
- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- jQuery version:
- Select2 version:
## Isolating the problem
- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by dhavalmodi7** [comment]
I have a issue related select2. when i post a from with multiple select with select2 but i got a only last value so can you help me out this ?

**Comment by SgtOddball** [comment]
Have you used dev tools to check that all values are being sent? More likely than not PHP is only calling back the first value because you've not told it to expect an array of values being passed over. 

A good way to test this is to not apply select 2 and just use the native multi select and if you get the same problem then it's the PHP code at fault in all likelyhood and not select2 (So make sure your select has `[]` in the element name to pass it through as an array. 

[This](http://stackoverflow.com/questions/17957588/store-multiple-select-option-into-a-php-array) stack overflow has more details on the for you. 

Though I am going off guess work here, and don't profess to be a PHP master.

**Comment by alexweissman** [comment]
Yes, in PHP you need to have `[]` in your `name` attribute in order for PHP to interpret the request parameters as an array.  We can add this to the documentation.

**Comment by marvin46** [comment]
i'am using ajax to get department by division id for the parameter,  when i'm add [] in my form name ex name="dept_id[]"
my multi select2 is cannot be accessible event i've choose a parameter before 
this is my form php
https://pastebin.com/CDf8xeCb

this is my js
https://pastebin.com/c1ekFgPL

**Comment by marvin46** [comment]
and this is my save api 
https://pastebin.com/wcWBrjnf
