### ISSUE TITLE
[4.0.3] Destroy by class name

### ISSUE THREAD

**Issue by santaclaus21** [select2/select2#4595]
#3413 Continue
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
## Steps to reproduce the issue
1. Create more than 1 select with class "select2"
2. Apply select2 only for one select
3. Call $("select.select2").select2("destroy")
## Expected behavior and actual behavior

When I follow those steps, I see ERROR.
I was expecting destroy only on elements having select2.

I have fixed that in ugly way: $("select.select2-hidden-accessible").select2("destroy");

JS Bin: 
NOT working: https://jsfiddle.net/fbz0mngp/21/
UGLY FIXED: https://jsfiddle.net/fbz0mngp/24/

Destroy in that way wasn't generate errors in 3.5 branch.

**Comment by alexweissman** [comment]
It looks like this issue should have been resolved in https://github.com/select2/select2/commit/878bb3ab0792197ae74b06f0e8cccb17ef16530e.

After [updating your broken jsfiddle](https://jsfiddle.net/u3w8dyqn/), I can see the error message that clearly states:
> The select2('destroy') method was called on an element that is not using Select2.

You are indeed trying to call `destroy` on an element that was never initialized as a Select2.  So, I don't see the problem here.
