### ISSUE TITLE
After add a button to drop down of select2 but can click on that button.

### ISSUE THREAD

**Issue by hengsoheak** [select2/select2#4615]
I have try to add a button to drop down of select2 jquery (version2) it work as well but I can't use click event in jquery how can I do.

```
  $("#addr_types").select2();
  $('.select2-drop').append('<i style="float: right;" class="btn btn-info btn-sm" id="add" "> Add </i>');
```

Step tow

```
  $('.city').select2({
       formatNoMatches:function(term){
            return '<i style="float: right;" class="btn btn-info btn-sm" id="add">Add</i>';
       }
     });

$(document).on('click', '#add, #select2-results-2, .select2-results,.select2-drop', function(){
    alert();
});
```

**Comment by alexweissman** [comment]
The dropdown options don't actually exist until Select2 has been initialized.  Since Javascript is asynchronous, the buttons probably don't even exist yet when you call `.on('click' ...`.  Try initializing your buttons inside a callback for Select2's [`open` event](https://select2.org/programmatic-control/events).

**Comment by hengsoheak** [comment]
Yes I solved it
