### ISSUE TITLE
Prevent that an ajax call is made when using the searchbox and search instead in current list

### ISSUE THREAD

**Issue by ProgrammingTestGitHub** [select2/select2#4667]
We want to use the current function of an select2 ajax call when opening the dropdown list. But we do not want that the function sends another ajax call when typing in the seachbox because the data is already available in dropdown list. Is there a way to prevent that an ajax call is being made when typing text in the searchbox.

Currently it takes a long time before the search is ended because it does an ajax call when typing instead of looking in the existing list that has already been collected by the ajax call when opening the dropdown. The currently code that we have is shown below.

## Steps to reproduce the issue
**js.code**
````   
 $("#gebruikerId").select2({
    width: "200px",
    dropdownAutoWidth: true,
    minimumResultsForSearch: 10,
    ajax: {
        url: "webservice.php",
        dataType: 'json',
        delay: 0,
        data: function (params) {
          return {
              request: "getUsers",
              q: params.term // search term
          };
        },
        processResults: function (data, params) {
                var results = [];
                $.each(data, function(index, item){
                    results.push({
                        id: item.id,
                        text: item.omschrijving
                    });
                });
                return {
                    results: results
                };
        },
        cache: true     
      }
}); 
````

**php code:**
```
<div class="gb-select-div">
    <select id="gebruikerId" name="gebruikerId" class="input-select-class"></select>
</div>
```

1. Open the dropdown. An ajax call is made.
2. Enter a value in the searchbox of the dropdown. An ajax call is made with the search term.

## Expected behavior and actual behavior

When I follow those steps, I see...
1. Open the dropdown. An ajax call is made.
2. Enter a value in the searchbox of the dropdown. An ajax call is made with the search term.

I was expecting...
1. Open the dropdown. An ajax call is made.
2. Enter a value in the searchbox of the dropdown. No ajax call, but searches the values that are shown in the dropdown. Because they have already been collected.

## Environment

Browsers

- [x] Google Chrome

Operating System

- [x] Windows

Libraries
- jQuery version:  jquery-ui-1.11.4.custom
- Select2 version: 4.0.3

**Comment by scheurta** [comment]
@ProgrammingTestGitHub 

I've had similar issues and have a "hackish" solution to the problem.

The basic concept is to remove the ajax property on success and set the data property to the data returned by processResults. And then initialize and open select2 again. 

With this concept, searching is only dom based since we already have the data.

Here's some example code:
```
var select2Element = $( 'select' );

var options = {
	ajax: {
		url: '/api/',
		type: 'json',
		data: function( params ) {
			return {
				action: 'action',
			};
		},
		processResults: function( data, params ) {
			return {
				results: data.data.items,
			};
		},
		success: function( data ) {
			delete options.ajax;

			options.data = data.data.items;

			select2Element.select2( options ).select2( 'open' );
		},
	},
};

select2Element( options );
```

**Comment by luronumen** [comment]
Please create a simple select2 ajax option for fixing this issue. This current select2 ajax behavior is making several unnecessary ajax request.

**Comment by alexweissman** [comment]
A better approach to this issue would be to:

1. Improve your remote data source's response time;
2. Use [throttling](https://select2.org/data-sources/ajax#rate-limiting-requests) to limit the frequency with which Select2 attempts to issue additional requests.

**Comment by MikeMajara** [comment]
@alexweissman The issue is not about response time, @luronumen whent straight to the point.

**Example**
Select2 with names of people attending a daily meeting (<=15). List of people changes daily.

**Problem**
Once, I have loaded the 15 names of today's meeting, why would I throw several more ajax requests to search among that list?

Obviously, the best response time or throttling adjustment will not be as good as implementing this functionality

**Comment by luronumen** [comment]
Hi @alexweissman 

Please evaluate this issue and reopen it for further investigation

Thanks in advanced

**Comment by alexweissman** [comment]
There is some discussion about solving this with a custom data adapter in https://github.com/select2/select2/issues/3927.

**Comment by luronumen** [comment]
ok @alexweissman, thanks!

**Comment by newportsolutionsgroup** [comment]
I have to agree that incorporating functionality into the [Configuration API](https://select2.org/configuration/options-api) for a single ajax call which populates the data option **_would be very valuable_**.

Using inspiration from @MikeMajara  and @ProgrammingTestGitHub and google here's a solution that works for me and may help someone else.  I only wanted to call the ajax once AND only if/when the user clicked the drop down to view the options (instead of loading all my drop downs every time the page loads). 

```
                        <select  class="form-control" name="office_id" id="office_id">
                            <option value="123">Newport Beach Office</option>
                        </select>
```
```
// office_id - event to load data via ajax only once if/when the select is clicked
$('#office_id').one('click', function (){
                                $.ajax({
                                    url: '/Office/List/',
                                    dataType: 'json',
                                }).done(function (data) {
                                    console.log(JSON.stringify(data.results) );
                                    $("#office_id").select2({
                                        data: data.results,
                                    });
                                    $("#office_id").select2("open");
                                });
                    });
```

**Comment by emudojo** [comment]
I still feel this is a pretty VALID user scenario

1. load data only when the user opens the dropdown
2. filter data locally
3. refresh data when he re-opens

now binding click events to the dropdown adds extra complexity to the workflow specially if you rely on open and opening events to validate certain conditions, also having to re-initialize the control every tie is a waste in my opinion.
