### ISSUE TITLE
IE11: value selected is wrong

### ISSUE THREAD

**Issue by jw1981** [select2/select2#4684]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Only in IE11
2. fixed width in options or dropdownAutowith = true
3. Select value from dropdown

See also [this ](https://www.youtube.com/watch?v=nzuSSqRrwpw&feature=youtu.be)video.

## Expected behavior and actual behavior

When I follow those steps, I see...
The wrong value selected.

I was expecting...
The right value to be selected.

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [x] Internet Explorer 11

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 2.2.4
- Select2 version: 4.0.3

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by elimn** [comment]
I am experiencing what I believe to be the same problem. Our select2 dropdown has a default value selected. In IE11, not other versions or browsers, if I select a value that appears underneath the default one in the list, then it will go with the default. If instead I select a value that appears above the default one, it will get selected.

Screencapture of the problem: http://imgur.com/a/CpJqa

Since the examples page does not contain a dropdown with a default value selected this can not be reproduced there. But, if it did contain such an example I believe I could reproduce this in IE11 on that page.

**Comment by kuiperr005** [comment]
@alexweissman Any updates regarding this issue? We're also experiencing the same problem..
