### ISSUE TITLE
The search input is not cleared when { tags: true, closeOnSelect: false }

### ISSUE THREAD

**Issue by jfcherng** [select2/select2#4698]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Click the input box
2. Type an non-existing tag, for example `xxx`
3. Press <kbd>Enter</kdb>

### When I follow those steps, I see...

A new tag is added but the search input is not cleared.
![aaa](https://cloud.githubusercontent.com/assets/6594915/20614937/583bc5b0-b30f-11e6-9301-db771a6006ec.gif)

### I was expecting...

The search input should be cleared.
I.e., `xxx` should be cleared from the search input.
Example jsbin: https://jsbin.com/wuxonaf/edit

## Environment

Browsers

- [x] Google Chrome
- [x] Internet Explorer
- [x] Mozilla Firefox

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Mobile
- [ ] Linux

Libraries

- jQuery version: 3.2.1
- Select2 version: 4.0.6-rc.0

## Isolating the problem

- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/wuxonaf/edit)
- [x] This bug happens when using Select2 without other pluigns

**Comment by alexweissman** [comment]
The jsbin link provided appears to no longer work.  Could you please provide a new one?

**Comment by jfcherng** [comment]
@alexweissman Sure. Link updated.

**Comment by alexweissman** [comment]
Thanks, this does indeed appear to be a bug.

**Comment by henadzit** [comment]
I'm having the same issue with 4.0.3.

**Comment by alexweissman** [comment]
Can you confirm whether this is still an issue in 4.0.6-rc.0?

**Comment by jfcherng** [comment]
@alexweissman I update the jsbin to `4.0.6-rc.0` [here](https://jsbin.com/qelehoqola/edit?html,output). This bug remains.

**Comment by alexweissman** [comment]
Alright thanks, I guess we'll wait for a PR that fixes this 😄

**Comment by risingtalent22** [comment]
Hi, @alexweissman.
I've met the exactly the same issue and is there any update for this?

**Comment by jfcherng** [comment]
I believe this is not fixed yet after viewing the commit log of the master branch.

**Comment by woorise** [comment]
I have the same issue. Is there any temporary fix on this?

**Comment by kevin-brown** [comment]
I'm not sure this is actually a bug, so here's the use case I'm thinking of.

1. You have Select2 hooked up to an AJAX data source (let's say the GitHub repo endpoint, like in the examples)
2. You search for "select2", trying to find all Select2-related repositories
3. You hold down "ctrl"/"alt"/"meta" (thus enabling closeOnSelect=false) and select the ones you care about

If we cleared out the search term on selection, you should select the first Select2-related repository, then the search box would clear and you would have to type "select2" again to get back that list. And you would have to keep repeating this. This definitely is not the expected behaviour.

I can understand where this is weird for the tagging use case, especially because the tag is automatically added to the results and remains there after you select it, but I believe this might be the expected behaviour for pretty much every other case. Can someone provide a use case where it does not make sense to maintain the search term and results when using closeOnSelect=false?

**Comment by SSheoran84** [comment]
we can use [clearSearchOnAdd]="true" to clear text

**Comment by MaiborodaPavlo** [comment]
Any updates?
