### ISSUE TITLE
select2.min.css “text-decoration: underline” issue

### ISSUE THREAD

**Issue by sinanyildiz** [select2/select2#4755]
I use select2.full.js and select2.min.css

I see that when I use select2.min.css, searched word underline was lost and never seen. When I look into select2.css it has "text-decoration: underline" but not select2.min.css

I added underline css into select2.min.css manually, but it didn't work.

Any answer is appreciated.

**Comment by alexweissman** [comment]
It's unclear how to approach this issue, since OP doesn't mention which version of Select2 has this problem.  Minified CSS is generated automatically by the [sass task](https://github.com/select2/select2/blob/master/Gruntfile.js#L211-L234), which uses https://github.com/sass/node-sass

In 4.0.4, I don't see a `text-decoration: underline` property in either the unminified nor the minified versions of the CSS dist file.  It is possible that this could happen, though.  Some minifiers are known to skip malformed CSS that would normally be recognized by most browsers.  A missing `}` or `;` could cause this to happen, for example.
