### ISSUE TITLE
Problema con select2 multiple al momento de hacer scroll en la ventana, los elementos de enciman 

### ISSUE THREAD

**Issue by gonzalocast17** [select2/select2#4799]
![capture](https://cloud.githubusercontent.com/assets/15850493/23036016/dacad69c-f446-11e6-8778-6d559f0803f9.PNG)

**Comment by William-H-M** [comment]
1) This a expected behavior from part of select you can try it on example page with multiple and will still happen
2) You should do the questiosn on english and put some description and not all the problem on the tittle and tell if at least you tried something before
3) Yes, I did understand your question because I speak spanisg too

**Comment by alexweissman** [comment]
In English:

> Problem with multiple select2 when scrolling in the window, the top elements

Unfortunately, this description and a screenshot are not enough for us to replicate the issue.  Please create a http://jsbin.com that demonstrates this problem, after which we can re-open the issue.
