### ISSUE TITLE
First item of previous result set is selected if you press enter before the AJAX request has completed

### ISSUE THREAD

**Issue by Seb33300** [select2/select2#4854]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

When working with a remote data source, the data source list is not cleared when the ajax search is triggered.
So if we tap the enter key before the search ajax call was loaded, the first item of the previous search is selected.

We are working with barcode readers on our application, so enter key is automatically pressed and the first item of the list is already selected.

## Expected behavior and actual behavior

Select2 should wait for the ajax response and select the first item if the result list is not empty.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer

Operating System

- [x] Windows
- [?] Mac OS X
- [?] Linux
- [?] Mobile

## Isolating the problem

- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other plugins

**Comment by jmtalves** [comment]
> When working with a remote data source, the data source list is not cleared when the ajax search is triggered.
> So if we tap the enter key before the search ajax call was loaded, the first item of the previous search is selected.
> 
> We are working with barcode readers on our application, so enter key is automatically pressed and the first item of the list is already selected.
> 

I have the same problem. Solutions?

**Comment by Seb33300** [comment]
No :( 

I disabled ajax, but it will be problematic when we will get a lot of entries...

**Comment by alexweissman** [comment]
I don't quite understand this issue - can you provide a working example and a set of steps to follow to reproduce the problem?

**Comment by Seb33300** [comment]
https://jsfiddle.net/3zeyroeb/2/

- Click on the select to open it
- write "one" and press enter as fast as possible (press enter before ajax finish loading)
=> the first item (hiroton) is selected => Not good

- Click on the select to open it
- write "one" and wait until the ajax loading refresh is finished and press enter
=> "one-coder" is selected which is the expected result

This make select2 unusable with barcode readers with remote data

**Comment by alexweissman** [comment]
Ah, I see what you're saying.  Since it's already fetched one set of results, if you press "enter" quickly enough it selects the first item from the first set of results, rather than waiting until the new set of results has been loaded and rendered.

I'm not really sure what the right solution would be.  It seems to me that maybe the control should become "locked" or disabled somehow until the AJAX request is completed and the new results are rendered.  This issue is reminiscent of a "double submission" problem in form submissions, the solution to which is to disable the submit button until the request has completed.

I don't think this is a good solution:
> Maybe, pressing enter should send the ajax request instead of selecting the first item?

This behavior would not be consistent with a classical `<select>` control.

**Comment by fmmich** [comment]
The following example (written in ES6) works around the problem by removing the highlight from the first item when a text change is made within the search box.  The lack of a highlighted item prevents the Enter key from working while the ajax call is retrieving results.  When ajax returns with results, the first item is highlighted again.

```javascript
$('#myselect2').on('select2:open', e => {
    // using '.ajaxfix' namespace so that the event can be specifically removed upon closing
    $('.select2-search__field').on('keydown.ajaxfix', e => {
        // tab, enter, shift, ctrl, alt, esc, pgup, pgdown, end, home, left, up, right, down
        if (![9, 13, 16, 17, 18, 27, 33, 34, 35, 36, 37, 38, 39, 40].includes(e.which)) {
            $('.select2-results__option').removeClass('select2-results__option--highlighted');
        }
    });
}).on('select2:closing', e => {
    $('.select2-search__field').off('keydown.ajaxfix');
});
```

I ran into the same problem reported here and needed to fix this in a production application that was affecting multiple users.

I don't recommend this as a permanent fix because it depends on race conditions and specific class names which could be changed by future releases of Select2.  I'm posting this to give @alexweissman an idea on how to resolve in a future release, since he wasn't sure "what the right solution would be" in September.  I hope this helps.

**Comment by atsawin** [comment]
I have similar problem in #4141 and manage to fix it with following patch. (It's against v4.0.2.)

```
--- a/select2.js    2016-03-09 08:33:38.000000000 +0700
+++ b/select2.js    2016-05-04 10:38:22.605348402 +0700
@@ -896,7 +896,7 @@
     var $loading = this.option(loading);
     $loading.className += ' loading-results';

-    this.$results.prepend($loading);
+    this.$results.html($loading);
   };

   Results.prototype.hideLoading = function () {
```

**Comment by StrikerTwo** [comment]
We got hit by this as well. @atsawin 's patch works for us.
Please consider including this in select2. If you have more than 10 options in your dropdown, you won't see the "loading..." hint anyway if it's prepended at the top.

**Comment by joaopgg** [comment]
Hi guys. Do we have any updates on this issue?

**Comment by bioworkflows** [comment]
This issue has not been fixed. Please re-open it.

Edit: @atsawin 's patch actually works. We need a PR.
