### ISSUE TITLE
select2 4.0.3 Search box is disabled 

### ISSUE THREAD

**Issue by jackryu** [select2/select2#4871]
Red Highlighted box is disabled in select 2  4.0.3 ver.

![image](https://cloud.githubusercontent.com/assets/6933841/25189415/b4ae5c14-2546-11e7-9e26-88520a1d54c7.png)

**Comment by jackryu** [comment]
Its Work : https://github.com/select2/select2/issues/1576
http://stackoverflow.com/a/18487440/375551

**Comment by mazhisai** [comment]
while removing tabindex="-1" does make the search box editable, its not a solution because it now breaks the accessibility of my page. The modal window is no longer active and accessible from keyboard. whats worse, the parent window can be tabbed into. is there an alternative solution here that doestn break accessiblity? thanks!

**Comment by jackryu** [comment]
I am facing same issue please any one can suggest other solution.

**Comment by jackryu** [comment]
please help.

**Comment by ProgrammingTestGitHub** [comment]
Another solution for the problem is to define the parameter "DropdownParent" of the select2 element. The name given to the parameter is the name of the modal form where the select2 is placed on. Here below an example of how to use this parameter.

$(document).ready(function() {
  $("#select2insidemodal").select2({
    dropdownParent: $("#myModal")
  });
});

https://stackoverflow.com/questions/18487056/select2-doesnt-work-when-embedded-in-a-bootstrap-modal

**Comment by alexweissman** [comment]
This is now documented: https://select2.org/troubleshooting/common-problems#select2-does-not-function-properly-when-i-use-it-inside-a-bootst

**Comment by ridho-pratama-putra** [comment]
thanks alot guys. dropdownParent solve my problems

**Comment by Zombaya** [comment]
I know I'm late at the party, but I managed to solve this issue globally by using the function shown below.  I'm leaving it here as a reference to other people who stumble upon this problem.

It fills in the dropdownParent-value if `select2()` is trigged on an element that has a parent with the class `modal`.

```javascript
(function(){
    var oldSelect2 = jQuery.fn.select2;
    jQuery.fn.select2 = function() {
        if (typeof arguments[0] === 'object' && typeof arguments[0].dropdownParent !== 'defined') {
            const modalParent = jQuery(this).parents('.modal');
            if (modalParent) {
                arguments[0].dropdownParent = modalParent;
            }
        }
        oldSelect2.apply(this,arguments);
    };
})();
```

**Comment by Zombaya** [comment]
I know I'm late at the party, but I managed to solve this issue globally by using the function shown below.  I'm leaving it here as a reference to other people who stumble upon this problem.

It fills in the dropdownParent-value if `select2()` is trigged on an element that has a parent with the class `modal`.

```javascript
(function(){
    var oldSelect2 = jQuery.fn.select2;
    jQuery.fn.select2 = function() {
        if (arguments.length === 1 && typeof arguments[0] === 'object' && typeof arguments[0].dropdownParent !== 'defined') {
            const modalParent = jQuery(this).parents('div.modal').first();
            if (modalParent.length > 0) {
                arguments[0].dropdownParent = modalParent;
            }
        }
        return oldSelect2.apply(this,arguments);
    };
})();
```

**Comment by influxpatrick** [comment]
dropdownParent  worked for me.. Thanks guys

**Comment by KimvdLinde** [comment]
For those that had an issue with it, but are reusing a module in different locations, you can attach the dropdownParent to the div encapsulating the select2, and then it works properly at all locations you use it, whether in the modal or the page.

**Comment by Abusiddiq18** [comment]
dropdownParent worked for me.. Thanks

**Comment by freilinjb** [comment]
> Otra solución para el problema es definir el parámetro "DropdownParent" del elemento select2. El nombre dado al parámetro es el nombre de la forma modal donde se coloca el select2. A continuación se muestra un ejemplo de cómo utilizar este parámetro.
> 
> $(documento).ready(function() { $("#select2insidemodal").select2({ dropdownParent: $("#myModal") }); });
> 
> https://stackoverflow.com/questions/18487056/select2-doesnt-work-when-embedded-in-a-bootstrap-modal

Gracias por la ayuda!!

**Comment by mudassarbutt7372** [comment]
Yes, Broo it's Working. And I face this issue. Thanks, bro.

**Comment by mudassarbutt7372** [comment]
**Solution is this**

Another solution for the problem is to define the "DropdownParent" parameter of the select2 element. The parameter's name is the modal form on which it is placed. Below is an example of how to use this parameter.

$("#yourdropdown").select2({
dropdownParent: $("#yourModal")
});
