### ISSUE TITLE
Programmatically associate additional data with dropdown items

### ISSUE THREAD

**Issue by Spongman** [select2/select2#4877]
in v3 there was $().select2("data", { ... }); for programmatically setting the selection along with any custom data required for rendering.

what's the equivalent in v4?

**Comment by William-H-M** [comment]
Hi, can you please refer to #4801 there are two solution about it

**Comment by Spongman** [comment]
Yeah neither of those solutions at relevant. The 2nd is pre-v4, and the first only allows setting the id & text values in the data. (I mentioned "custom data" in OP)

**Comment by William-H-M** [comment]
Hi, I didn't see the thing about custome data but if not should be [this](https://select2.github.io/options.html#query) and this about the [data](https://select2.github.io/options.html#data)

there's [this post](http://stackoverflow.com/a/31254054) on SO that can help

#2658 kinda says the same but not sure if still avalaible

**Comment by alexweissman** [comment]
Please continue any further discussion of this issue in #5036.
