### ISSUE TITLE
Using allowClear with multi-select causes the placeholder to be added as a selection

### ISSUE THREAD

**Issue by vbjay** [select2/select2#4880]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue
https://jsfiddle.net/zmtq7an8/

## Expected behavior and actual behavior

When I follow those steps, I see...

- The dropdown shows when I click the clear widget.
- The Placeholder option is shown as selected after the process instead.  
![image](https://cloud.githubusercontent.com/assets/3629489/25310615/abb33d7e-27b6-11e7-805f-c88eab91d976.png)
I was expecting...
- The clear widget to not drop down the selection area.
- The empty placeholder to not be selected when a new item is selected.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.2.1 and 3.1.1
- Select2 version: 4.0.3

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other plugins
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by William-H-M** [comment]
Hi, for this to be done just remove your empty option and it'll work

**Comment by vbjay** [comment]
Don't think you understand how allowClear works. Read the documentation.

**Comment by vbjay** [comment]
https://select2.github.io/options.html

**Comment by vbjay** [comment]
https://select2.github.io/examples.html

**Comment by William-H-M** [comment]
Hi,
1) Did you at least try it out?
2) Please don't do too many comments for something that can be done throught an edit
3) As for your asking if I've read documents, yes I do, here's the page that you [reference it](https://select2.github.io/options.html#allowClear)
and the placeholder one where [allowClear ](https://select2.github.io/examples.html#placeholders)is show too, on the example page when you set up allow clear the dropdown is going to be show.
4) The only thing you need to do was remove the empty option of your selectList then in your JavaScript just leave it as is, here a little [fiddle ](https://jsfiddle.net/vpwz6t3j/1//)if you just don't believe me

**Comment by vbjay** [comment]
The empty item is fixed.  The dropdown showing on clear is not.

**Comment by William-H-M** [comment]
Hi, about when clear the dropdown showing this is by default because the allowClear trigger a focus on the select, if not wrong, I tried to attach an event to the clear control but I wasn't able to do even a simple console.log when it was clicked it looks like the code itself remove any other code when this is clicked 
the control itself it's 
```
$('.select2-selection__clear').click(function(e) {
  e.preventDefault();
  console.log('clicked!!!');
});

```

I'm not sure how to avoid it, for that I suppose that you need to open a new ticket or a new pull request making a new option or something, sorry if it's not of much help

**Comment by jpgilchrist** [comment]
I actually noticed this behavior with slightly different click stream. I had a few items selected and when I hit backspace, instead of deleting one character it just removed them all and then continued with the same behavior you mentioned. It's reproducible in your jsfiddle as well. 

Select some then hit backspace. Also, if you simply click off of the select2 after hitting backspace or clear, it shows some weird behavior as well.

**Comment by jpgilchrist** [comment]
But @vbjay you really should update the title of this.... Your description is good but the title is not.

**Comment by vbjay** [comment]
The behavior is not what is expected or off from what is expected. I am not
going to hunt for the right title.

**Comment by vbjay** [comment]
Thanks for the backspace info.

**Comment by William-H-M** [comment]
Hi, @jpgilchrist at the weird behavior do yo mean that when clear and trying to click outside or down the select it won't close the box, at least click on the same level or above itself? if yes, if not worng that's intended too, why? not sure tbh.

and about the behaviour of the backspace that's intended too, but you can change it if you want, [in this line ](https://github.com/select2/select2/blob/master/dist/js/select2.js#L1815), and as you can see the same will happen if DELETE is pressed, both can be commented if need it

**Comment by jpgilchrist** [comment]
@William-H-M If it's as designed then I think it was an oversight in the design; because you are right if you simply remove to empty `<option></option>` it works perfectly fine. 

In my opinion there are two things going on here:
* when there's an empty `option` in the `select` then when you hit delete or backspace (doesn't matter - as you pointed out they do the same thing) it adds some bad formatting

before:
![image](https://cloud.githubusercontent.com/assets/5065660/25586526/aaff0e40-2e6d-11e7-99e0-830d5406eb6c.png)

after clearing (i.e., backspace, delete, or clicking the clear 'x')
![image](https://cloud.githubusercontent.com/assets/5065660/25586554/c9797eb4-2e6d-11e7-8fba-4ba65b8e4e2a.png)

* it seems as if it's actually selecting the empty option on clear, which is why when you then subsequently select another option it ends up in this state

![image](https://cloud.githubusercontent.com/assets/5065660/25586580/f43dbe9e-2e6d-11e7-9b3b-c605f31de08c.png)

**Comment by jpgilchrist** [comment]
Okay I was able to narrow this down in the code:
* in MultipleSelection.prototype.update function simply adding
``` javascript
if (!selection.id) {
  continue;
}
``` 
to the for loop fixes the issue of having the invalid first option (see last screenshot)

* Adjust search placeholder width in Search.prototyp.resizeSearch
```javascript
if (this.$search.attr('placeholder') !== '') {
  width = this.$selection.find('.select2-selection__rendered').innerWidth() - 40; // to adjust for the x (clear all option)
} ...
```

The above is really terrible, maybe should do something like `... - ( 10px /* for margin */  - 1em /* width of the clear icon */;`

However, there's one thing I can't nail down. When creating a brand new instance of a MutliSelection then how does the data get applied originally. It does not call the update function, which, therefore, means that my change isn't applied during the initialization. I'm not super familiar with the code and couldn't find it with the amount of time I was willing to dedicate to this right now.  I figured you might know off the top of your head and could point me in the right direction.

**Comment by alexweissman** [comment]
Related to #3335 - not sure if this a duplicate or just another manifestation of the same bug.

**Comment by baerrach** [comment]
This looks like a duplicate of #5060 rather than the backspace bug of #3335

**Comment by alexweissman** [comment]
@kevin-brown explained this in more detail in https://github.com/select2/select2/issues/4366#issuecomment-220324441:

> For placeholders on multiple selects, if you set the `id` of the placeholder to `null` (during initialization, not on the `<option>` which shouldn't exist) then you can get around this issue.

Seems like a poor workaround, though.

**Comment by shehzadev** [comment]
Hey! @vbjay try this

`<select data-placeholder="Select a number..." multiple="multiple" style="width:221px;">
        <option></option>
        <option value="1">One</option>
        <option value="2">Two</option>
        <option value="3">Three</option>
    </select>`

**Comment by Erisbv** [comment]
`if($_this.data('placeholder')){
                        placeholder = $_this.data('placeholder')
                    }

                    $_this.select2({
                        language: "pt-BR",
                        dropdownParent: dropdownParent,
                        placeholder: placeholder
                    });`

**Comment by Erisbv** [comment]
Add Data Attribute 
<code>if($_this.data('placeholder')){ placeholder = $_this.data('placeholder');}</code>
<code>$_this.select2({placeholder: placeholder});</code>

**Comment by borakayalar** [comment]
I found another way, when I attach to select2 to dom than 
$('.select2-search__field').width('100%') change to width style with it $('.select2-search__field').width('100%') 

My Code : 
`
function setSelect(select, data, placeholder) {
    select.each(function () {
        let $this = $(this)
        $this.wrap('<div class="position-relative"></div>')
        $this.select2({
            placeholder,
            allowClear: true,
            dropdownParent: $this.parent(),
            dropdownAutoWidth: true,
            data
        })
    })
    $('.select2-search__field').width('100%')
}
`
