### ISSUE TITLE
"Searching..." message should not display if previous search returned results

### ISSUE THREAD

**Issue by Spongman** [select2/select2#4884]
now in v4, with ajax requests, the "Searching..." label appears directly under the search text box pushing the currently loaded search results down, when the ajax request completes the "Searching..." label vanishes making the results jump up. if you type slightly slower than the ajax request completes, then the results jump up and down annoyingly after each keypress.
https://select2.github.io/examples.html#data-ajax

this wasn't an issue with pre-v4 select2. the "Searching..." label didn't appear if there were results already in the list.
http://select2.github.io/select2/#ajax

**Comment by jasonl99** [comment]
Same problem for me.

**Comment by alexweissman** [comment]
I think it's good to have some feedback that Select2 is waiting for a result set, so I wouldn't necessarily suggest that we hide it altogether just because some results were matched previously.

A better approach would be to use some kind of layering or tooltip to show the "searching" message without changing the position of the result set.
