### ISSUE TITLE
How to add Delay to keydown event ?

### ISSUE THREAD

**Issue by ghost** [select2/select2#4914]
Select2 is slow when typing keywords if the select has a fair number of items.
Maybe everytime keydown event runs searching.
I want to insert like ```setTimeout```

**Comment by alexweissman** [comment]
For large numbers of items, you may want to consider using a remote data source with [server-side pagination](https://select2.org/data-sources/ajax#pagination).

**Comment by KasemOmary** [comment]
True that pagination is a good idea - but the number of people using a rock or a potato as a computer is ... fairly decent.  Callbacks to the server will not do the UX for said users much help ;  they will still experience input/update delays on their end.  Working on the client end is, perhaps, a better solution for said user.  In my case, this is a couple dozen entries.  Not exactly a book.

**Comment by alexweissman** [comment]
I've seen some other issues about [performance in v4](https://github.com/select2/select2/labels/performance).  At the time I just assumed that these were limited to cases where the developer made a bad decision to render thousands of entries at once.  But now that you say:

> In my case, this is a couple dozen entries causing UX sluggishness.

I am more concerned about the issue.  It might be worth digging into the underlying causes of the performance problems in Select2 v4, rather than using a keydown delay as a workaround.

> I am forking the project to create a version which supports timeouts. Consider the suggestion for inclusion within the primary project.

I believe the term for this is "pull request" 😉

**Comment by KasemOmary** [comment]
"Technically" I did do a fork, as I need this working now.  I'll get a pull request for the primary release in as soon as I'm done with testing my modification out.  So far, it's looking nice.

**Comment by KasemOmary** [comment]
https://github.com/select2/select2/pull/5082

**Comment by KasemOmary** [comment]
I have a working addition to address this made - however I'm having some difficulty grabbing options. 

![image](https://user-images.githubusercontent.com/3031521/31676540-f7186b4e-b335-11e7-80c8-a8c973dba922.png)

    this.$search.on('keyup input', function (evt, options) {
        var timeout = options;
        timeout = 1000; // <= Need this. 
        if (timeout > 0) {
            if (this.SearchTimeout != null) {
                clearTimeout(this.SearchTimeout);
            }

            var param = { self: self, evt: evt };
            var s2Timeout = function () {
                this.self.handleSearch(this.evt);
            };
            this.SearchTimeout = setTimeout(s2Timeout.bind(param), timeout);
        } else {
            self.handleSearch(evt);
        }
    });

Is there a way to grab data from options.get(); within a triggered event?   Soon as that's resolved - this is a fully working addition to address to this issue.  

Thanks

**Comment by alexweissman** [comment]
what does the `options` object currently contain?

**Comment by KasemOmary** [comment]
Nothing at all, at the moment ; simply a placeholder for my intentions for functionality.  

I'd need to bind something from where the function is declared to get useful data in there.  Ideally, the setting which designates a timeout length from options.get('searchTimeout')  //or whatever the new option should be called. 

Trying to find out if there's a better/existing way of accomplishing getting those options rather than me getting it done by any means necessary.

**Comment by alexweissman** [comment]
I honestly have no idea - you're probably more familiar than I am with the codebase (I'm not the author and I only started helping out around here a few months ago).

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused to fix some major UI bugs (that are majority of issues and PR's). But if you open a PR with unit tests, I will be glad to review and approve if everything is ok :+1:
