### ISSUE TITLE
How do I put the selected tags outside of the input box? select2-selection__choice

### ISSUE THREAD

**Issue by enteeee** [select2/select2#4996]
I want to show the tags bottom of the inout text, is there anyway to get the selected values and display outside of the box, meanwhile it should keep the same actions. 

Attached the expected results screenshot.
<img width="555" alt="screen shot 2017-07-25 at 2 57 35 pm" src="https://user-images.githubusercontent.com/16496970/28559615-d22b4172-7149-11e7-9f17-e9961236419a.png">

Can anyone help me please. :)

**Comment by enteeee** [comment]
<img width="555" alt="screen shot 2017-07-25 at 2 57 35 pm" src="https://user-images.githubusercontent.com/16496970/28559580-a3d236aa-7149-11e7-8157-170f2a488e03.png">

**Comment by alexweissman** [comment]
I'm going to mark this as a feature request, but to be honest it's probably out of the scope of built-in features for Select2.  You should instead use the `select2:select` event on a single selection box to create/remove the selection items.

This is actually very similar to what we do in UserFrosting with our `ufCollection` widget, except we add a row to a table instead of a "badge".  See the demo here: https://learn.userfrosting.com/client-side-code/components/collections#many-to-many

The code for this widget is available here:
https://github.com/userfrosting/UserFrosting/blob/ed88feb37a88c75b84181d5c311fef0a42db2652/app/sprinkles/core/assets/userfrosting/js/uf-collection.js#L120-L125

Hopefully you can reverse-engineer that to get what you need.

Also, you've misspelled "monogamous" 😉

**Comment by F-Tahir** [comment]
@enteeee I'm wondering if you managed to figure this out? Also run into the same problem and can't quite figure out how to apply @alexweissman's solution to Select2.

**Comment by enteeee** [comment]
I put back the options inside, Im closing this issue.
