### ISSUE TITLE
Select2 jquery code apply over select box after Save Menu item in wordpress

### ISSUE THREAD

**Issue by rerraw** [select2/select2#5016]
I have WordPress theme I added the new select box field, based on the select2 plugin style. Now explain my problem based on the Numbers on image below

1- add new menu item
2- Menu added to the menu item list - The new item contains select box based on select2 plugin
3- As see the select box show as normal multiple HTML select box and not show as in select2 plugin
4- But after click on Save Menu item and reload the page the select box show as multiple select box as in select2 plugin
5- As see after saving menu item the select box changed to multiple select2 box

Why don't apply the jQuery select2 code directly before saving menu item? 
How can I do that until before saving menu item directly show my select box as the select2 box?

![ddd](https://user-images.githubusercontent.com/6832360/29498111-399a0dd4-85fe-11e7-925b-bf09c4d59b6c.jpg)

My jQuery select2 code that I applied over the select box within menu item

`$(".bsnselect").select2();`

Also, I registered the select2 plugin files in my WordPress theme as below

```php 
function YPE_bsn_backend() {
    wp_enqueue_script( 'select2-js', plugins_url( '/js/select2.min.js', __FILE__ ), array( 'jquery' ), null, true );
}
add_action( 'admin_enqueue_scripts', 'YPE_bsn_backend' );

function YPE_bsn_backend() {
    wp_enqueue_style( 'select2-css', plugins_url( '/css/select2.min.css', __FILE__ ) );
}
add_action( 'admin_enqueue_scripts', 'YPE_bsn_backend' );

**Comment by alexweissman** [comment]
This is likely due to the way you are integrating Select2 into the rest of your code.  When you dynamically generate your new `<select>` element, you need to call `.select2()` on that new element.

Simply having a generic `$(".bsnselect").select2()` randomly placed in your code will not initialize Select2 on new, dynamically created elements.

At any rate, this is more of a generic question/lack-of-understanding about Javascript and asynchronous programming.
