### ISSUE TITLE
Execution should halt if Select2 instance is null

### ISSUE THREAD

**Issue by plqplq** [select2/select2#5073]
The following was add to the ret = line:

    if (instance) 

        this.each(function () {
          var instance = $(this).data('select2');

          if (instance == null && window.console && console.error) {
            console.error(
              'The select2(\'' + options + '\') method was called on an ' +
              'element that is not using Select2.'
            );
          }

    **          **if (instance)** ret = instance[options].apply(instance, args);**
        });

Without that, we get a javascript error

In version 404 this is line 6417

**Comment by alexweissman** [comment]
I'm sorry, could you explain this further?  Also, not sure if you are aware, but GitHub lets you link to specific lines of code.  So rather than say:

> In version 404 this is line 6417

It would be easier for others if you could link directly to that line.

**Comment by plqplq** [comment]
sorry I'm newish to Github. We hit a scenario where the variable instance came back as null or undefined from this statement 

      var instance = $(this).data('select2');

Then the line down below breaks with a null reference exception:

    ret = instance[options].apply(instance, args);

So changing it to this seems to fix it with no ill effects

    if (instance) ret = instance[options].apply(instance, args);

Its not obvious to me how to find that line of code since I have a select2.full.js here whereas the git entries appear to be a number of smaller files.

**Comment by alexweissman** [comment]
So actually, you can use GitHub's search to search for entire lines of code.  Plugging that line into search yields this: https://github.com/select2/select2/blob/062c6c3af5f0f39794c34c0a343a3857e587cc97/src/js/jquery.select2.js#L37

The repo actually consists of a number of smaller components (which is considered a best practice for any piece of software; see the [single-responsibility principle](https://en.wikipedia.org/wiki/Single_responsibility_principle)).  These then get compiled into the monolith distribution files.

Anyway, I'm confused though by the debugging block above:

```
      if (instance == null && window.console && console.error) {
        console.error(
          'The select2(\'' + options + '\') method was called on an ' +
          'element that is not using Select2.'
        );
      }
```

I can't imagine under what conditions that `window.console` and `console.error` are _not_ defined.  What browser are you using?  It might be better to get the Javascript error when `instance` is null and the console is unavailable, rather than silently skipping the `.apply` call.

Anyway, welcome to open source!

**Comment by plqplq** [comment]
We mainly test with firefox and internet explorer, but also edge and chrome. Most often we'll run in internet explorer since that allows native JS debugging, so we might not (or might) have tested this specific error in the others.

If I get some time in the next few days I'll try to catch the error in the debugger, and then I'll update here.

Thanks for the explanations - makes sense :)

**Comment by plqplq** [comment]
OK that was easier than I thought - the error happens in IE and firefox and console.error does not stop execution in either case. So it does enter that IF but it doesn't stop the following ret= assignment line from being executed.

**Comment by plqplq** [comment]
This fiddle shows that console.error doesn't stop execution (I initially thought it might be our "window.onerror" handler, but no, it always doesn't stop execution)

https://jsfiddle.net/c0kmhdpc/1/

**Comment by alexweissman** [comment]
Thanks for looking into this.  Yeah, it's unclear whether execution should be manually halted in that check, since it will halt anyway when it fails the dereference (as you pointed out).

We do actually have a method for determining if Select2 is initialized already: https://select2.org/programmatic-control/methods#checking-if-the-plugin-is-initialized

I'm not sure which method is preferable though, yours or the one we have documented.

**Comment by plqplq** [comment]
I suppose you could change it to a throw? Which is what we do.. but I guess you want to be consistent with the rest of the product.

      if (instance == null && window.console && console.error) {
        throw 
          'The select2(\'' + options + '\') method was called on an ' +
          'element that is not using Select2.'
        ;
      }

Although execution "halts" - it raises an error unnecessarily in the case of ele.select2("close") since there's nothing to do. So its a shame to half execution of the callers product when all you need to do is return early. Which is another possible fix:

      if (instance == null && window.console && console.error) {
        console.error(
          'The select2(\'' + options + '\') method was called on an ' +
          'element that is not using Select2.'
        return;
        );
      }

Anyway, now we have a workaround, we're ok, but you might want to apply one of the fixes anyway.

thanks for helping 👍

**Comment by alexweissman** [comment]
> it raises an error unnecessarily in the case of ele.select2("close") since there's nothing to do.

That's true.  This is a pretty generic issue that applies to any jQuery plugin, though.  I'd be interested in knowing how other popular jQuery plugins behave when you call a method before the plugin has been initialized on a selector.  Perhaps there is some kind of standard for this?

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused now to fix UI bugs. But if you open a PR with unit tests, I will be glad to review and approve if everything is ok.
