### ISSUE TITLE
Search event has multiple calls

### ISSUE THREAD

**Issue by coron3r** [select2/select2#5102]
If using a custom matcher, one ends up with multiple event calls. Those calls match the number of option a select has. Is this something that is a implemented for a reason? I find it as a bug.

Here is a jsbin url [http://jsbin.com/dolovokipu/edit?html,js,console,output](http://jsbin.com/dolovokipu/edit?html,js,console,output) where you can see that the console produces 3 outputs when typing  in the search bar.

Thank you!

**Comment by alexweissman** [comment]
I believe that this has been fixed in the [latest pre-release](https://github.com/select2/select2/releases/tag/4.0.6-rc.0).  See http://jsbin.com/firikogafa/edit?html,js,console,output I see that I haven't updated the JSBin template to reflect that new release, so thank you for bringing this to my attention.  I will update that now.
