### ISSUE TITLE
select2.min.js:1 Uncaught TypeError: c.ajax is not a function

### ISSUE THREAD

**Issue by SamsadSajid** [select2/select2#5177]
I got this error from Inspect Element of Google Chrome's dev console.
The error is:

> select2.min.js:1 Uncaught TypeError: c.ajax is not a function
>     at Object.transport (select2.min.js:1)
>     at d (select2.min.js:1)
> transport @ select2.min.js:1
> d @ select2.min.js:1
> setTimeout (async)
> d.query @ select2.min.js:1
> a.query @ select2.min.js:1
> j @ select2.min.js:1
> (anonymous) @ select2.min.js:1
> d.invoke @ select2.min.js:1
> d.trigger @ select2.min.js:1
> e.trigger @ select2.min.js:1
> (anonymous) @ select2.min.js:1
> d.invoke @ select2.min.js:1
> d.trigger @ select2.min.js:1
> c.handleSearch @ select2.min.js:1
> j @ select2.min.js:1
> (anonymous) @ select2.min.js:1
> dispatch @ jquery-3.1.1.slim.min.js:3
> q.handle @ jquery-3.1.1.slim.min.js:3
There is nothing about this on any issues or forum or in the documentation page

**Comment by alexweissman** [comment]
This issue does not appear to conform to our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Please re-read the contributing guidelines _carefully_ and then edit your question.  Once your issue complies with the guidelines, we can reopen it.

**Comment by SamsadSajid** [comment]
Hello,
The thing is I couldn't find anything about this problem in your Documentation, Forums, nor in any closed or open issues. 
Could you kindly take a look?

**Comment by alexweissman** [comment]
Right, so that doesn't necessarily mean that the next step is to open a new issue.  And, if you do open a new issue, you need to follow the rules:

## Asking for Help

In general, the Github issue tracker should **only** be used for **bug reports** and **feature requests**.  If you're just having trouble getting something to work, you should ask in the [forums](https://forums.select2.org) or on [Stack Overflow](https://stackoverflow.com) instead. 

...

5. **When possible create and link to a [minimal, complete, and verifiable](https://stackoverflow.com/help/mcve) example by cloning our [JSBin template](http://jsbin.com/hojajiwoye/edit?html,js,output). Code dumps, zip files, etc are NOT acceptable.**
6. **Include relevant screenshots or animations, if possible. Drag your screenshots directly into the forums or issue tracker text box. They will automatically be uploaded and the Markdown to display them will be generated.  Avoid third-party image hosts, or links which require extra clicks to view the image (except IRC, where this is unavoidable).**
