### ISSUE TITLE
support ie8?

### ISSUE THREAD

**Issue by a51764579** [select2/select2#5188]
I see the plugin support ie8+,can it support ie8?

**Comment by SgtOddball** [comment]
I'm not so sure anymore, the worlds moved on alot since 2009 and considering it's no longer supported AT ALL by Microsoft, I'd recommend that any efforts to support IE8 as wasted. If IE8 support was required by your project I'd take a lot of time and effort to educate users as to why it would most wise to move to something newer. 

If you really HAD to support IE8, then a previous version of Select2 might be more suited (3.5 for example).

**Comment by alexweissman** [comment]
This issue does not appear to conform to our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Please re-read the contributing guidelines _carefully_ and then edit your question.  Once your issue complies with the guidelines, we can reopen it.
