### ISSUE TITLE
Add Option maximumInputLength

### ISSUE THREAD

**Issue by deeky666** [select2/select2#519]
Hi guys,

it would be nice to have an option to limit the search term to a certain number of characters. I currently have a situation where I need the user to type in exactly 9 characters, not more, not less to load result data from a query function. It should behave like input's maxlength attribute

I took the example from http://ivaynberg.github.com/select2/#data and modified the query function to my needs:

<pre>
 $("#e5").select2({
    minimumInputLength: 9,
    query: function (query) {
        var data = {results: []}, crossfoot = 0, multiplier, product, i;

        for(i = 7; i >= 2; i--) {
            multiplier = i % 2 == 0 ? 2 : 1;
            product = String(parseInt(query.term[i]) * multiplier);
            crossfoot += parseInt(product) > 9 ? product[0] + product[1] : parseInt(product);
        }

        // Validates query term and pushes result only if valid
        if(crossfoot % 10 == parseInt(query.term[8])) {
            data.results.push({id: query.term, text: query.term});
        }
                
        query.callback(data);
    }
});
</pre>

What do you think?

**Comment by crusy** [comment]
This doesn't prevent the additional characters from being entered, it displays a message "Please delete X characters" instead. While this may be desired in certain situations, it differs from how `<input type="text" maxlength="20">` works... so in order to have a consistent UI it would be preferable to just limit the input instead of showing some message

**Comment by NelGarbuzova** [comment]
This is not fixed yet. maxLength attribute not appears on input. Need to reopen the issue.
