### ISSUE TITLE
Feature: Selectable <optgroup>

### ISSUE THREAD

**Issue by thejae** [select2/select2#520]
Taking the example of your demo, i'd like to know if it's possible to select the parent category "Alaskan/ Hawaiian Time Zone"

EDIT
I am not looking to auto select every options from the optgroup, I just want to select the optgroup label itself.

**Comment by thiagoponte** [comment]
Any news on this issue? I'm using select2 3.5.2 and the problem persists.
I cannot select the optgroup, already added id and value.

**Comment by Karzin** [comment]
Same problem here

**Comment by sheparddw** [comment]
Same problem here. It would be great to have the option to select an optgroup as an option.

**Comment by kevin-brown** [comment]
There is a technical barrier here that Select2 will likely never be able to tackle: A standard `<optgroup>` is not selectable in the browser.

The best possible solution is to [have an `<option>` for selecting the group](http://stackoverflow.com/q/9892247/359284), like you would have with a standard select. Without an `<option>` tag, it's not possible to set the selected value to the group (as the value doesn't actually exist). Select2 even has a `templateResult` (`formatResult` in 3.x) so you can style it as a group consistently across browsers.

But the main request here (a selectable `<optgroup>`) [is not possible](http://stackoverflow.com/q/9892247/359284), you can only select an `<option>`. Because of that, I'm closing this feature request.

**Comment by minlare** [comment]
This makes sense to not allow when converting from html <select>, but should be possible when loading remote data.
