### ISSUE TITLE
jQuery deprecation

### ISSUE THREAD

**Issue by actricom** [select2/select2#5228]
Hi

jQuery are deprecating a couple of functions currently used in select2: (.camelCase and .isFunction) as noted here: [http://blog.jquery.com/2018/01/19/jquery-3-3-0-a-fragrant-bouquet-of-deprecations-and-is-that-a-new-feature/].
Is this something to worry about?

**Comment by davilious** [comment]
For the context, it happens when using jQuery 3.x  and use the [jquery-migrate.js](https://github.com/jquery/jquery-migrate) plugin to know the breaking changes.

When using Select2 and jQuery 3.x, the jquery migration plugin give us some more **deprecations** warnings, such as:

- [jQuery.fn.click()](https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryfnclick-event-shorthand-is-deprecated) event shorthand is deprecated, it also applies to event `focus`, there is a bunch of these in select2.js .

- [ jQuery.fn.offset()](https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryfnoffset-requires-an-element-connected-to-a-document), there are some in select2.js.

![captura de pantalla 2018-08-30 a las 12 29 57](https://user-images.githubusercontent.com/950504/44846367-70862200-ac50-11e8-90a2-0bf37c5fd1f7.png)


Acording to the documentation:

> Items listed as deprecated and removed must be changed before the code will work properly without the Migrate plugin. Items listed as only deprecated are still supported by the current version but no longer considered a good practice

**Comment by kevin-j-morse** [comment]
Hopefully the @stale bot will re-open this issue? It is quite an annoyance when trying to bring a project up to jQuery 3.4 compatibility using the jQuery Migrate tool.
