### ISSUE TITLE
Feature: Optgroup + Tagging

### ISSUE THREAD

**Issue by thejae** [select2/select2#524]
It would be nice to be able to categorize suggested tags while allowing the user to add custom tags. Right now it's either multi-list dropdown or tagging.

**Comment by ScottieR** [comment]
Just a note:  I'm able to get grouped tag results working...sort of.  Using format data: [ text: "Group1", children: [ { text: "First Child", id: "First Child"} ... ] ] 

The problem is that autocomplete / search is being performed on the group name instead of on the tag children themselves.  Perhaps this was fixed in the 4.0 milestone that @kevin-brown mentioned, but I haven't had time to upgrade versions yet.

**Comment by AminaG** [comment]
:+1:
