### ISSUE TITLE
Select2 Mulitple but not as tag like bootstrap-select

### ISSUE THREAD

**Issue by cromartie1984** [select2/select2#5359]
I can't find if it can be changed like this :+1: 
![38997831-97e12bbe-43ab-11e8-85f5-b8c05d91c7b1](https://user-images.githubusercontent.com/22010858/45180232-13273d80-b21b-11e8-905b-ddfacc6ed717.gif)

Instead of having **tags** for selected options, we could have **4,5,... options selected** in the selection div
It would be great, because sometimes you have too much options to select and it takes too much space.

**Comment by pedrofurtado** [comment]
We don't have plans to include this feature, we are focused in UI bug fixes. But I will be realy appreciate if you can open a PR with this feature, with support for I18n (because of the message "X are selected") and some unit tests. It should be a "configurated" feature. The user could pass a parameter indicating if he/she desire this feature or not.
I will close for now, but reopen when PR is done 👍
