### ISSUE TITLE
100+ Issues purged, new ownership?

### ISSUE THREAD

**Issue by jakeNiemiec** [select2/select2#5367]
Over the past 2 hours, 100+ issues have been closed or locked with this text:

> We don't have immediate plans to provide this. We are focused to fix some major UI bugs (that are majority of issues and PR's). But if you open a PR with unit tests, I will be glad to review and approve if everything is ok

In most cases, the content of the issue was ignored completely. (eg: requesting a demo for a confirmed bug that already had a demo:  https://github.com/select2/select2/issues/4740)

Help needed:
https://github.com/select2/select2/issues/3387
https://github.com/select2/select2/issues/3854
https://github.com/select2/select2/issues/1345
https://github.com/select2/select2/issues/3652

Confirmed bugs:
https://github.com/select2/select2/issues/4740
https://github.com/select2/select2/issues/4063

Issues tied to open PRs:
https://github.com/select2/select2/issues/3158
https://github.com/select2/select2/issues/4586

This reverts all of the tagging and organising work from @alexweissman. All of this, plus accidental merges into master (https://github.com/select2/select2/pull/5307) make me wary of the new ownership. Was there an announcement I missed?

**Comment by jonahgreenthal** [comment]
Seconded. @pedrofurtado may have the best of intentions, but this really isn't an okay way to maintain a project.

**Comment by Chealer** [comment]
Thank you @jakeNiemiec. I looked at a random ticket, #4740 and while I won't comment on intentions, I fully agree with @jonahgreenthal about this being unaccceptable.

I'd like to add that in the case I personally witnessed, #4661, there was not even an explanatory comment, and there still is none 2 weeks after I asked, which is not just inappropriate, but downright insulting.

[This is my last contribution to this project](http://www.philippecloutier.com/blogpost92-Selected-Select2-Better-go-with-option-2), and I no longer support Select2 in any way.

**Comment by karolyi** [comment]
Wow this was unexpected. So I guess select2 is no longer a viable option for HTML-supporting select widgets. At my first googling, https://github.com/selectize/selectize.js came up as an alternative, but I'm open to suggestions. Anyone?

**Comment by Chealer** [comment]
@karolyi I haven't evaluated the situation in the last 2 years, but at least Chosen should be part of your consideration.

**Comment by jakeNiemiec** [comment]
I'm sad to see this project end like this.

**Comment by jonahgreenthal** [comment]
Ironic.

This might be a good place for @kevin-brown to give an update on the current status of Select2 and general plans for the short and medium term. (Have I missed such an update somewhere else?) Clearly things have picked up recently, and I'm thrilled about that, but I'm also not clear on where they're headed, and I think everyone would benefit from knowing.

**Comment by jakeNiemiec** [comment]
If @kevin-brown ends up reading this, please understand that there are no pitchforks being waved in your direction, **FOSS maintenance is a thankless job and I am thankful for all of the free work you have done for us**. Just realize that there have been several instances of GitHub repos becoming compromised after being passed off to 3rd parties.

I want to point out to those in this thread that the issues linked above have been re-tagged but not reopened. It's at least good to see PRs flowing again.

**Comment by kevin-brown** [comment]
Hey, I get it. This repo has gone through some weird times in the last few years. Mostly because it was basically unmaintained for a large portion of that, and all of us disappeared off the face of the earth in between the changes.

----

So, let's quickly talk about the future.

I enabled [the Stale integration for GitHub](https://github.com/apps/stale) because, to be honest, this issue tracker was getting out of control. It's hard to jump back into a project when there are 300... 400... 500... 600 😞 open tickets, most of which haven't been triaged. So the best bet there was to automatically purge the old ones that haven't been kept up to date, and instead focus on the ones which have recent activity.

I have no interest in handing this project back off to a third party, both because of the security issues (which have been noted) and because this is a project that _drains you to work on_. I get an email around once a week offering to take over the project from people, many of of whom appear to have good intentions, that see that this project is dead. But for each of those emails I also get another 3 from people who are angry that this project is dead or that there is a bug.

My goal is to go back to taking this project slowly, instead of rushing to get a release out and burning out. There are bugs, _tons of them_, and my goal isn't to fix every one of them.

**4.1.0 isn't coming soon.** Every new feature that is accepted just increases the surface area of this plugin, and makes it more and more difficult to debug things and fix the more pressing issues. So the next few minor releases are going to be largely focused on fixing the bugs that exist. The ones that are easy to fix, or the ones that can be automatically tested so we don't have regressions later on, since those are the ones that I can throw a few hours at instead of a few days.

-----

As of this comment, there are 69 open tickets and 33 open pull requests. I've looked at all 33 pull requests during the original Stale period, but I still haven't looked at all 69 open tickets. FOSS is tough, and this project has been around for [a few years](https://github.com/select2/select2/commit/53e214d32f39ec78670ccf58df1536375bdf4112).

**Comment by Chealer** [comment]
I feel compelled to make a spontaneous comeback. First, thanks kevin-brown for taking the time to provide an explanation.

> Hey, I get it. This repo has gone through some weird times in the last few years. Mostly because it was basically unmaintained for a large portion of that, and all of us disappeared off the face of the earth in between the changes.
> 
> So, let's quickly talk about the future.
> 
> I enabled [the Stale integration for GitHub](https://github.com/apps/stale) because, to be honest, this issue tracker was getting out of control. It's hard to jump back into a project when there are 300... 400... 500... 600 disappointed open tickets, most of which haven't been triaged. So the best bet there was to automatically purge the old ones that haven't been kept up to date, and instead focus on the ones which have recent activity.


You **can** ignore "stale" tickets if you wish. You can also sort/prioritize tickets taking their "staleness" into account.
You **could also** ask to confirm that an issue persists if it is time-consuming to test yourself, and spend less time trying to infirm/confirm the more "stale" a ticket seems to be. You can also close an old ticket even if it may persist, as long as:
1. You indicate that you are closing the ticket because you presume the issue was solved.
2. You invite people who would experience the issue with a current version to reopen the ticket.

However, you **cannot** trash work from reporters just because there is a lack of triagers. In fact, disrespecting reporters is your best bet to turn potential triagers (and many more) away.

> I have no interest in handing this project back off to a third party, both because of the security issues (which have been noted) and because this is a project that _drains you to work on_. I get an email around once a week offering to take over the project from people, many of of whom appear to have good intentions, that see that this project is dead. But for each of those emails I also get another 3 from people who are angry that this project is dead or that there is a bug.


I am not sure what your point was, but you have to learn to deal with anger and negativity if you wish to contribute to social production projects. There is no guarantee that you will get more praise than criticism, in particular when you develop a behind-the-curtain project. You have to find the motivation by yourself, or to find a way to monetize. Nobody is forcing you to contribute, just like nobody is forcing us to contribute.
Sometimes, anger can be turned into a constructive energy and help with the underlying problems. In any case, everyone should respect others - those who write to you should be respectful, just like you should treat other contributors respectfully, independent of the pressure you feel. You know your value and should ignore disrespectful and non-constructive comments just like you ignore noise.

> [...]

Best success
