### ISSUE TITLE
add a on search event

### ISSUE THREAD

**Issue by abhijitgujar86** [select2/select2#5476]
add a search event trigger for the select so that can update the option from server based on the typed character/words something likfe google search dynamic and ajax based.

**Comment by Zohaad97** [comment]
@abhijitgujar86 Its already supported by select2. If you have a look on this [link](https://select2.org/searching) . There is a guide how would you implement this on your project.

You can change the styles by over riding CSS classes. 

Hope this helps

**Comment by kevin-brown** [comment]
Yeah, I'm going to close this off since this is usually handled either in the formatter, the matcher, or on the server side in the API.

---

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://select2.github.io/community.html
[irc]: https://select2.github.io/community.html
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes

**Comment by thekevincurtin** [comment]
Using the matcher does not work for this use case, since the matcher is evaluated for every single option in the dropdown

Is there an approach to execute only once for each typed input?  It seems like an adapter is needed but haven't been able to find an example for this case
