### ISSUE TITLE
Multiple instances uses same options

### ISSUE THREAD

**Issue by x-fusion** [select2/select2#5478]
Hello I have an form in which you can add as many _**select2**_ single select boxes as you want. It is done by cloning it, before cloning I do `$(".select.custom-select.select2-selection--single").select2('destroy');` and after cloning `$("select2.control").select2()`. Problem is that if I select option **A** in **select1** I cannot select it in **select3** or **select5**.. It's disabled option. It seems that all those instances are linked between.. :/ Any workaround or something I have missed?

**Comment by MarineDruet** [comment]
Hello,
I tried to duplicate your issue but did not manage to. 
Maybe if you use the destroy method on your original `<select>` and not on the `<span>` created by the select2 it would work better?
We will be able to help you more if you provide a snippet of you code.

**Comment by kevin-brown** [comment]
It sounds like you are calling `.select2("destroy")` on the selection element (generated by Select2) instead of on the original `<select>`. That would explain why things may not be getting cleaned up correctly.

-----

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://select2.github.io/community.html
[irc]: https://select2.github.io/community.html
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes

**Comment by Novelz** [comment]
Necroing to include some additional info.
The problem is related to the attribute `data-select2-id` given to the options of the select, even if I use the `destroy` method both the select and the options keep all of the select2 data bind to them.

If different options in different select have the same `data-select2-id` it's impossible to select the same value, the fastest way to solve this for me was to remove the attribute manually.

I'm currently using the 4.0.8v
