### ISSUE TITLE
add a maximum count threshold

### ISSUE THREAD

**Issue by mfrasca** [select2/select2#5503]
I am using select2 through django-select2.  I'm focusing on what that project calls 'model' widgets, where the matches come from a remote database.  my use case is in botanic taxonomy, where there's char sequences which are extremely frequent, and there's also sequences which are more rare.
it makes sense, in this case, if the framework would allow me specify a maximum result count below which my user can be interested in seeing the matches.  like they type `quin` and they see the 16 matches, but still after typing 'aceae' the framework says please be more specific, possibly informing me there's still 1300 matches.

**Comment by kevin-brown** [comment]
Unfortunately this is something which would need to be implemented on the backend. Since it's not something which we intend to implement on Select2 itself, I would recommend reaching out to the community to see if there is a recommended way that others have used.

----

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://select2.github.io/community.html
[irc]: https://select2.github.io/community.html
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes
