### ISSUE TITLE
Select2 does not display dropdown when select2 container is in full screen 

### ISSUE THREAD

**Issue by bhuneshwer** [select2/select2#5555]
Go to https://select2.org/searching

In the developer console execute below script : 
```
 var elem = document.getElementsByClassName('s2-example')[0];
    if(document.webkitFullscreenElement) {
      document.webkitCancelFullScreen();
    }
    else {
      elem.webkitRequestFullScreen();
    };

```
Select2 will move to full-screen mode. But dropdown options will not be displayed.
<img width="1280" alt="Screenshot 2019-07-08 at 7 12 08 PM" src="https://user-images.githubusercontent.com/7676665/60814994-5001ef00-a1b4-11e9-8b49-176286f4a0e5.png">

**Comment by kevin-brown** [comment]
The issue here is that you are requesting full screen for the outer element that contains the selection area (in this case, the example box). But when Select2 opens the dropdown, it is by default places outside of this containing element and instead appended to the body. Because of this, the dropdown is not visible in full screen mode because it is not contained within the element that is full screen.

You can fix this issue by setting the `dropdownParent` to the element that you are making full screen (or the element containing the selection) so it remains visible when the containing element is made full screen.

https://select2.org/dropdown#dropdown-placement
