### ISSUE TITLE
[Feature request] option to hide drop down list

### ISSUE THREAD

**Issue by KarstenHoehne** [select2/select2#5557]
When using the automatic tokenization feature (https://select2.org/tagging#automatic-tokenization-into-tags) it would be nice to have an option to hide the drop down list in order to get a functionality similar to this: https://material.angularjs.org/latest/demo/chips

without having to use yet another library, especially since the functionality is already almost completely provided by select2.

Currently it is possible to use css to get this behavior. Still having it as a cconfig option would be nice.

https://codepen.io/anon/pen/QXpdXV

```
$("#test").select2({
     multiple: true,
     tags: true,
     dropdownCssClass: 'bbbbbbbbbbbbbb' //requires select2.full.min.js
    });
```

```
.select2-dropdown.bbbbbbbbbbbbbb {
    display: none;
}
```

**Comment by kevin-brown** [comment]
De-prioritizing this for 4.0.x.

There are accessibility issues that need to be considered if and when this is implemented, since Select2 is primary a searchable dropdown and this removes the dropdown part of that. The example that was linked basically only implements the "tagging" functionality without any of the other things you would be looking for in a dropdown.
