### ISSUE TITLE
Input width defaults to 0.75em instead of 100%

### ISSUE THREAD

**Issue by mcandre** [select2/select2#5563]
With Bootstrap 4, select2's input box width is rendered as a teeny tiny 0.75em, instead of 100%.

**Comment by kevin-brown** [comment]
0.75em was intentionally chosen instead of 1em, because _most_ of the time people are writing full width characters. We're aware of this breaking down when full width characters are most/all of the search term, and we don't currently have a suggested way to work around this.

As noted in https://github.com/select2/select2/issues/4074#issuecomment-170588618, I would rather not have to automatically determine the size because we used to do that and it was honestly an inconsistent mess.
