### ISSUE TITLE
Bug when adding previously added, but cleared selections

### ISSUE THREAD

**Issue by sophanox** [select2/select2#5598]
Hey there,

I think I have found a bug whereby Select2 fails to take into account an already selected option, if that option has been selected before, then cleared and reselected. 

See the fiddle here: https://jsfiddle.net/gfk472au/6/

As you can see the 'select2/select' option is preselected. If you then press the light blue button, this clears the select2, then re-adds that already selected value. 

If you then search again for 'select2/select' and select it, it will add that same option again. So there's two identical options selected. Press the light green button and you'll see they both have the same IDs.

I guess the only work around at the moment would be to recreate the select2 each time.

Thanks for looking into it!

**Comment by kevin-brown** [comment]
https://jsfiddle.net/ah7sedyc/

Calling `.val()` does not remove the previously existing `<option>` elements, so when you clicked the button is would duplicate them. When you selected the result in the dropdown, it would automatically select both of the `<option>` elements that existed, which is why you were seeing this behaviour. Calling `.clear()` instead/as well fixes the problem for you.

---

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://select2.org/troubleshooting/getting-help
[irc]: https://select2.org/troubleshooting/getting-help
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes

**Comment by sophanox** [comment]
Ah thank you for clarifying that Kevin. FYI, unless I missed it, there doesn't appear to be any to .clear() in the docs - particularly the Add, select or clear items page.

All the best
