### ISSUE TITLE
Multiple select - disable pillboxes and replace with count selected?

### ISSUE THREAD

**Issue by morrow95** [select2/select2#5599]
Been using select2 for years now.  Just recently came across a use scenario where I can't see myself using it as is.

Have a multiple select where user can select 30+ options (most with long names).  The default for multiple select is to add each selected in a pillbox.  With the high number that can be selected and the length of their names the pillboxes do not look good, creates a huge area on the page for display (even more so on smaller screens) and in the end doesn't even really serve a purpose as it is visually hard to see/read what you selected.

What I would 'like' to do is replace the pillboxes with a count of how many options are currently selected instead.  This eliminates the problems mentioned above and the user would just use the dropdown to see what is selected/unselected, add/remove, etc like a 'normal' multiple select.

Is there a way to do this with templating?  If not, can I make an option request for this ability?  Maybe like an option that when enabled changes to this style/use rather than the default pillboxes - basically removing the pillboxes entirely and just replacing with count?

There is another plugin out there, bootstrap-select, which handles multiple selects in this manner with a few other options to go along with it.

**Comment by kevin-brown** [comment]
This is very doable if you are willing to write your own selection adapter. It is all handled within the `update` method

https://github.com/select2/select2/blob/e5131d0cc8dffd98ba36a68f3d027bf79e763cb4/src/js/select2/selection/multiple.js#L82-L113

Unfortunately this is a large enough feature request that it isn't likely to land within the core of Select2 any time soon. Especially because we are focusing on fixing the bugs first before taking on large new features.

**Comment by morrow95** [comment]
Thanks... will give this a go.

**Comment by andreivictor** [comment]
@morrow95 , there is already written a custom selection adapter that fits your need: 
https://jsfiddle.net/bojanv91/ou7ohLd1/15
Original article: https://bojanv91.github.io/posts/2017/10/extending-select2-with-adapters-and-decorators
