### ISSUE TITLE
If binding data is huge collection then takes 30 seconds to bind the data to select component 

### ISSUE THREAD

**Issue by vittal288** [select2/select2#5600]
I have used 5 select2 elements in a screen and I am planning to bind to huge data but screen is getting hanged.

>  <select #multiSelect
>       class="form-control input-sm "
>       name="{{ruleParam.code}}"
> 			[(ngModel)]="model"
> 			(ngModelChange)="selectValue()"
> 			multiple>
> 			
> 		</select>

**Comment by kevin-brown** [comment]
If you are using Select2 with enough options that it is significantly slowing down the page load, it is recommended to switch to using a remote data source. Select2 is optimized to only handle large data sets when a remote source is used, because the process is converting local data into internal data objects and keeping them in sync is costly.

----

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://select2.org/troubleshooting/getting-help
[irc]: https://select2.org/troubleshooting/getting-help
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes

**Comment by vittal288** [comment]
I am fetching the data from the remote data source (I have assumed remote data means, I am loading the data from AJAX call and rendering it )

**Comment by SebuJang** [comment]
Using the data adapter, it is possible to handle huge data with select2 through client data.
See jsfiddle below.

https://jsfiddle.net/4b5snvkj/35/
