### ISSUE TITLE
Fire Event After results have rendered in dropdown

### ISSUE THREAD

**Issue by amfazlani** [select2/select2#5610]
I have posted this question on the forum but it seems this functionality does not exist  yet. I want to run some code right after the results have been populated in the ul. I have tested all the events and they all either run only when select is first opened (select2:opening), or after user has selected an item. But there doesn't seem to be an event for after render of the results. I feel like its a pretty common use case to want to have a callback for this specific event as the current events are when the items do not exist yet. templateResult is good to format the html but I need to initialize the actual element after they've been rendered with templateResult.

**Comment by kevin-brown** [comment]
While this is a common use case, it is not one which we intend to support because nobody can quite agree on when to trigger an event like this (and why). So as a result I am going to direct this as a usage question, so it can be asked in forums where it is more likely to get a solution.

----

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://select2.org/troubleshooting/getting-help
[irc]: https://select2.org/troubleshooting/getting-help
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes
