### ISSUE TITLE
Select2 internationalization issue

### ISSUE THREAD

**Issue by abclaur** [select2/select2#5617]
Hi,

The following setup throws an Error inside select2 plugin (version 4.0.3 onward).
https://jsbin.com/camawig/edit?html,output

I believe it has something to do with the dependency loading system, but it's hard to point exactly.

Any idea what might cause this ? I have not found a similar issue or maybe somebody else encountered in another form ?

Thanks,
Laurentiu

**Comment by abclaur** [comment]
Another observation: removing lang="en" from the <html> node solves the issue, don't know why though !

**Comment by kevin-brown** [comment]
> The following setup throws an Error inside select2 plugin (version 4.0.3 onward).

This has been happening since 4.0.0.

> I believe it has something to do with the dependency loading system, but it's hard to point exactly.

Yup, within the almond.js loader that we use.

https://github.com/requirejs/almond/blame/master/almond.js#L180

----

We catch this error within Select2, so this should never bubble up outside of the library. If you are defining your own global `Error()` class and [overriding the global `Error` class](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error), then you should be aware that this class is commonly used.

This isn't a bug, so I'm going to close this off.
