### ISSUE TITLE
Custom attributes missing on first selection (with AJAX)

### ISSUE THREAD

**Issue by delitestudio** [select2/select2#5637]
I'm using Select2 with the AJAX option to allow the user to select one city among all the Italian ones:

![shot_1](https://user-images.githubusercontent.com/14090511/64687189-5188b580-d48a-11e9-862b-89236accb9c9.png)

I'm adding some custom attributes to each city, i.e. its province and its postcode(s):

	processResults: function (data) {
		return {
			results: jQuery.map(data, function(obj) {
				return { id: obj.city_name, text: obj.city_name, 'prov_name': obj.prov_name, 'postcodes': obj.postcodes };
			})
		};
	},

I use this custom attributes to update the province and postcode fields automatically based on the value selected in Select2:

![shot_2](https://user-images.githubusercontent.com/14090511/64687340-9876ab00-d48a-11e9-8572-2386f991d175.png)

To get the custom attributes I'm using this code (as seen [here](https://stackoverflow.com/questions/33940477/adding-data-attributes-with-select2)):

	var data = jQuery('#billing_city').select2('data')[0];

It actually works correctly as we can see from the browser debugger:

![shot_3](https://user-images.githubusercontent.com/14090511/64687578-0f13a880-d48b-11e9-948d-d05628f4e5da.png)

Everything works properly, except for one case: if I go back to select the initial city, `data` no longer contains my custom attributes, so it doesn't update the other fields correctly.

E.g.: from Milan I choose Rome everything is ok, from Rome I choose back Milan I get this:

![shot_4](https://user-images.githubusercontent.com/14090511/64687886-9a8d3980-d48b-11e9-8865-8471d66bdc79.png)

I've already tried different ways (including [this one](https://select2.org/programmatic-control/add-select-clear-items#preselecting-options-in-an-remotely-sourced-ajax-select2), or the now deprecated `initSelection`), but I can't find a solution. Do you have any ideas? I think I'm missing something simple :(

**Comment by kevin-brown** [comment]
This really needs a jsbin where we can reproduce this issue, since otherwise there are a ton of different things that could be interacting here.

---

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/
