### ISSUE TITLE
Select2 dropdown- initial load doesnt have scrollbar in mobile/iPad

### ISSUE THREAD

**Issue by praneeth1987** [select2/select2#5650]
I am using select2 dropdown and it has around 100 values in dropdown.
In deskptop on initial load, I see all 100 values with scrollbar in results section where as in iPad I dont see any dropdown. But after search , we can see those values
We feel that values are missing on initial load, Any chance to bring scroll bar in iPad as well

**Comment by praneeth1987** [comment]
We want that old scroll bar so that users can scroll in ipad as well similar to desktop mode.
Any tweak to make it visible in iPad

**Comment by kevin-brown** [comment]
It's not clear if you're looking for the placeholder to be displayed (iPads generally don't have them normally), or if you're running into an issue when scrolling that is specific to the iPad. Because I no longer have an iPad to test with, I'm going to need some more information.

----

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/

**Comment by praneeth1987** [comment]
No its not about placeholder, its scrollbar inside the dropdown where I have 150 values in dropdown and scrollbar is not visible in iPad. Also when I set the min-height, the height gets increased but scroll bar is not at all visible after that.

I am just using the seletc2 plugin alone.

**Comment by kevin-brown** [comment]
Replace "placeholder" with "scrollbar" in my original comment, the statement still applies.

https://stackoverflow.com/q/7492062/359284

I thought the iPad didn't normally display a scrollbar for scrollable content until it was first scrolled?
