### ISSUE TITLE
X button displayed when placeholder key missing

### ISSUE THREAD

**Issue by mcandre** [select2/select2#5653]
In single-selection fields, the X button for clearing the choice, is displayed when no entry is actually selected.

As a workaround, I am explicitly `placeholder: ''` (blank) to my `select2()` calls.

**Comment by kevin-brown** [comment]
The docs for `allowClear` are on the page of the documentation for placeholders. You need a placeholder in order to clear the value back to the placeholder.

https://select2.org/placeholders

If you enabled the `debug; true` option, you would have seen an error in your console about this.

https://github.com/select2/select2/blob/7c4131bc27009fbf8f8ad9406ff3de72e8a5c8d7/src/js/select2/selection/allowClear.js#L15-L18
