### ISSUE TITLE
Problem with templateSelection and ajax source when an option is dynamically added to the select

### ISSUE THREAD

**Issue by fernaog** [select2/select2#5659]
With an ajax url where the fields do not follow the standard select2 structure. Example:

```
{
    "customer": [
        {
            "id": 1,
            "name": "Customer1",
            "created": "1993-02-24T05:32:18+00:00",
            "modified": "1982-09-30T18:34:26+00:00"
        }
    ]
}
```

  if  you use the templateSelection option  with something like this:

```
templateSelection: function (item) {
        
        return item.name;
   }
```

and you try to add dynamically an option with:

```
var newOption = new Option(response.customer.name, response.customer.id, true, true);
$('#customer').append(newOption).trigger('change');
```

the option is added but not rendered as selected

**Comment by kevin-brown** [comment]
Select2 uses `id` and `text` as the internal data format, not `id` and `name`.

https://select2.org/data-sources/formats

You're going to need to map your objects to meet Select2's internal data format. That link should help you out.

**Comment by razvanioan** [comment]
If you cannot / don't want to change data structure sent back from the API, you can override it to match `select2` format structure inside the `processResults` method

Check the link bellow for a simple scenario, but more complex data manipulation can be made in order to pull it through

https://select2.org/data-sources/ajax#transforming-response-data
