### ISSUE TITLE
The first letter is automatically placed as a valid option.

### ISSUE THREAD

**Issue by rodriquelca** [select2/select2#5661]
**Environment**
Select2 4.0.10

**Current behavior**
The single  select2 dropdown catch the first letter (typed on the keyboard) automatically.

**Expected behavior**
The selec2 dropdown must not automatically place an option that the user has not chosen from the options list.

**Steps**

1.  Create a select2 component.
HTML
`<select class="js-data-example-ajax">
</select>`

Javascript
`
var testData = [];
$(".js-data-example-ajax").select2({
		data: testData,
		tags: true,
    width: '400px'
});
`

2. Run the code
3. In the select2 textfield type a word.  for example  "hello world"
4. Here the first letter "h" was setted automatically.

http://jsfiddle.net/rodrigoquelca/bdeafury/7/

**Comment by kevin-brown** [comment]
This is because you're using tags with no pre-selected options or placeholder. This is a somewhat rare edge case and one easily solved by just adding a placeholder to your select and calling it a day.

**Comment by BenHunt42** [comment]
For anyone that finds this after the fact, only placing a placeholder will not fix the problem as presented exactly as in the jsfiddle. You also have to add an empty `<option>` for it to preselect. Once you have that, it will use the placeholder instead of showing the first letter of the tag.

IMO, it's a pretty basic example and probably happens often. Still seems like a bug, especially if you have to add blank tags to hack around it.
