### ISSUE TITLE
closeOnUnselect should be a option

### ISSUE THREAD

**Issue by Sire** [select2/select2#5699]
I don't want the selection to pop open after I click the X to unselect an item.

From a UX perspective, it makes little sense to me to display the dropdown after you have just removed an item. Consider what use case is most common:
"I just want to remove an item"
"I want to remove an item then immediately add another"

The [workaround here](https://github.com/select2/select2/issues/3209) works fine. But in my humble opinion, this should be turned into an option.
Suggestion: Add option "closeOnUnselect" with default false (so as to be backward compatible).

**Comment by kevin-brown** [comment]
Thanks for submitting this feature request! Unfortunately it's not being considered for immediate inclusion in Select2 because the known workaround exists.

----

Adding a new option to Select2 ends up being costly, not just in developer times but in downstream bugs that inevitably come up as a result. Because of the number of options we support, a lot of effort must be put in to ensure that there are no side effects caused by combining options together.

The better, more specific option name for what you'd be looking for would be something like "dontOpenWhenMultiselectOptionUnselected" which continues to be an edge case. If we added something like "closeOnUnselect" that would imply a relation to "closeOnSelect" which handles the behaviour in the dropdown.
