### ISSUE TITLE
Search input is not automatically focused on iOS 

### ISSUE THREAD

**Issue by vtrottier** [select2/select2#5706]
On iOS, when I click on a select2 input to open it, the search input is not focused. I need to click on it to be able to start typing.

Can be reproduced in the basic usage example in the docs https://select2.org/getting-started/basic-usage.

**Comment by vtrottier** [comment]
After some research and testing, it looks like on iOS Safari focusing an input field programmatically only works if it is done inside a click event handler.

**Comment by kevin-brown** [comment]
> After some research and testing, it looks like on iOS Safari when focusing an input field programmatically the keyboard will only open if it is done inside a click event handler.

Yup, this sounds about right. This isn't something we're planning on changing in Select2 for compatibility and usability reasons, so I'm going to have to close this off.

**Comment by kueblc** [comment]
I ran into this recently. Some of our customers were unable to figure out how to enter text. Thanks to this and an apparent duplicate #3814, I arrived at the following workaround:

```js
// after initializing select2
$('.select2-container').on('click', function() {
  $('.select2-search__field').focus()
})
```

I feel this should be fixed upstream, for compatibility and usability reasons. It is a poor user experience, with no obvious technical reasons why this shouldn't be the default behavior.

**Comment by davidfregoli** [comment]
The problem appears whenever the select is nested inside of a `<label>`, the click event bubbles to it and you lose focus.

Unfortunately `$('.select2-container').on('click', (e) => e.stopPropagation());` doesn't help because there's some other internal event that's triggering a `click` on the original `<select>`, which, guess what, will bubble to the `<label>`.

`$('.select2-container').on('click', (e) => e.preventDefault());` is what I've ended up using, not sure why or if it breaks anything else, so I can't say it's a perfect solution for everyone.
