### ISSUE TITLE
Select2 dropdown values are unable to set in ng-model scope

### ISSUE THREAD

**Issue by manjunathmofs** [select2/select2#5714]
select2 based dorpdown values is unable to set in ng -model
![image](https://user-images.githubusercontent.com/20864819/69797576-f39c7c00-11f5-11ea-8515-295dc9b4172c.png)

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/

**Comment by manjunathmofs** [comment]
I have attached my sample in plunker for your reference for more clarity

https://plnkr.co/edit/uQM1lOAUJRO8aLnNyxNN?p=preview

**Comment by kevin-brown** [comment]
> angularjs 1.7.8

That's still a thing?

I remember AngularJS (not Angular) having issues with Select2 because it did dirty checking on the model state only instead of listening for the change event (which Select2 properly emits). I think there's a Select2 plugin for AngularJS that you might be able to use to make them work nicely together.

Because it's an issue with AngularJS and not Select2 when isolated, I'm going to have to treat this like a usage question.

----

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://select2.org/troubleshooting/getting-help
[irc]: https://select2.org/troubleshooting/getting-help
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes
