### ISSUE TITLE
 data-* attribute for pre-selected values on data-data array

### ISSUE THREAD

**Issue by icaroscherma** [select2/select2#5778]
Select2 v4.0.5
`FEATURE REQUEST`

I'm currently using `data-data` attribute with a JSON array of objects but this data doesn't come with the pre-selected values, I got it elsewhere and I don't want to manually put on a `<script>` tag like `$('#mySelect').val(arrayOfSelectedValues);`, is there hidden feature to an attribute like `data-selected="[1,2,3]"` to run this `$(this).val($(this).data('selected'));` ?

Is it a wanted feature to somebody else? If so I will take a look to make a PR.

**Comment by icaroscherma** [comment]
On `Options.prototype.fromElement = function ($e) {`, before `return this;` (line 5035 on v4.0.5), add the lines:

```Javascript
if ($e.data('selected')) {
  let selected = $e.data('selected');
  if (!Array.isArray(selected)) {
    selected = [selected];
  }
  selected.forEach(s => {
    const index = this.options.data.findIndex(x => x.id === s);
    if (index !== false) {
      this.options.data[index].selected = true;
    }
  });
}
```

Any negative effects that you guys are aware of?

**Comment by kevin-brown** [comment]
Closing this off as wontfix, unfortunately we do not plan on adding another option to support this behaviour. Luckily this should be something you can do on your own with a little bit of code after you initialize Select2.

```js
$('.js-select2').select2();
$('.js-select2[data-selected]').each(function () {
  var selected = $(this).data('selected');
  if (!Array.isArray(selected)) {
    selected = [selected];
  }
  $(this).val(selected);
});
```

All of this works because Select2 automatically converts array data into `<option>` elements that can be treated like any other option in your select. Which means you can call `val()` on the select to set those as the expected options.
