### ISSUE TITLE
data-ajax--process-results is (may) not (be) working (properly)..

### ISSUE THREAD

**Issue by yahyaerturan** [select2/select2#5788]
Hi I am trying dynamically instantiate based on data attributes. Everything is fine, except `data-ajax--process-results`. 

I have a predefined function as below:

```javascript
var select2fnResultConverter = function (xhr, params) {
    var data;
    params.page = params.page || 1;
    params.name = "asc";

    data = $.map(xhr.data.items, function (obj) {
        obj.text = obj.text || obj.name;
        return obj;
    });

    return {
        results: data,
        pagination: {
            more: (params.page * 10) < xhr.data.total_items
        }
    };
};
```

When I add it to data attribute as `data-ajax--process-results="select2fnResultConverter"`, javascript throws an error saying that:

`i.processResults is not a function`

I tried a lot of combination  but couldn't make it work. If I write it in javascript instead of data attributes, it works.

```javascript
$('#js_form_new_business_id').select2({ajax:{processResults:select2fnResultConverter}});
```

Thanks for the lib and support.

**Comment by kevin-brown** [comment]
> javascript throws an error saying that:
> 
> `i.processResults is not a function`

Because in your case, it's not. You're passing in a string.

Select2 does not dynamically parse JavaScript functions that are passed in as a string. This would require us to know what type the option is supposed to be, and that's way more effort than we're willing to invest.

We recommend either defining it entirely in JS or using `$.each()` to dynamically pull that attribute for each element before Select2 is initialized on it.

----

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://select2.org/troubleshooting/getting-help
[irc]: https://select2.org/troubleshooting/getting-help
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes
