### ISSUE TITLE
Ajax error handling... again

### ISSUE THREAD

**Issue by motching** [select2/select2#5799]
With the default `transport` function added to `_applyDefaults`, it became a little hard to implement custom ajax error handling. If I only put in error handling, the success call obviously won't happen. The simplest method I found is to override the whole function with the original and add my code but that is a lot of boilerplate and also if select2 changes the default transport function I'll be out of sync.

    transport: function (params, success, originalFailure) {
        var $request = $.ajax(params);
        $request.then(success);
        $request.fail(function (response) {
            // {{MY ERROR HANDLING CODE}}
            // Let select2 invoke their error handling code as well.
                originalFailure();
            });
           return $request;
    }

What do you think of adding an error handling callback to the options list? Similar to `processResults`, something like `handleError`. It could be added in the `request` function, to be invoked there if it exists. 

I can make a PR if you think it has a reasonable chance of being merged. Let me know, thanks!

**Comment by kevin-brown** [comment]
Honestly, with the default transport being
```js
transport: function (params, success, failure) {
    var $request = $.ajax(params);

    $request.then(success);
    $request.fail(failure);

    return $request;
}
```
And it being exceedingly unlikely that this will change in a meaningful way, I am going to decline adding a new feature for error handling. Especially because the more common request is to have the ability to turn _successful_ responses into error responses, and you need to override the transport for that as well.
