### ISSUE TITLE
Search field with number issue

### ISSUE THREAD

**Issue by ayhaadam** [select2/select2#5804]
Hi, I create a select for user to select/input phone numbers, with options `tags: true` and `tokenSeparators: [',', ' ']` for dynamic option creation.

In some mobile browsers, the keyboard will be reset digit by digit. So it's really hard for user to key in a complete phone number, as below screenshots.

I also tried specify number soft keyboard  by setting search field `type="tel"`, `type="number"`, `inputmode="numeric"`, `inputmode="decimal"` or `pattern="[0-9]*"` in `select2:opening` and `select2:open` event, but there will be no comma key on the number keyboard.

JS Bin: http://jsbin.com/sitipetuku/edit?html,js,output

---

**Work perfectly** 
- Safari on iOS 13.3.1
![13](https://user-images.githubusercontent.com/3087573/76923926-cba16780-690f-11ea-94f0-8b0d84d04f8d.gif)

---

**With keyboard Issue**
- Safari on iOS 12.4.2 (basically all iOS 12)
![12](https://user-images.githubusercontent.com/3087573/76924321-f4762c80-6910-11ea-94b2-9b1032a86339.gif)

- Chrome 80.0.3987.132 on Android 10
![10](https://user-images.githubusercontent.com/3087573/76924311-ea542e00-6910-11ea-9069-7bf35892ce48.gif)

**Comment by kevin-brown** [comment]
You're asking for custom number support but you've identified the issue of using a comma as your separator, since it's not on those keyboards. We also can't solve that problem for you.

----

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://select2.org/troubleshooting/getting-help
[irc]: https://select2.org/troubleshooting/getting-help
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes
