### ISSUE TITLE
Please consider bountysource to promote specific issues

### ISSUE THREAD

**Issue by flip111** [select2/select2#5817]
Please consider [bountysource](https://www.bountysource.com/) (or any alternative) to promote specific issues.

**Comment by kevin-brown** [comment]
To be completely honest, this isn't something we're considering because the overhead is likely going to be more than it's worth again. We had enabled Bountysource on this repo a few years ago and it ended up not having an impact on whether or not issues were fixed.

As a result we found out that the best way to get a long-standing issue fixed was to personally find someone who would be interested in fixing it for you. We've watched the community do this with mixed success, but we don't act as or promote a specific broker for making this happen.
