### ISSUE TITLE
Regression in responsive between 4.0.5 and 4.0.6+ when i scroll right and down the full page - 1 solution provided

### ISSUE THREAD

**Issue by eldy** [select2/select2#5832]
Due to a change into select2.css, web pages are not correctly rendered on an android smartphone, as well as on chrome smartphone emulator when you try to scroll on right, when using 4.0.6 (tested on all version from 4.0.6 to 4.0.13: same trouble). 

This is what i got with 4.0.5 (Correct): If i try to scroll on right, rendering stop at end of page.
![image](https://user-images.githubusercontent.com/883887/79638206-b58ffc80-8184-11ea-9b28-7c16f6f377f2.png)

And this is whatI have with 4.0.6+ (Bad): If i try to scroll on right, rendering continue even if there is no content. Note that trouble is also on scroll down.
![image](https://user-images.githubusercontent.com/883887/79638309-246d5580-8185-11ea-9fa1-4030454e2d20.png)

**Solution:**
If I restore the following line that was removed in 4.0.6, trouble is fixed (it fix also if i test the change on 4.0.13);

```
.select2-hidden-accessible {
  margin: -1px !important;                /* line to restore */
}

```

**Comment by kevin-brown** [comment]
This change landed in 2017 as https://github.com/select2/select2/commit/7ca986701ac3b0e9bb17dc912fd8c6812edbefa6 which was based on https://github.com/select2/select2/pull/4908.

I recognize that it causes an odd behaviour in your case, but it looks like you found a solution that works around that issue without requiring changes to Select2 itself (you can include that CSS in any of your files) which is a plus. Because it has been 3 years at this point, I'm going to close off this and acknowledge that anyone encountering this issue in the future will need to add back in this line of CSS.

**Comment by eldy** [comment]
Update: The fix i suggested was working on most browser but i found some were the bad behaviour was still present.

```
.select2-hidden-accessible {
  margin: -1px !important;                /* line to restore */
}

```
I fixed for all browsers with this change instead:
```

.select2-hidden-accessible {
  margin: -10000px !important;                /* line to restore */
}

```
