### ISSUE TITLE
Empty default selection on multi-select

### ISSUE THREAD

**Issue by robo2bobo** [select2/select2#5858]
Hello everyone,

I've got a multi-select input and I would like it to start empty, without a selection. Unfortunately, when the page loads, select2 automatically picks the first option and I can't stop it. The result looks like this:

![default](https://user-images.githubusercontent.com/37706921/82124098-8b425680-97a5-11ea-9472-edf5015f2df8.png)

While the documentation says that multi-selects should not have an empty option, someone suggested to use one with a placeholder option. This seems to work at first, the result loooks good:

![emptyselect](https://user-images.githubusercontent.com/37706921/82124104-96958200-97a5-11ea-96e3-9bd12f67f67c.png)

Unfortunately, when the user tries to pick an option, TWO options are selected, one of them is the empty one and the result looks like this:

![emptyselect2](https://user-images.githubusercontent.com/37706921/82124107-9b5a3600-97a5-11ea-8c78-2c9933790e30.png)

Here is how I load the script:

```javascript
$('#brand').select2({
	placeholder: { id: '-1', text: 'Select an option'},
	maximumSelectionLength: 6,
	multiple: true,
	width: "100%"
});
```

I'm using: select2-4.1.0-beta.1.zip

Any help would be appreciated.

Thank you.

**Comment by kevin-brown** [comment]
Multiple select boxes do not support a complex placeholder, so you can't use a custom `id` with them. Additionally, they do not require a placeholder `<option />`, unlike a single select, because by default they can have no selections. If you include a placeholder `<option />`, that option will be selected and appear within your selection list.
