### ISSUE TITLE
Search-Box focus behaviour

### ISSUE THREAD

**Issue by abenz1267** [select2/select2#5869]
Hello,

we migrated from 3.5 to 4.0.13 and now have a problem with search inputs not being focused after opening a select2 box. I noticed the same behaviour on the official website, see https://select2.org/appearance#labels (clicking on the "Alaska" box). Other Select2 boxes seem to work just fine. See the "Alaska" Box on https://select2.org/getting-started/basic-usage.

Only workaround we found so far is manually focusing the input bar AFTER A TIMEOUT. This isn't exactly a good solution.

Any pointers on what's going wrong? This seems like a bug to me...

Regards

**Comment by abenz1267** [comment]
Also wanted to add: in those cases on Linux/Windows the selected item inside the select2-box won't update if you select via arrow keys. Like, visually. On MacOSX the native select box will open up.

**Comment by Daijobou** [comment]
I found this issue too. Its little annoying. See https://select2.org/appearance#labels and add a item in "Click this to focus the multiple select element". Now delete it with "x" and popup is opened again. Scroll down and click anywhere and browser jumps back to previous input, because closing popup have focused input. When scrolling it should close the popup, like in https://select2.org/getting-started/basic-usage.

**Comment by abenz1267** [comment]
just checked and the issue seems to be present still.
