### ISSUE TITLE
Made some Accessibility updates want feed back, ALSO how can we unselect on enter!

### ISSUE THREAD

**Issue by nonoandy** [select2/select2#5872]
https://jsfiddle.net/nonoandy/z94dgom7/

I made some accessibility updates trying to retro fit the current html :) and would like some feedback!
Also, does anyone know how to make enter unselect items on the dynamic dropdown.

**Comment by kevin-brown** [comment]
I would recommend taking a look at the Select2 4.1.0-beta.1 release because it has some of these features baked in from the beginning.

> Also, does anyone know how to make enter unselect items on the dynamic dropdown.

You **really** don't want to do this. We have a giant commit about why this is a bad idea (we tried it): https://github.com/select2/select2/commit/017c20109471fa5b835603faf5dc37f7c2c2ea45

**Comment by nonoandy** [comment]
Thank you! I seen the updates in the beta version and like what I seen (after I already did this work lol.  If I get a change between jobs, I will get the latest version and give you some feed back.

As for the "unselect on enter" that is fine but could you give a option to unselect on just space bar (not just ctrl+spacebar).  I have given some aria-descriptions to help users but this has been asked for a lot.
Either way thank you for everything you do!
