### ISSUE TITLE
Mobile Keyboard overlaping Select Box

### ISSUE THREAD

**Issue by atulb-webonise** [select2/select2#5888]
Hi, My Name Is Atul I have issues which are I think common but no once faced it.

Here is the issue.
I have the number of select boxes in a wrapper which is a popup that has a fixed position using CSS. 
in mobile, it overlaps behind the keyboard. which should be above the keyboard.

here the codepen area where I have reproduced it. Please open it on the mobile.
https://codepen.io/atulya/pen/QWyvXxL

Waiting for positive reply.

- Atul Bhalerao

**Comment by kevin-brown** [comment]
More than likely, it is not displaying above the keyboard because there is not enough space for it to display above the keyboard with how it is positioned.

----

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/
