### ISSUE TITLE
Setting Max Length for dynamic option creaton

### ISSUE THREAD

**Issue by OmarHegazi94** [select2/select2#5901]
I'm trying to set max length for dynamic option creation but it appears to be not possible ..

(screenshot)

![Settings](https://user-images.githubusercontent.com/24498809/88479671-1a5fad80-cf51-11ea-8a73-2ea3bb1239a2.png)

`        function targetAudeinceCounter() {
            var FieldLength = $('.select2-selection__choice__display').text().length;
            $('.audienceCounter').text(300 - FieldLength);
        }`

but this won't stop the user from adding more that the length specified .

is there a way of doing this or a way around it ?

**Comment by kevin-brown** [comment]
I haven't tested it out, but you may be able to use `maximumInputLength` and `tags` together. Otherwise I would recommend creating your own `createTag` method and returning `null` if it is over the maximum length that you are looking for.

---

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://select2.org/troubleshooting/getting-help
[irc]: https://select2.org/troubleshooting/getting-help
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes
