### ISSUE TITLE
insertTag isn't working

### ISSUE THREAD

**Issue by mezzarfani** [select2/select2#5909]
I am unable to get insertTag to work. It appears to be a bug.

See below for an example:

https://jsfiddle.net/cr1g60ho/

**Comment by kevin-brown** [comment]
In your example, the tag is being inserted into the results at the bottom of the list (when others are included) instead of at the top like it is by default. It appears to be working as documented.

https://select2.org/tagging#customizing-tag-placement-in-the-dropdown

---

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://select2.org/troubleshooting/getting-help
[irc]: https://select2.org/troubleshooting/getting-help
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes
