### ISSUE TITLE
Strange BUG with minimumResultsForSearch: Infinity

### ISSUE THREAD

**Issue by Hamarkhis** [select2/select2#5937]
Hello guys,

I have been searching a lot on my side to find the cause of what's happening on the select2 dropdown, I have a bad user experience. I have made a clean install of wordpress with minimal things and I am able to reproduce the issue : when the line `minimumResultsForSearch: Infinity` is used, the dropdown list is closing itself and I can't select anything. Tested with latest version of select2, 4.1.0-beta.1.
If I comment the line `minimumResultsForSearch: Infinity` then everything works fine.

EDIT : **I found a workaround, do not use the latest jQuery 3.5.1, instead, use the jQuery 2.2.4.**

Maybe _can I suggest you to tell on [the select 2 site page](https://select2.org/getting-started/installation) that jQuery version 3.x is not supported_.

**Comment by Hamarkhis** [comment]
Hello Guys,

I have been searching a lot on my side to find the cause of what's happening on the select2 dropdown, but I don't manage to advance. 

I suspect that the dropdown might be misplaced but I'm not sure of this, so first, I have made a short video to see what's happening on my side.

[Go there to see it](https://freshsite.mystagingwebsite.com/wp-content/uploads/2020/10/Select2-issue.mov)

Let me know what we can improve there.

**Comment by kevin-brown** [comment]
I'm going to need more information to be able to debug this one, since from my experience this option works as expected.

> Maybe _can I suggest you to tell on [the select 2 site page](https://select2.org/getting-started/installation) that jQuery version 3.x is not supported_.

We definitely support the latest version of jQuery 3.x, we actually run our tests against all 3 latest versions of jQuery.

----

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/

**Comment by eberhapa** [comment]
I had the same issue. You need to install the jquery migrate helper and change it to the legacy version.

**Comment by retroriff** [comment]
I have the same issue since WP migrated to jQuery 3.5.1. I tried to reproduce the error here but it works:

https://jsfiddle.net/retroriff/z28nqLe6/6/

I can reproduce the error in WP when only I am logged in and when I use "minimumResultsForSearch: Infinity".

**Comment by kampiamodikuesto** [comment]
same problem with: WP 5.7, WC 5.1.0

i setted Legacy 1.12.4-wp in Enable jQuery Migrate Helper settings
