### ISSUE TITLE
In Firefox dropdown not enlarging when dropdownAutoWidth enabled

### ISSUE THREAD

**Issue by mishani0x0ef** [select2/select2#5947]
## Issue

In Firefox browser, when `dropdownAutoWidth` is enabled - options that overflows width of the dropdown wrapped to the next line:

Firefox (has issue):
![image](https://user-images.githubusercontent.com/12882856/98573637-15670580-2285-11eb-8b50-00c520466bbb.png)

Chrome (works correctly):
![image](https://user-images.githubusercontent.com/12882856/98573690-231c8b00-2285-11eb-9f81-14e9c3e3cd01.png)

## Steps to reproduce
1. Open next [jsFiddle](https://jsfiddle.net/48q69ncx/1/) in Mozila Firefox
```js
$('#example').select2({
    placeholder: 'Select a month',
    dropdownAutoWidth: true
});
```
2. Expand dropdown
3. Look at the item that contains long text

**Actual Result:** 

Largest item wrapped in a second line

**Expected Result:** 

Dropdown enlarged to fit the lergest item

## Environment

Browsers:

- [x] Mozila Firefox 82.0.2 (64-bit)
- [ ] Google Chrome
- [ ] Microsoft Edge

Operating System:
- [x] Windows 10 

Select2:
- [x] v4.0.13

**Comment by kevin-brown** [comment]
I can confirm that this option is working as expected in

* Chrome (87.0.4280.66)
* Edge (87.0.664.47)

I can confirm the option is not working as expected in

* Mozilla Firefox 78.5.0esr

But I'm also willing to call this not a bug, because Firefox is actually behaving as expected for those who are not custom theming. Select2 is telling Firefox to automatically fill out the width of the dropdown, and Firefox is choosing to do it slightly smaller than you would expect. If you set the width on the original `<select>` to `200px`, you can actually see that Firefox will let the dropdown be wider than the selection area, which is what we would expect to happen.

![image](https://user-images.githubusercontent.com/1991850/100493533-a05d5200-3105-11eb-8f8b-b6421fea4f75.png)

You can tell Firefox to never break the text up across multiple lines by controlling the whitespace settings via CSS for Select2 results.

https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
https://developer.mozilla.org/en-US/docs/Web/CSS/white-space
