### ISSUE TITLE
createTag doesn't work with templateResult

### ISSUE THREAD

**Issue by nashsaint** [select2/select2#5950]
I used a template to render a multiline option but also have a createTag to allow new entry, but it appears like the createTag is completely ignored when templateResult is present.

```
function rowItem(item) {
    let el = $(item.element),
    firstname = el.data('firstname'),
    country = el.data('country')

    let template = $('<div class="typeahead-multiline">'+
         `<div>${firstname} ${lastname}</div>`+
          `<div>${country}</div>`
     '</div>')
     return template
}
$(this).select2({
                  dropdownPosition: 'below',
                  tags: true,
                  createTag: function (params) {
                    return {
                      id: params.term,
                      text: params.term,
                      newOption: true
                    }
                  },
              templateResult: rowItem
                });
```

**Comment by kevin-brown** [comment]
[Here's an example of it working](https://stackoverflow.com/a/30021059/359284), I suspect the issue is actually in your `rowItem` function not working with what you're returning from `createTag`.

----

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://select2.org/troubleshooting/getting-help
[irc]: https://select2.org/troubleshooting/getting-help
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes
