### ISSUE TITLE
How to do quick option (HTML Content) filtering via a search box 

### ISSUE THREAD

**Issue by yogeshsaroya** [select2/select2#5956]
Hi 

I need same as example > Loading Remote Data (https://select2.github.io/select2/index.html#infinite) but without Ajax search, i have only 100+ items. I want to load all data via json file and then filtering via a search box. No Ajax data, same as the "Examples  > The Basics" but option will have images and more content.

How can I do that.  in "Examples  > The Basics" i can not use Images. 

Thanks

**Comment by yogeshsaroya** [comment]
- [ ]

**Comment by kevin-brown** [comment]
I'm going to assume you're using Select2 4.x or newer, since the documentation you linked to is for Select2 3.x which is half a decade old at this point.

You can find information how to build Select2 from an array of data elements at https://select2.org/data-sources/arrays.
---

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://select2.org/troubleshooting/getting-help
[irc]: https://select2.org/troubleshooting/getting-help
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes

**Comment by yogeshsaroya** [comment]
Yes i am using Select2 3.5.3
 ( https://select2.github.io/select2/index.html#infinite ) 

You can find information how to build Select2 from an array of data elements at https://select2.org/data-sources/arrays.  >> Yes i was already using this but here i can not use images and html data. 

https://select2.github.io/select2/index.html#infinite is about ajax loading. I need it without ajax. on select it should show all option and then can filter. no ajax anymore. 

Thanks
