### ISSUE TITLE
Results could not be loaded

### ISSUE THREAD

**Issue by philiprbrenan** [select2/select2#5959]
![image](https://user-images.githubusercontent.com/7548378/102674565-5577ad00-418e-11eb-96b6-3fb50a62e521.png)

Please provide a more meaningful error message as the current one does not indicate any actionable reason why the results failed to load.

**Comment by kevin-brown** [comment]
Check your developer console since it most likely includes an error about why the AJAX request failed. If you're not seeing anything in the console, you can enable `debug: true` in your options for additional debugging information.

Since Select2 is customer-facing we do not dump these debugging details into the results list and instead keep them in the console for developers to be able to view.

----

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://select2.org/troubleshooting/getting-help
[irc]: https://select2.org/troubleshooting/getting-help
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes
