### ISSUE TITLE
Always allow option to create "X" when "X" already exists.

### ISSUE THREAD

**Issue by robsilva** [select2/select2#5968]
I would like to allow users to create a new option even if an option with the exact same label already exists.
Right now, when the user input matches exactly one of the options, the 'Create X' option does not appear.

My abridged code looks like this:
```
       $("#select-session").select2({
            tags: true,
            data: sessionList,
            insertTag: function(data, tag){
                tag.isNew = true;
                data.push(tag);
            },
            escapeMarkup: function (markup) { return markup; },
            templateResult: (session)=> {

                if (session.loading) return "Loading...";

                return session.isNew
                    ? `<i class="fa fa-plus mx-2"></i> Create ${session.text}`
                    : `<div class="row">
                        <div class="col-6 text-truncate">${session.text}</div>
                        <div class="col-6 text-truncate">${session.start ? moment(new Date(session.start)).format('MM/DD/YY h:mm a') : ''}</div>
                    </div>`;

            },
            templateSelection: (session) => {
                if (!session.id) {
                    return session.text;
                }
                return `${session.text || ''}`;
            },
        })
```

Any help would be greatly appreciated. Thanks in advance.

**Comment by kevin-brown** [comment]
This can be accomplished by overriding `createTag` and returning a unique `id` for it, since that is how we de-duplicate.

---

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://select2.org/troubleshooting/getting-help
[irc]: https://select2.org/troubleshooting/getting-help
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes

**Comment by sovetski** [comment]
I had the same problem, if someone else needs, this solution works as @kevin-brown explained with "createTag" and "select2:selecting" event:

```javascript
select2({
  selectionCssClass: 'test',
  tags: true,
  tokenSeparators: [','],
  createTag: function(params){
      var term = $.trim(params.term);

      if (term === '') {
          return null;
      }

      return {
        id: term,
        text: term,
        newTag: true // <<-- HERE
      }
  },                          
}).on('select2:selecting', function (e) {
    var data = e.params.args.data;

    if (data.newTag) {
        var $option = $("<option selected></option>").val(data.text).text(data.text);
        $(this).append($option);
    }
});
```

More information: https://select2.org/tagging#tag-properties
