### ISSUE TITLE
Placeholders on multiple select2 are cut when they are bigger than options

### ISSUE THREAD

**Issue by Sabe67** [select2/select2#5979]
Hello,

I write you because I have a problem which I can't solve myself.
I have multiple select with placeholders. When they are biggers than the options, they are automatically cut by select2.

![select2](https://user-images.githubusercontent.com/13998579/107517442-0a867e80-6bae-11eb-8f51-1e844fa78037.png)

Thank you for your help.

**Comment by kevin-brown** [comment]
Select2 allows you to set the `width` of the select box which should allow you to make it as large as you want. 

https://select2.org/appearance#container-width

By default Select2 tries to not be wider than the original `<select>` which is why you see it being limited to the size it is.

---

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://select2.org/troubleshooting/getting-help
[irc]: https://select2.org/troubleshooting/getting-help
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes

**Comment by Sabe67** [comment]
Thank you for your help. But I think it's not a good solution.
My website is in several languages. Depending on the language, the text can be longer or shorter. And I have just on call for select2 I prefer something dynamic and not static with a width.

**Comment by Mick3DIY** [comment]
> Thank you for your help. But I think it's not a good solution.
> My website is in several languages. Depending on the language, the text can be longer or shorter. And I have just on call for select2 I prefer something dynamic and not static with a width.

Hello @Sabe67, 
be careful also about Boostrap & Bootstrap themes in your project... I discovered some minor bugs with long placeholder, for example with https://github.com/ttskch/select2-bootstrap4-theme 

Cheers.
