### ISSUE TITLE
Clear filter set empty string against clear array

### ISSUE THREAD

**Issue by LocalHeroPro** [select2/select2#5987]
1. Create element
```
<select name="types[]" multiple="multiple"></select>
```
2. Initialize
```
allowClear: true,
```
3. delete all selected items and you get array with empty sting.

Proof:
![image](https://user-images.githubusercontent.com/42643563/108722073-04d05780-7523-11eb-9811-18dc49fd954e.png)

**Comment by kevin-brown** [comment]
https://jsfiddle.net/d4urm6w2/5/

Tried to reproduce it here with a minimal test case and I wasn't able to reproduce the issue you are seeing.

----

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/

**Comment by mhabsaoui** [comment]
Hi, I confirm this array with empty string is somehow linked to a weird button in the list with no value...

You can go try this browser addon using Select2, install it and once you get on the Options page (on first install or on click on addon picto) =>  https://chrome.google.com/webstore/detail/click-and-read-cnrs/ffboikeeabaiacihgbdinhcegeincpnh?hl=fr

1) Check "I am a user of BibCnrs" and add any domain from the list  +  click green save button at bottom of page 
2) Uncheck and redo previous step 1)
3) You should get the weird empty grey button, introduced by Select2 ? 

![image](https://user-images.githubusercontent.com/18755135/116043962-a170bc00-a670-11eb-85cd-072f4fd9352e.png)

![image](https://user-images.githubusercontent.com/18755135/116053372-e863af00-a67a-11eb-8f60-618f28f18f64.png)

So for now, we had to filter it...

![image](https://user-images.githubusercontent.com/18755135/116061696-76439800-a683-11eb-86b5-10355266c504.png)


Thanks for your help !

**Comment by mhabsaoui** [comment]
To be fully complete :


1. -     What steps can be used to reproduce the issue?
as explained on previous post

2. -     What is the bug and what is the expected outcome?
bug is the empty button appearing at start of the selected items as explained on previous post. Expected to Not have it.

3. -     What browser(s) and Operating System have you tested with?
Latest Firefox, Chrome and Safari on Latest Ubuntu  (18.04.5 / 20.04.1 LTS), Windows (10) and MacOS (Catalina, BigSur)
 
4. -     Does the bug happen consistently across all tested browsers?
Yes, fully reproducible  !

5. -     Can you reproduce this issue on any of the examples in the docs?
Don't know if it can be applied to those examples, but have to try...
 
6. -     What version of jQuery are you using? And what version of Select2?
"select2": "4.0.6-rc.0", "jquery": "3.3.1",   => We kept an aloder version of jquery because of the annoying auto focusing not working on latest jquery version...

7. -     Are you using Select2 with other plugins?
Nope. select2+jquery are the main used.

Hope it helps :-)

**Comment by mhabsaoui** [comment]
Hi,

well any suggestions or feedback ?

Or do we have to switch to react-select2...

**Comment by Cyrille37** [comment]
Hello,

You can see in javascript browser console that removing individually all items does not the same as clearing with the cross little button.

**(1)** After removed each items:
```
> $('#the-multiselect').val()
Array [ ]

```
**(2)** When clearing with the cross :
```
> $('#the-multiselect').val()
Array [ "" ]
```

Another (*underlying*) problem is in case **(1)** the select field is not present in the http post request while in case **(2)** an empty field is well transmitted.
The case **(1)** is a attended behavior (an empty array) but like it is not transmitted in the request, the back logic cannot know that the values are cleared...

**Comment by Cyrille37** [comment]
Hello

I could not reproduce the difference I talked about in previous comment, but with this [jsfiddle](https://jsfiddle.net/Cyrille37/x351fgsp/11/) you can try that after clearing, the empty select2 `types[]` is not transmitted in http post request:

![image](https://user-images.githubusercontent.com/368965/122667391-05b48580-d1b3-11eb-9863-ccb5b94f3611.png)

**Comment by Cyrille37** [comment]
Like my report is not the same, I've open a new issue [Empty select2 is not transmitted in Http Post Formdata #6055](6055).

**Comment by mhabsaoui** [comment]
LOL, sorry we just had (previous Dev.) an empty <option></option> inside the <select />, which caused the empty button bug...

So before to close this Issue :²

- Can you confirm, according the Documentation, that we only need following code for **Multi** select box ?  

`<select class="domainList" name="domain[]" style="width: 100%;" multiple="multiple"></select>`

- How to apply a Placeholder to a **Single** select box ? (because this time without an empty <option></option> inside the <select />, the Placeholder text isn't shown and instead we got the first elemnt in the listbox...

Many Thanks for your reply.

**Comment by mhabsaoui** [comment]
Anyway, the answer is already here in Doc. :  https://select2.org/placeholders
