### ISSUE TITLE
Install Doc on Windows

### ISSUE THREAD

**Issue by blpraveen** [select2/select2#6001]
I installled grav from composer.
copied the doc folder from git repository to users folder on my grav cms installation
When I open it on localhost it shows like the attached image.
What am I doing wrong
![image](https://user-images.githubusercontent.com/3274289/110902519-0627bf80-832c-11eb-9e08-a6c5cc13e20c.png)

**Comment by pamtbaau** [comment]
As explained on the cross-post of this issue on [Stackoverflow](https://stackoverflow.com/questions/66595435/grav-cms-on-windows/66595683#66595683), since Grav 1.7 the Twig function `autoescape` has been enabled by default.

To fix this security measure, all Twig output that is trusted must receive the `|raw` filter.

Do you have any plans to upgrade the templates of this repo to Grav 1.7?

**Comment by kevin-brown** [comment]
> Do you have any plans to upgrade the templates of this repo to Grav 1.7?

We're way more likely to move to a static site generator (again) than to upgrade to Grav 1.7 unfortunately.

**Comment by pamtbaau** [comment]
In that case, you may consider to notify the Grav team and remove this plugin from the plugin directory.
