### ISSUE TITLE
css to change background of a select which has option:selected doesn't work on 4.1 version

### ISSUE THREAD

**Issue by martinbarilik** [select2/select2#6004]
Here is the fiddle for 4.0.13

https://jsfiddle.net/mArtinko5MB/tkazg3Lc/3/

Here is the fiddle for 4.1

https://jsfiddle.net/mArtinko5MB/6Lw7s09v/4/

**Comment by kevin-brown** [comment]
This is because Select2 has an accessibility issue in 4.0 where the `title` attribute was not being set for placeholders. We fixed this in 4.1 with the accessibility overhaul, which means that your hack for detecting when a selection is present no longer works.


----

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://select2.org/troubleshooting/getting-help
[irc]: https://select2.org/troubleshooting/getting-help
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes
