### ISSUE TITLE
[QUESTION] How can i create tag with ajax response

### ISSUE THREAD

**Issue by can-guven** [select2/select2#6008]
Hi, I want to create tag with ajax response.  Because when user delete this tag. I have to request to backend with tag id.

```js
createTag: function (params) {
      var term = $.trim(params.term);
      if (term === "") {
        return null;
      }
      return {
        id: ?, //i want to set this with ajax response
        text: term,
        newTag: true,
        anotherId: ?, //i want to set with ajax response
      };
    },
```

**Comment by devmonkey22** [comment]
Per project Issue Template guidance:
1. Make sure that your issue is a BUG or FEATURE REQUEST.  **General usage and troubleshooting questions should be directed to the [forums](https://forums.select2.org) or [Stack Overflow](https://stackoverflow.com/questions/tagged/jquery-select2).  Issues asking for general support WILL BE CLOSED automatically.**

https://forums.select2.org/t/create-new-tags/942 may help you.

**Comment by kevin-brown** [comment]
This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://select2.org/troubleshooting/getting-help
[irc]: https://select2.org/troubleshooting/getting-help
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes
