### ISSUE TITLE
placeholder affect option empty value

### ISSUE THREAD

**Issue by YueYunyun** [select2/select2#6009]
Sample:
https://codepen.io/YueKing/pen/wvgzoEL

if use placeholder ,the empty value option will be missing.

![Sample](https://user-images.githubusercontent.com/27658806/112861246-37074300-90e7-11eb-96fb-fd87aa87f6bc.png)

**Comment by Okeanos** [comment]
Bump. I am also interested in this.

**Comment by kevin-brown** [comment]
It is not visible because it's a "placeholder" option. If you wish to still allow the user to remove the selection and revert to the placeholder, we would suggest using the `allowClear` option. If you want the option to still be visible in the dropdown as a valid option to select, then we would suggest not using the `placeholder` option.

**Comment by Okeanos** [comment]
I will try that, thank you for the explanation.

**Comment by Okeanos** [comment]
@kevin-brown maybe I am doing something wrong but the example [here](https://jsfiddle.net/nd8rgjb9/4/) definitely doesn't work as expected.

It might be a weird edge case of having to specify the placeholder via `data-placeholder` but what I expect to happen is:
`Option 1` is not preselected given that I defined a placeholder (which should be shown by default). What happens: `Option 1` is selected but can be cleared.

If I additionally put an empty `<option></option>` at the beginning of the select it'll be selected (correctly showing the placeholder text) but it can't be cleared and no other selection can be done. This effectively breaks the select box.

**Comment by kevin-brown** [comment]
Per the HTML spec for a single select, if there are no options with the `selected` attribute set within a `<select>` element on initialization, the first `<option>` within the select is set as selected. As a result, the first option in your jsfiddle is being selected. This is why on the Select2 placeholders documentation we show in our example the empty `<option></option>` and have a note below it explaining what the deal is.

https://select2.org/placeholders

This is why your first option is selected instead of the placeholder as well, since, as noted in the docs, this is the default behaviour per the spec and we can't do anything about it. If you add in the blank option as the first option, the placeholder appears as the default option and the two options in the dropdown appear as expected.

https://jsfiddle.net/1vwL4bpe/1/

By default Select2 does not allow the placeholder option to be selected, which is why as soon as you pick an option it is not possible to go back to the placeholder. This is because dropdowns with placeholder options are typically meant to be required on a form, so by default Select2 makes this assumption and does not allow it to be reset. If you wish to allow it to be reset, we provide the `allowClear` option which can make a "x" appear next to the selected option (as well as enabling keyboard shortcuts), allowing it to be cleared back to the placeholder.

https://jsfiddle.net/1vwL4bpe/2/

Note that in your example you set `maximumSelectionLength` to `1` which means that Select2 will not allow another option to be selected if one already has been. This is not a standard or recommended configuration on a single select because they _always_ have a selected option. If you remove that, you'll see it behaves as documented. I am willing to take another ticket being made to raise a warning when `maximumSelectionLength` is set but `multiple` is not set, since this seems like an invalid configuration.

**Comment by Okeanos** [comment]
Thank you so much for your in depth explanation of this. Totally makes sense and works as I expect it to. I must've picked up the `maximumSelectionLength` option by accident and not questioned it further originally (it's been a while since I last worked on this private project).

A warning on the [selections](https://select2.org/selections#limiting-the-number-of-selections) documentation page concerning "must be set to allow multiple selections to begin with" wouldn't go amiss either. I would actually even propose to make `maximumSelectionLength` with a value `< 2` an illegal config value. Should I open a ticket asking to clarify the documentation or will you handle that?
