### ISSUE TITLE
Empty select2 is not present in Post Formdata

### ISSUE THREAD

**Issue by Cyrille37** [select2/select2#6055]
Select2: 4.0.13
JQuery: 3.6.0

After cleared, the empty select2 is not transmitted in http post formdata request.

With this [jsfiddle](https://jsfiddle.net/Cyrille37/x351fgsp/13/)

1) With selected values the http post formdata are well filled:
![image](https://user-images.githubusercontent.com/368965/122668903-bc683400-d1ba-11eb-8f8e-a20555d92f5b.png)

2) After clearing, without selected value, the http post formdata is empty:
![image](https://user-images.githubusercontent.com/368965/122668894-abb7be00-d1ba-11eb-9db0-8f2966ea7d62.png)

**Comment by kevin-brown** [comment]
I couldn't find my duplicate target for this, but this is a "feature" of your browser where it won't send an empty selected value (because nothing was selected) and instead just doesn't send anything. This happens with a standard multiple select and as a result Select2 meets the spec here.

This is not a bug and is specific to multiple selects with no selections made.

**Comment by Cyrille37** [comment]
You've right @kevin-brown , all tested browsers does not send a empty multiple select. I did not find nothing about in [HTML5 spec](https://html.spec.whatwg.org/multipage/form-elements.html#attr-select-multiple) not either at w3school and mdn ...
So we cannot use multiple select for editable form (like CRUD), but only for simple form submit ; it's a shame.

**Comment by honsberg** [comment]
is there any work-around to submit a specific value for empty?
