### ISSUE TITLE
templateResult doesn't support ES6 template literals

### ISSUE THREAD

**Issue by antonioaltamura** [select2/select2#6064]
Hello,
I've just noticed `templateResult` https://select2.org/dropdown#templating doesn't render ES6 template literals. Is that something planned to be fixed? 

https://jsfiddle.net/alfredopacino/e9zpvb06/4/

**Comment by kevin-brown** [comment]
This isn't an issue with template literals, the same code doesn't work with JS and string concatenation. The issue is actually that you're returning just a string from the template and it contains HTML. So to avoid XSS attacks, we automatically escape the HTML string which is what you're seeing. In order to work around this, you need to return a JS DOM or jQuery element from the templating function which won't be escaped.

You can see an example of this in the AJAX section.
