### ISSUE TITLE
[BUG] Unable to unselect multiple with ajax--url

### ISSUE THREAD

**Issue by aweiand** [select2/select2#6070]
I'm testing this with latest version (4.1.0-rc.0) and previous stable (4.0.13). 
When using remote fetch URL (either data-* attributes or ajax in options) in a multiple select, it fails with unselect previous checked option.
I wrote this fiddle to demonstrate the bug: [https://jsfiddle.net/aweiand/yLejwkof/32/](https://jsfiddle.net/aweiand/yLejwkof/32/)

This is a snapshot just to illustrate the selections. In the input I put the number of selected fields. 
![image](https://user-images.githubusercontent.com/1443817/125681304-d2630ce8-ad59-4db5-862d-2195c411a639.png)

**Comment by kevin-brown** [comment]
I see what you're experiencing in the jsfiddle. More than likely a decorator is missing and that's causing issues. Will investigate more.

**Comment by kevin-brown** [comment]
Alright, so there are two pieces to this and unfortunately the one you've identified in the OP is not a bug, it's a misconfiguration.

Because you are not using the multiple select selection box, you lose the ability to deselect individual options using the selection area and you've only got the clear all button. Normally this would be fine except you have an empty option in your `<select>` which aligns with your placeholder, so the clear all button is not actually clearing them all and instead is replacing all of your selection with your placeholder. Removing the empty `<option>` fixes this issue and the clear all button behaves as one would expect.

Because you are using the single select selection container, the only other way to unselect items would be to use CTRL + SPACE in the dropdown. This is because SPACE and ENTER both map to only selecting options as explained in this commit: https://github.com/select2/select2/commit/017c20109471fa5b835603faf5dc37f7c2c2ea45 The way to toggle options (select or unselect) is via CTRL + SPACE, which if you try it in that jsfiddle does not appear to work. I am still looking in to if this is an actual bug, and if so what is causing it to occur, or if it's another misconfiguration caused by the custom dropdown adapter combination in use.

**Comment by aweiand** [comment]
Ok. But I need the empty option to show a "Select one" text to the user...
And sorry, what is the "multiple select selection box" what I'm not using (Can you provide an image?)?

Thank's a lot for the quickly response!! (but in my mind is a bug, because without ajax--url doesn't do this)

**Comment by aweiand** [comment]
I just update the fiddle to shows works without ajax options...
 - [https://jsfiddle.net/aweiand/4rhwsxea/12/](https://jsfiddle.net/aweiand/4rhwsxea/12/)
