### ISSUE TITLE
versions > 4.0.5  with Woocommerce variations selection conflict with default selection

### ISSUE THREAD

**Issue by njwgh** [select2/select2#6087]
If you use select2 to style the Woocommerce product variations form, then there are issues with select2 versions > 4.0.5

If you have a default value selected in your variations dropdown then you are are unable to re-select that default option from the dropdown, once you have selected another option.

select2 version 4.0.5 and less work correctly

Here is a link to a fresh wordpress and woocommerce install with no other plugins, that illustrates the problem:

[https://ofn.nataliewood.biz/product/test-product-1/](https://ofn.nataliewood.biz/product/test-product-1/)

The 'medium' size is selected by default. If you choose any other size then you can no longer reselect 'medium'

This is only an issue on the product variations form. Other forms with select elements in wordpress with woocommerce, styled by select2, work correctly.

The above example has wordpress: 5.8 and woocommerce 5.6.0 but it was also an issue with previous versions of both.

The libraries included in the above example are:

`        wp_enqueue_style( 'select2','//cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css');
        wp_enqueue_script( 'select2','//cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js', array('jquery'), '4.1.0',true);  
`

but all versions from 4.0.6 upwards have the same issue

my select2 initialisation is:
`	$('.variations_form select').select2({
		minimumResultsForSearch: Infinity, 
		 width: '100%', 
	});`

Note that the actual 'issue' is that the 'selected' attribute is not removed from the initial default option when a new option is chosen.
so in:
`Results.prototype.setClasses`

`item.element.selected `
is always true for the item that was initially set as the default, regardless of what other options have been chosen

This was working correctly in 4.0.5 which was using the
`var item = $.data(this, 'data');`
construct

whereas 4.0.6 and greater is using the 
`var item = Utils.GetData(this, 'data');`
construct

There is also a report of the same issue on stackoverflow:
[https://stackoverflow.com/questions/60616043/woocommerce-variations-with-select2-conflict-with-default-selection](https://stackoverflow.com/questions/60616043/woocommerce-variations-with-select2-conflict-with-default-selection)

Presumably most people would tend to use woocommerce 'selectwoo' to style the variations form and this does work as 'selectwoo' is based on a version of select2 < 4.0.6, however selectwoo has its own issues namely that it no longer supports using html for styling of the selected item, via templating.

Apart from woocommerce, I'm thinking that other plugins that change or manipulate select fields could also have a conflict and that there could be a subtle issue with the 'caching' of the select field data in the 'Utils' construct

**Comment by kevin-brown** [comment]
Looked into this really briefly and I'm going to say there's some magic happening in the `add-to-cart-variation.js` file that isn't well supported. Generally Select2 is able to handle the surprisingly dumb things that plugins do to the state of the dropdown, but occasionally we run into situations where they're doing stuff that is _extra dumb_ and it requires some extra research.

**Comment by ItsVlad** [comment]
I have exactly the same problem, find out two hacks/workarounds:

1. Small timeout (>= 120) on select2 init 
2. Calling the select2 init on document ajaxComplete event.

I know they are not the most appropriate workarounds but its the only things ive found that worked so far.

**Comment by gRoberts84** [comment]
I encountered this issue my self and in my case, it was down to there being more than one jQuery instance on the page.

As my build process was including jQuery too, events were spread across the different instances and confusing things. 

```
function tvw_remove_jquery() {
    if (!is_admin()) {
        wp_deregister_script('jquery');
        global $wp_scripts;
        foreach ($wp_scripts->registered as $key => $item) {
            if (in_array('jquery', $item->deps)) {
                $item->deps                   = array_diff($item->deps, ['jquery']);
                $wp_scripts->registered[$key] = $item;
            }
        }
    }
}
add_action('wp_enqueue_scripts', 'tvw_remove_jquery', PHP_INT_MAX);
```

Dequeuing jQuery and removing jQuery from all dependencies fixed the issue for me.

**Comment by dmitrijCraq** [comment]
Hi everyone,

I confirm the issue described by @njwgh and after a day I was able to solve. I'm currently using:

- Select2 4.1.0-rc.0 
- WordPress 6.1.1
- WooCommerce 7.3.0.

@kevin-brown you're right, there is some weird behaviour caused by the onFindVariation method inside add-to-cart-variation.js, in fact when I disable the enqueuing of the add-to-cart-variation script the Select2 works as expected.

This is the idea behind the fix:

1. The fix must be placed in your function.js or whatever script enqueued in your theme that you control. It is ideal that your script file is placed before add-to-cart-variation.js in your HTML.
2. Get the variation form object using jQuery and all the selects contained inside the variations form.
3. Add to the variation form jQuery object an event listener for the "check_variations" custom event defined and triggered by add-to-cart-variation.js. This event is triggered everytime the user changes the select value.
4. The handler of this custom event must destroy and re-initialize the Select2 instance for every selects inside the variation form.

This solution is not so elegant, because everytime you interact with the form you need to destroy and re-create the Select2 instance, however it is the only way I've found so far.

The following code explains the solution
```
const variationForm document.querySelector('form.variations_form.cart');`

if(variationForm !== null) {
   const $variationForm = $(variationForm);
   const wcSelects = [...variationForm.querySelectorAll('select')];

   $variationForm.on('check_variations', () => {
            wcSelects.forEach(wcSelect => {
                let $wcSelect = $(wcSelect);
                $wcSelect.select2('destroy');
                
                // This is a my custom class component that basically creates the Select2 instance
                new Select(wcSelect);
            });
        });
}
```

Hope It can help
