### ISSUE TITLE
Preventing select2:opening disable tags feature

### ISSUE THREAD

**Issue by antonioaltamura** [select2/select2#6088]
I'm trying to make select2 work with no data source, with only `tags:true` flag.
That would basically mean disable the dropdown.
I noticed if you use `tags:true` and prevent `select2:opening` event, the tags feature is in fact disabled. It is kind of expected, as the `tags` feature automatically select the first option of the select. Still, I'm not sure it is the behaviour you want to get in this scenario, the 2 things should work independently if needed.

https://jsbin.com/lowiwik/edit?html,js,output

**Comment by kevin-brown** [comment]
Select2 is not an autocomplete or typeahead, which is almost seems like what you're looking for. Since you're disabling opening the dropdown, and because Select2 does not support changing selections without opening the dropdown (except for deleting), you're running into expected behaviour.

----

This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://select2.org/troubleshooting/getting-help
[irc]: https://select2.org/troubleshooting/getting-help
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes
