### ISSUE TITLE
Tooltip is not present on remote selected li items

### ISSUE THREAD

**Issue by synth** [select2/select2#6119]
We moved a standard select2 to using remote data source. Our tests that verify functionality broke and we traced it to the fact that when the data source was inline, title attributes (tooltips) are added for both preselected options and newly selection options. However, when we moved to a remote data source, the title tags remain present for preselected options, but are NOT present for newly selected items from the remote source. 

We saw this on version 4.0.0 and upgraded to 4.0.13 and the issue remains. This can be reproduced via this jsbin: https://jsbin.com/bonahevepu/1/edit?html,js,output

<img width="1653" alt="Screen Shot 2021-11-07 at 4 09 05 PM" src="https://user-images.githubusercontent.com/10546/140667379-ddf8527d-e5c4-4638-b905-0a7da891260b.png">

**Comment by kevin-brown** [comment]
This is because the options are not being mapped to have a `text` or `title` property on the remote data. This is something which we call out in the 4.x migration documentation as well as in the AJAX section where we do this for the GitHub example to ensure it is mapped properly.

**Comment by synth** [comment]
@kevin-brown Thx for getting back. Would you mind sharing what migration docs you are talking about? I was able to hunt down [this one](https://github.com/select2/select2/blob/develop/docs/pages/15.upgrading/01.new-in-40/docs.md), but it doesn't really mention what you are talking about. It also links to changelogs, which also don't really mention this. So, not sure if I'm missing something, or if the documentation you're referring to is somewhere else. Thx.

**Comment by kevin-brown** [comment]
This is primarily called out in https://select2.org/data-sources/formats, given that the Select2 data format is what Select2 expects from the AJAX results. You can also see a brief snippet showing it at the AJAX pagination section at https://select2.org/data-sources/ajax#pagination. In the migration docs is where it calls out that these attributes are strictly enforced now (since they previously weren't in 3.x) at https://select2.org/upgrading/migrating-from-35#the-id-and-text-properties-are-strictly-enforced.

This is something where I'd welcome PRs that automatically detected this an spit out a warning in debug mode if `text` is missing on objects in AJAX responses (or data adapter responses in general, also acceptable). We don't see the issue getting reported often so it hasn't been super high on my list of things to fix.
