### ISSUE TITLE
JavaScript execution on enter and XSS vulnerability

### ISSUE THREAD

**Issue by ReneKrewinkel** [select2/select2#6120]
See attached screenshot
![bug-select2](https://user-images.githubusercontent.com/15904823/141292010-0eccaa94-d960-4d3e-8cc8-9b1c1758513c.png)

**Comment by kevin-brown** [comment]
I have a feeling this has to do with configuration you're using involving result rendering or disabling escaping since I wasn't able to reproduce this on the documentation site.

----

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/
