### ISSUE TITLE
i18n dist files have invalid condition

### ISSUE THREAD

**Issue by MananTank** [select2/select2#6124]
Issue: BUG
Version: Latest (4.1.0)

See this dist for example:
https://github.com/select2/select2/blob/develop/dist/js/i18n/en.js

![image](https://user-images.githubusercontent.com/22043396/141753123-6047e5fa-bea4-436b-825a-23cdcea2c862.png)

Here the first condition is not quite right, everything after the condition should be wrapped in braces `if (...) { ... }` but it's not, so only the assignment to variable `e` is considered inside the condition and everything else after that is outside the condition, which is not right and throws error when the condition is false as in that case `e` is undefined

### Consider this case
When `jQuery.fn.select2` is `undefined`, the condition becomes false so variable `e` is not defined, but then code continues the execution and tries to do `e.define(...)` which throws an error because `e` is `undefined`. This is currently happening in our codebase

**Comment by kevin-brown** [comment]
So I looked at the underlying source here and the removal of the braces is accurate given the original code. This looks like a bug on the surface but it begs a bigger question: is this something we should be mitigating or should we just raise a warning in the console?

Ultimately it's a configuration issue to have things like the translations on the page without having Select2 there.

**Comment by MananTank** [comment]
@kevin-brown I agree it's wrong to have translations on the page without Select2. 
But looking at the condition, I assume the entire point of it is to guard against those cases and prevent throwing error, otherwise what's the point of having that condition?

**Comment by kevin-brown** [comment]
> otherwise what's the point of having that condition?

That condition is actually [a hack to make r.js connect language/translation files up with the AMD loader](https://github.com/select2/select2/blob/develop/src/js/banner.start.js) which is really the root of the problem here. There's probably something we can do about catching if _only_ the translation files are included on a page or if they are included before the Select2 main file.

The current issue with just throwing an `else` on there is that banner is also used for the Select2 main file, so it would always be triggered there. Again, there's probably a way to fix it in a different way (possibly just using different banners for language files vs the main file).
