### ISSUE TITLE
Searches HTML Tags

### ISSUE THREAD

**Issue by jsBiztech** [select2/select2#6126]
When HTML tags are set in Option, those tags are also returned as search results.
E.g.
Option is set as

```html
<div style="color:green">enhancement</div><div><b>Select2</b> supports custom themes using the theme option so you can style Select2 to match the rest of your application.</div>
```

and when i tries to search **_style_** or **_<div_** , it should not return any option as search result but it's returning each option as search result

URL: https://jsfiddle.net/onkf397b/

**Comment by kevin-brown** [comment]
Unfortunately this appears to be a configuration error on your part. The `text` attribute on the Select2 data options is for _text_, not HTML. Since this is the attribute that is matched during searches, if you include HTML in it then it will be matched as well. We recommend you do not include HTML within your text attribute on your data objects as a result.

Additionally, your disabling of `escapeMarkup` could present security issues and is not recommended as a result. We would recommend using `jQuery` elements instead containing your HTML and return those from your template methods. This will prevent unintended XSS injection within your dropdowns.
