### ISSUE TITLE
mousedown on select2-selection__clear will cause a selection of an item on up if the dropown appears at the __clear position

### ISSUE THREAD

**Issue by reimerdes** [select2/select2#6135]
Only relevant for multiselect with enough entries that more than one line is used.

Example: https://jsfiddle.net/1yahbc6L/2/
* Select all elements
* click into the input field of the multiselectbox so set the focus
* click on the clear x
* the `mousedown` removes all entries and box shrinks to one line.
* the focus remains within the multiselectbox
* the dropdown reapears and the `mouseup` event selects whatever element is at the mouse cursor position.

In my opinion select2-selection__clear should use click like used with selection__choice__remove.
Maybe I am missing a constraint that is solved by using mousedown. Otherwise it feels like inconsistent behaviour.

Changing the event from mousedown to click seems to work fine for us.

**Comment by reimerdes** [comment]
Only relevant for multiselect with enough entries that more than one line is used.
Might be to our custom styling (clear at the bottom right corner of select2-selection.

If i click on the clear x 
* the mousedown removes all entries and box shrinks to one line.
* the dropdown reapears and the up selects whatever element is at the mouse cursor position.  

In my opinion `select2-selection__clear` should use `click` like used with `selection__choice__remove`.
Maybe I am missing a constraint that is solved by using mousedown.

Changing the event from `mousedown` to `click` seems to work fine for us.

**Comment by kevin-brown** [comment]
I'm going to call this an interesting edge case, and I'm not sure it's common enough to warrant a fix. This can happen in a standard multiselect box with the following steps:

1. Go to a standard multiselect box https://select2.org/getting-started/basic-usage#multi-select-boxes-pillbox
2. Select an option
3. Remove focus from the multiselect such that the dropdown closes
4. Mouse down on the clear icon
5. While mouse is held down, mouse up over the (now open) dropdown
6. Observe the dropdown option is selected and the dropdown closes

In order for this to happen with the example steps you outlined, the dropdown would need to appear where the clear icon is located. This is something that doesn't happen by default in Select2 configurations and as such the only way to truly reproduce it is to forcibly move the mouse during the clear action (which can occur).

The reason why the clear icon triggers on `mousedown` has to do with the behaviour in single selects and trying to keep it consistent within a multiselect as well. In a single select, it's possible to mousedown on the selection area and subsequently mouseup in the dropdown area to allow for a quick selection with a single mouse click (something which can typically be observed in your browser's default single select as well). Could we switch it to be a click within a multiselect? Sure. Is it worth it to create an extra branch within the clear icon handler? Probably not.

I'm marking this as "needs information" because it's totally possible I'm missing something here that would make this a more common issue.

**Comment by reimerdes** [comment]
![Jan-05-2022 09-55-09](https://user-images.githubusercontent.com/10461938/148189292-11c3eae5-7676-4893-ad05-50661e3d006a.gif)

Sorry i didn't mention the screensize for the fiddle example. 
The cursor is not moving, but the box is because it's smaller without entries.
