### ISSUE TITLE
HTML errors

### ISSUE THREAD

**Issue by ghost** [select2/select2#6237]
Hi,

While validating my HTML page with https://validator.w3.org/nu/#textarea, I noticed that the Select2 library had some HTML errors.

![screen](https://user-images.githubusercontent.com/59090546/226673476-d0216add-804a-4c05-be6d-e34dabb09c70.png)

JS Bin: https://jsbin.com/suxumej/edit?html,js,output

Steps to reproduce:
1. Copy and paste the HTML code below in a file (about the same as on the JS Bin):
```html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width">
		<title>Select2 HTML errors</title>
		<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet">
		<script src="https://code.jquery.com/jquery-3.6.4.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
		<script>
			$(document).ready(function ()
			{
				$('#example1').select2();
			});
		</script>
	</head>

	<body>
		Selections:
		<select id="example1">
			<option value="1">Option 1</option>
			<option value="2">Option 2</option>
			<option value="3">Option 3</option>
			<option value="4">Option 4</option>
		</select>
	</body>
</html>
```
2. Open the HTML file in a browser.
3. Open the web development console.
4. Click on the `<select>` element to open the dropdown created by Select2.
5. Copy the dynamic HTML content from the web development console.
6. Paste the dynamic HTML content into https://validator.w3.org/nu/#textarea.

Here is a gif to summarize the steps:

![summary](https://user-images.githubusercontent.com/59090546/226673295-7252090a-fc4d-441b-844f-d598ae4fdb95.gif)

**Comment by kevin-brown** [comment]
This appears to be more of a usage question than a bug report or common feature request.  As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list][ml], [IRC][irc], or [Stack Overflow][so].

[ml]: https://select2.org/troubleshooting/getting-help
[irc]: https://select2.org/troubleshooting/getting-help
[so]: http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes

**Comment by ghost** [comment]
> This appears to be more of a usage question than a bug report or common feature request. As we continue to keep the Select2 issue tracker geared towards these two areas, bug reports and common feature requests, we are redirecting usage questions to other communities such as the [mailing list](https://select2.org/troubleshooting/getting-help), [IRC](https://select2.org/troubleshooting/getting-help), or [Stack Overflow](http://stackoverflow.com/questions/tagged/jquery-select2?sort=votes).

@kevin-brown I don't really agree with your answer: this is not an usage question, but this is a bug report. The HTML code generated by Select2 does not respect the HTML semantics and rules and should be fixed, in my humble opinion. Especially since these 3 errors are very easy to fix. By having HTML errors, some browsers or screen readers may misinterpret the code and not work as expected. As you can see, the validator does not return notices or warnings, it returns errors.

Solutions:
- Error 1: remove the `role="textbox"` attribute, because it's not allowed when the input is `type="search"`.
- Error 2: remove the `autocorrect="off"` attribute, because it's a non-standard attribute.
- Error 3: we could use `<div>` for the parent elements instead of `<span>`, and if there is a display issue (because the default display is `inline` for `<span>` and `block` for `<div>`), this should be solved with CSS by changing the `display` property.

**Comment by kevin-brown** [comment]
You're right, I closed this as a usage question when I should have closed it as a wontfix.

I'm going to be very real with you, the errors returned by the W3C HTML validator have always been suspect and continue to be. Part of it has to do with the HTML spec historically being a "suggestion" of a set of rules with browsers doing their own things based on it.

> Bad value textbox for attribute role on element [input](https://html.spec.whatwg.org/multipage/#the-input-element).

This is complaining because of a redundant use of a `role` attribute following [WAI-ARIA guidelines for a `combobox`](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/). Part of the issue here is that Select2 has to work with the limited recommendations that we've been given by WAI-ARIA trying to make the select box accessible to our users, and the W3C validator doesn't always love those recommendations. The typical recommendation here would be to use `role="searchbox"`, but that is not currently compatible with a `combobox` which presents it's own issues.

> Attribute autocorrect not allowed on element [input](https://html.spec.whatwg.org/multipage/#the-input-element) at this point.

This is complaining about a non-standard `autocorrect` attribute [used primarily by the Safari web browsers](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text#autocorrect) (mobile and desktop) to control whether or not autocorrect takes place within an input box.  Users expect to filter a dropdown based on what they are typing and not based on what Apple or anyone else thinks they are typing, and as such removing this attribute would be detrimental to the user experience. Browsers which do not support this attribute will silently drop it per the spec, so this shouldn't be much of an issue.

> Element [ul](https://html.spec.whatwg.org/multipage/#the-ul-element) not allowed as child of element [span](https://html.spec.whatwg.org/multipage/#the-span-element) in this context. (Suppressing further errors from this subtree.)

Again, accessibility and the HTML specification battle again. We cannot use a `<div>` here because a select box is not a block element, it's an inline (I think technically inline-block) element and as such does not disrupt the page flow.  But a `combobox` works most consistently across screen readers when the `tree` that it is referencing is a list element, so that needs to be a block element. But block elements can't be within inline elements. We value accessibility over conformance to the HTML spec here.

---

If you wish to patch these within your own copy of Select2, by all means go for it. But these are not currently being entertained in the Select2 core.

**Comment by ghost** [comment]
> This is complaining because of a redundant use of a `role` attribute following [WAI-ARIA guidelines for a `combobox`](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/). Part of the issue here is that Select2 has to work with the limited recommendations that we've been given by WAI-ARIA trying to make the select box accessible to our users, and the W3C validator doesn't always love those recommendations. The typical recommendation here would be to use `role="searchbox"`, but that is not currently compatible with a `combobox` which presents it's own issues.

Indeed, for accessibility, the `<input>` should have `role="searchbox"` or `role="textbox"`, and since here your `<input>` has a `type="search"`, this causes problems. But knowing that you are defining a `role`, the `type` is irrelevant right? Are you using a native `type="search"` functionality? If not, you could just use `type="text"` which implicitly has the `role="textbox"`.

> This is complaining about a non-standard `autocorrect` attribute [used primarily by the Safari web browsers](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text#autocorrect) (mobile and desktop) to control whether or not autocorrect takes place within an input box. Users expect to filter a dropdown based on what they are typing and not based on what Apple or anyone else thinks they are typing, and as such removing this attribute would be detrimental to the user experience. Browsers which do not support this attribute will silently drop it per the spec, and everyone will be happy.

I agree with you on this part, this error is not the most important to fix. It's just a question about standard and quirks for some browsers.

> Again, accessibility and the HTML specification battle again. We cannot use a `<div>` here because a select box is not a block element, it's an inline (I think technically inline-block) element and as such does not disrupt the page flow. But a `combobox` works most consistently across screen readers when the `tree` that it is referencing is a list element, so that needs to be a block element. But block elements can't be within inline elements. 😱 We value accessibility over conformance to the HTML spec here.

Concerning this error, did you think about using `<div style="display: inline-block;">` (or `inline`) instead of `<span>`? A block element (`<ul>` here) should never be contained within an inline element (`<span>` here). I believe that this solution should have no accessibility issues and would be fully compliant.
