### ISSUE TITLE
automatic dropdownParent

### ISSUE THREAD

**Issue by WellingtonNico** [select2/select2#6284]
hello guys, what about change this:
```js
function AttachBody (decorated, $element, options) {
    this.$dropdownParent = $(options.get('dropdownParent') || document.body);
    console.log('dropdown parent',this.$dropdownParent)

    decorated.call(this, $element, options);
  }
  ```
  to this:
```js
function AttachBody (decorated, $element, options) {
    this.$dropdownParent = $(options.get('dropdownParent') || $element.closest('div') || document.body);
    console.log('dropdown parent',this.$dropdownParent)

    decorated.call(this, $element, options);
  }
  ```
  
  why?
  many times we need to change the data-dropdown-parent or directly dropdownParent option, but it is annoying and it could be solved just making the change above

**Comment by kevin-brown** [comment]
While I love the idea of this, this is something we defer to implementers since it varies so widely. A lot of people choose to target `<form>` tags and modals, so there isn't really a single option that is going to please everyone.

The good news is this is easy for you to implement when you're initializing Select2 within your own application.
