### ISSUE TITLE
NPM missing older versions

### ISSUE THREAD

**Issue by tvardy** [select2/select2#6327]
Hey,

Would it be possible to publish the older versions to the NPM registry?

There are probably more reasons others would like it on the registry, like being able to use it in something like [unpkg.com](http://unpkg.com/) or [codesandbox.io](http://codesandbox.io/). For us, we would be able to correctly attribute the project with the right credit and provide the right license information.

**Comment by kevin-brown** [comment]
Unfortunately this isn't quite as easy as switching to those tags and pushing straight to NPM - I believe most of the existing 3.x tags are from custom builds since the project wasn't set up for NPM prior to 4.x. As a result it's unlikely this is ever going to happen, so I'm going to close off this ticket for now.
