### ISSUE TITLE
quietMillis does not delay ajax search

### ISSUE THREAD

**Issue by fckas** [select2/select2#740]
As soon as the input is at minimumInputLength value, then the search is run immediately despite having a 5 second (5000ms) long delay.
Typing too fast results in an ajax error.

**Comment by fixbugsnow** [comment]
fckas's original (select2) concern is valid ... faced same fast-typing error ... on fast typing (due to the field's select2/object instantiation delays? - didn't yet dig select2.js further as to why), select2 returns in error - as it tries to cancel the previous Ajax call for the (partially typed) type-ahead - with "abort"  values, as shown in the IF stmt below ... all I did was just trap this 'specific' condition and ignore it:

//RESULTS Typeahead 
this.$("[name=results]").select2({   
    tags: true,
    multiple: true,
    minimumInputLength: 1,
    quietMillis: 50, //or 100 or 10
    ajax: { 
        url: fetchResultsUrl,
        dataType: 'json',
        params: {
            error: function(err,errText,errType) {
                if (      err.readyState == 0 
                    && err.status == 0 
                    && err.statusText == "abort" 
                    && err.errText == "abort" 
                    && err.errType == "abort")
                {
                    //this happens when typing too fast in the Select2 type-ahead - DO NOTHING!!
                    console.log('Select2.js fast type ahead condition encountered and handled properly');
                } else {
                    //process proper errors
                }
            }
        }
    }
});

Hope this helps. Thanks.

**Comment by youmee** [comment]
**[SOLUTION]**
They changed property name from **quiteMillis** to **delay**. Use `delay: 500` instead.
https://select2.github.io/options.html#a-request-is-being-triggered-on-every-key-stroke-can-i-delay-th
